- lib/helper/writeConfigFile.js
> Concurrent build causes race condition

- cli.js
also add -h as alias for --help
Signed-off-by: Arnav Gupta <championswimmer@gmail.com>
> show usage when no args supplied

- README.md
Added note for windows users as discussed here: #59
> Updated "How we used it so far" part of README.md

- README.md
Hi, accordingly with #62, added link to grunt plugin. Feel free to merge or not to merge it :)
> Added link to grunt plugin. #62

- README.md
- lib/win.js
Create a new configuration option called `verbosity` which is a value from 0-4
that will get passed as the -Vx flag to makensis. The values match the
levels in makensis.  Defaults to 3.
> Add config option for verbosity

- .eslintrc
- index.js
- lib/helper/writeConfigFile.js
- lib/osx.js
- lib/win.js
Hi @stefanjudis,
you're using some rules for linting and in the contributing.md you're asking not to create lines with length more than 80. So I've added this rule to the `eslintrc` and also fixed some linting issue. 
Feel free to change or comment anything.
> Updated linting rules

- README.md
> fix grammar and clarify electron-packager dependency

- .idea/dictionaries/develar.xml
- .idea/runConfigurations/ArtifactPublisherTest.xml
- .idea/runConfigurations/BuildTest.xml
- .idea/runConfigurations/RepoSlugTest.xml
- appveyor.yml
- lib/win.js
- package.json
- src/build-cli.ts
- src/packager.ts
- src/platformPackager.ts
- src/winPackager.ts
- templates/win/installer.nsi.tpl
- test/BuildTest.js
- tsconfig.json
- typings/command-line-args.d.ts
As part of easy migration to new API
> Add target option to build nsis instead of squirrel windows installer

- .npmignore
> Fixing a dependency for cli.js

- package.json
- src/linuxPackager.ts
- src/macPackager.ts
- src/packager.ts
- src/platformPackager.ts
- src/promisifed-fs.ts
- src/winPackager.ts
- test/BuildTest.js
- test/helpers/packTester.js
- test/winPackagerTest.js
- typings/main/ambient/fs-extra/fs-extra.d.ts
PR is required to fix windows-installer — blocked on https://github.com/electronjs/windows-installer/pull/22
> fix(windows): do not rename artifacts twice

- README.md
- package.json
> docs: Add Electron Release Server as an alternative to Nuts #185

- package.json
- src/winPackager.ts
> fix: Getting "no such file or directory, rename ..." #208

- .idea/runConfigurations/linuxPackagerTest.xml
- .idea/runConfigurations/winPackagerTest.xml
- lib/linux.d.ts
- lib/linux.js
- package.json
- src/builder.ts
- src/codeSign.ts
- src/index.ts
- src/linuxPackager.ts
- src/macPackager.ts
- src/metadata.ts
- src/packager.ts
- src/platformPackager.ts
- src/promise.ts
- src/repositoryInfo.ts
- src/util.ts
- src/winPackager.ts
- templates/linux/after-install.tpl
- templates/linux/after-remove.tpl
- test/README.md
- test/fixtures/no-author-email/package.json
- test/fixtures/test-app-one/package.json
- test/fixtures/test-app/package.json
- test/src/BuildTest.ts
- test/src/helpers/expectedContents.ts
- test/src/helpers/packTester.ts
- test/src/helpers/runTests.ts
- test/src/linuxPackagerTest.ts
- tsconfig.json
> feat: use productName from app/package.json if present #204

- .idea/runConfigurations/winPackagerTest.xml
- .idea/runConfigurations/winPackagerTest__debug_logging_.xml
- src/winPackager.ts
- test/fixtures/no-author-email/package.json
- test/fixtures/test-app-one/package.json
- test/fixtures/test-app/package.json
- test/src/helpers/packTester.ts
- test/src/helpers/runTests.ts
> fix: Windows nupkg downloaded twice each time

- .travis.yml
- appveyor.yml
- package.json
https://github.com/travis-ci/travis-ci/issues/2311#issuecomment-200597613
> chore: use Xcode 7 (nvm preinstalled), don't install nsis on appveyour

- docs/options.md
- package.json
- src/builder.ts
- src/index.ts
- src/metadata.ts
- test/src/helpers/expectedContents.ts
- tsconfig.json
> fix: Error publishing to github when building on travis #261

- docs/options.md
- package.json
- src/macPackager.ts
- src/platformPackager.ts
- test/src/osxPackagerTest.ts
- typings/electron-packager.d.ts
prepare to fix #69 — but it requires fix ds-store as well, not only appdmg
> test: tiffutil error #69

- docs/options.md
- package.json
- src/metadata.ts
- src/winPackager.ts
- test/fixtures/test-app-one/package.json
- test/fixtures/test-app/package.json
- test/src/BuildTest.ts
- test/src/helpers/packTester.ts
- test/src/helpers/runTests.ts
- test/typings/decompress-zip.d.ts
> fix: Windows installer metadata is incorrect #278

- docs/options.md
- package.json
- src/linuxPackager.ts
- src/metadata.ts
- src/packager.ts
- src/platformPackager.ts
- test/src/BuildTest.ts
- test/src/helpers/fileAssert.ts
- test/src/helpers/packTester.ts
> feat: Ability to customize the output directory

- package.json
- src/builder.ts
- src/linuxPackager.ts
- src/macPackager.ts
- src/metadata.ts
- src/packager.ts
- src/platformPackager.ts
- src/util.ts
- src/winPackager.ts
- test/src/BuildTest.ts
- test/src/helpers/packTester.ts
- test/src/helpers/runTests.ts
- test/src/linuxPackagerTest.ts
- test/src/osxPackagerTest.ts
- test/src/winPackagerTest.ts
- tslint.json
Allow osx as platform id
Closes #301
> fix: check that electron-packager create out directory

- docs/Multi Platform Build.md
> docs: build of 32 bit from a machine with 64 bit

- package.json
> chore: use pre-git instead of pre-commit

- package.json
- src/codeSign.ts
- src/metadata.ts
- src/packager.ts
- src/promise.ts
- src/repositoryInfo.ts
- src/winPackager.ts
No need to define CSA_LINK explicitly
> feat: import startssl certs by default

- README.md
- docs/Multi Platform Build.md
- docs/Options.md
- package.json
- src/builder.ts
- src/cliOptions.ts
> docs: Multiplatform Build Documentation is lacking

- .idea/dictionaries/develar.xml
- docker/nsis.sh
- docs/NSIS.md
- docs/Options.md
- package.json
- src/errorMessages.ts
- src/fpmDownload.ts
- src/httpRequest.ts
- src/metadata.ts
- src/packager.ts
- src/platformPackager.ts
- src/targets/nsis.ts
- src/targets/squirrelWindows.ts
- src/winPackager.ts
- templates/nsis/FileAssociation.nsh
- templates/nsis/NsisMultiUser.nsh
- templates/nsis/allowOnlyOneInstallerInstace.nsh
- templates/nsis/boring-installer.nsh
- templates/nsis/checkAppRunning.nsh
- templates/nsis/installer.nsi
- templates/nsis/readme.md
- test/fixtures/test-app-one/package.json
- test/fixtures/test-app/package.json
- test/src/helpers/avaEx.ts
- test/src/helpers/packTester.ts
- test/src/winPackagerTest.ts
- test/tsconfig.json
- tsconfig.json
- typings/uuid-1345.d.ts
* file associations are not implemented
* "boring" installer is not polished.
* uninstaller is not signed (http://nsis.sourceforge.net/Signing_an_Uninstaller)
Closes #472 #493
> feat: NSIS target

- README.md
I'm not an English native speaker either but I tried to improve some stuff on the docs. Feel free to take whatever you like or ditch it completely. That is just my way to give back for the awesome project!
Now I only need the protocol feature for Windows :-P
> Minor English improvements

- src/metadata.ts
- src/targets/nsis.ts
Adding a flag to disable warnings as errors for NSIS
> feat(nsis): NSIS warnings as errors #763

- src/util/util.ts
Whoops, when fixing as per review in #881, accidentally broke the code.
> fix: typo in handling of npmArgs

- README.md
text editors "complain" when using this snippet because this extra comma
> remove unnecesary comma

- src/asarUtil.ts
Found this issue with the recent release.  Not all files are being unpacked.
> fix: write remaining files to unpack

- nsis-auto-updater/src/NsisUpdater.ts
- templates/nsis/boringInstaller.nsh
- templates/nsis/oneClick.nsh
After updating with the auto updater, the first start will start with a "--updated" flag
> feat: First start after update will start with a flag

- src/yarn.ts
fixes https://github.com/electron-userland/electron-builder/issues/1027#issuecomment-268066701
> fix: order of platform and arch npm env vars

- src/packager.ts
- test/src/BuildTest.ts
This is fix #1031 and #953  issue
> Trim suffix from wine version

- nsis-auto-updater/src/electronHttpExecutor.ts
- src/util/nodeHttpExecutor.ts
> fix: Removing the abort trigger from httpExecutor

- docs/Auto Update.md
Replaced - 
updateinfo >> UpdateInfo
versioninfo >> VersionInfo
> Fixed small typo errors in link

- packages/electron-updater/src/GenericProvider.ts
- packages/electron-updater/src/api.ts
> fix(electron-updater): channel & channelFile mismatch for macOS GenericProvider publishing (#1203)

- docs/Publishing Artifacts.md
Integrate fragment into previous sentence.
> Grammar correction

- packages/electron-builder/src/publish/PublishManager.ts
S3 options can now contain macros to allow something like this:
```
"publish": {
"provider": "s3",
"bucket": "some-bucket",
"path": "${os}/${env.SOME_ENV}"
}
```
Now `bucket`, `path` and `channel` can contain macros. Previously these options couldn't be configured with macros.
> feat(deployment): expand macros in S3 options

- README.md
change downloads per month shield from fs-extra to electron-builder
> docs: Fix downloads per month shield

- packages/electron-updater/src/NsisUpdater.ts
> check for EACCES error when try to install on auto updated windows

- CONTRIBUTING.md
Refs: https://github.com/electron-userland/about/pull/4
> Add code of conduct

- .idea/dictionaries/develar.xml
- docs/Multi Platform Build.md
- docs/Options.md
- packages/electron-builder/src/fileMatcher.ts
- packages/electron-builder/src/metadata.ts
- packages/electron-builder/src/packager.ts
- packages/electron-builder/src/util/config.ts
- packages/electron-builder/src/util/yarn.ts
- test/out/__snapshots__/ignoreTest.js.snap
- test/src/ignoreTest.ts
- yarn.lock
> Merge develar branch

- packages/electron-builder/src/util/packageDependencies.ts
- packages/electron-builder/src/util/yarn.ts
the solution for this https://github.com/EmergingTechnologyAdvisors/node-serialport/issues/1180#issuecomment-320975958 issue
> call rebuild with version

- packages/electron-builder/src/builder.ts
- test/src/BuildTest.ts
> Fix parsing of CLI '-c' arguments when combining values with a config file path

- docs/publishing-artifacts.md
After discussion with @develar on slack. I've been using this workflow for a couple of days now and seems to work fine.
> Add s3 workflow documentation

- packages/electron-builder/templates/nsis/include/installer.nsh
- packages/electron-builder/templates/nsis/installSection.nsh
> feat(nsis): KeepShortcuts mechanism is not functional

- packages/electron-builder/templates/nsis/assistedMessages.yml
- packages/electron-builder/templates/nsis/messages.yml
**Feature:** Brazilian portuguese language for `nsis` installation
Refs to #1992
> feat(nsis): brazilian portuguese language

- packages/electron-builder-squirrel-windows/src/squirrelWindows.ts
> Use convertVersion for version in squirrel packageFile

- packages/electron-updater/src/AppUpdater.ts
Also made "Quit" a lowercase "exit"
> Include application name in update notification

- packages/electron-builder/templates/nsis/oneClick.nsh
> fix(nsis): NSIS installer is crashing on "Exit" (Admins on Win7)

- docs/auto-update.md
Hi there! Just a small PR to change grammar. Got tripped up here because `whereas` usually means `in contrast to` rather than `consequently`. Thanks for your work on this!
> Grammar changes

- packages/electron-builder-lib/templates/nsis/assistedInstaller.nsh
https://github.com/electron-userland/electron-builder/issues/2372
https://github.com/electron-userland/electron-builder/issues/1501
> add customWelcomePage macro

- packages/electron-builder-lib/src/util/AppFileCopierHelper.ts
This will resolve the "__shim.js" not found issue. #2319
> Added "path.resolve()" to "const shimPath"

- packages/electron-builder-lib/templates/nsis/assistedMessages.yml
- packages/electron-builder-lib/templates/nsis/messages.yml
> feat(nsis): simplified Chinese version of messages during installation

- packages/electron-updater/src/BaseUpdater.ts
> fix(linux): use updateInfo.path as AppImage installer name

- docs/cli.md
- packages/electron-builder/src/builder.ts
> docs: modify example to reflect deprecation of --em

- packages/electron-builder-lib/src/targets/MsiTarget.ts
> fix(msi): put appId in file shortcut to fix notifications in win8/win10

- docs/auto-update.md
> docs: use obj destructor

- packages/app-builder-lib/templates/nsis/assistedMessages.yml
> feat(nsis): add japanese language

- packages/app-builder-lib/src/options/macOptions.ts
- packages/app-builder-lib/src/targets/pkg.ts
Add the ability to set a custom background image, welcome message, and
conclusion message to PKG installers.
> feat: add more pkg configuration options

- packages/app-builder-lib/src/electron/electronVersion.ts
- packages/app-builder-lib/src/util/packageMetadata.ts
Fixes https://github.com/electron-userland/electron-builder/issues/3475
> fix(app-builder-lib): validate using semver.coerce()

- packages/electron-updater/src/NsisUpdater.ts
Proposed fix for https://github.com/electron-userland/electron-builder/issues/3535
> Pass requestHeaders to httpExecutor

- packages/app-builder-lib/src/binDownload.ts
- packages/app-builder-lib/src/targets/MsiTarget.ts
- packages/app-builder-lib/src/targets/nsis/NsisTarget.ts
- packages/app-builder-lib/src/targets/nsis/nsisUtil.ts
- packages/app-builder-lib/src/targets/tools.ts
- packages/electron-builder-squirrel-windows/src/SquirrelWindowsTarget.ts
- test/src/binDownloadTest.ts
- test/src/updater/differentialUpdateTest.ts
introduce environment variables to configure where the electron-builder-binaries are downloaded from.
related to electron-userland/electron-builder-binaries#21 and #1859
> feat: configurable electron-builder-binaries host

- packages/app-builder-lib/src/targets/MsiTarget.ts
- packages/app-builder-lib/templates/msi/template.xml
Added enhancements so menuCategory does what the code comments suggest it is supposed to do:
* Enable sub-directory in program files based on menuCategory or Author value in package.json
* Added Directory attribute to RemoveFolder tag in MSITarget so it passes wix MSI validation.
> menuCategory enhancement

- packages/app-builder-lib/templates/entitlements.mac.plist
The issue in detail is explained here
https://github.com/electron/electron-osx-sign/issues/192
> Bug fix for App sandbox not enabled (ITMS-90296)

- packages/app-builder-lib/templates/nsis/assistedInstaller.nsh
feat(nsis): 
add new interface to show custom page after change installation directory and before install start, like other running options.
> feat(nsis): show custom page after change lation and before install start 

- packages/app-builder-lib/electron-osx-sign/util-provisioning-profiles.js
Fixes (#4324) - When the command `security cms` runs, it will default to system keychains during a bamboo build even if a keychain is passed in using the CSC_KEYCHAIN environment variable.
Inside of getProvisioningProfileAsync function (found within electron-osx-sign package) I added a keychain arg to surface the CSC_KEYCHAIN environment variable as a flag to the `security` command.
This is best reproduced on a bamboo build agent machine. If you do not have a bamboo server to test with, follow these instructions:
1) Toggle debug mode for electron osx sign `debug=electron-osx-sign` 
2) set `CSC_KEYCHAIN` environment variable
3) build and ensure that during the signing process that the correct keychain file is being used (instead of login or system keychain)
1) This is my first contribution …
> added keychain flag to getProvisioningProfileAsync (#4324)

- packages/app-builder-lib/src/util/appFileCopier.ts
Fixes #4366 , see [this comment](https://github.com/electron-userland/electron-builder/issues/4366#issuecomment-547620535).
Hopefully I did not miss any special cases that you already considered. Otherwise, please guide me into the right direction and I will update the PR 😉
> feat: support nested node_modules

- docker/base/Dockerfile
> Bugfix: Upgrade libcurl3 to libcurl4

- packages/app-builder-lib/src/codeSign/windowsCodeSign.ts
> fix(app-builder-lib): signing certificate selection by sha1

- packages/app-builder-lib/templates/entitlements.mac.plist
> Update entitlements.plist to be compliant with electron-notarize requirements

- packages/app-builder-lib/src/targets/snap.ts
This debugging was accidentally introduced by me in https://github.com/electron-userland/electron-builder/pull/4237
> remove snap debugging

- packages/app-builder-lib/src/platformPackager.ts
This makes it a bit clearer IMO
> Improve wording of ASAR warning

- packages/app-builder-lib/templates/nsis/include/installUtil.nsh
With c84ecff171dac128a1d5552a1287a375dc57df07 a check for the return value of the uninstaller process was added, however a check if the uninstaller process itself was launched correctly was still missing.
This was causing issues with a customer of ours who uses Windows Group Policy restrictions that prevent the launch of executables residing inside the Temp folder.
For some examples how these GPOs work please see: http://www.fatdex.net/php/2014/06/01/disable-exes-from-running-inside-any-user-appdata-directory-gpo/
When our customer was running an update with the new installer, the uninstaller failed silently due to the GPO and the installer kept waiting infinitely for the process to return.
This commit now adds appropriate error handling if the `old-uninstaller.exe` process cannot be …
> Error handling if uninstaller cannot be launched

- packages/electron-updater/src/providerFactory.ts
Issue https://github.com/electron-userland/electron-builder/issues/4686
> DigitalOcean Spaces doesn't support multiple range requests

- packages/dmg-builder/vendor/mac_alias/alias.py
Fixes https://github.com/electron-userland/electron-builder/issues/4840
Same bug posted to vendor [here](https://github.com/al45tair/mac_alias/issues/6) with corresponding PR [here](https://github.com/al45tair/mac_alias/pull/7)
> Fixed bug in hard copy vendor lib mac_alias

- packages/app-builder-lib/scheme.json
- packages/app-builder-lib/src/electron/electronMac.ts
- packages/app-builder-lib/src/options/FileAssociation.ts
- test/snapshots/mac/macPackagerTest.js.snap
- test/src/mac/macPackagerTest.ts
> Add missing LSHandlerRank #4614

- packages/app-builder-lib/src/util/NodeModuleCopyHelper.ts
Added Changelog and Readme writing to excluded files
> Added Changelog and Readme writing

- packages/electron-updater/src/NsisUpdater.ts
This PR fixes the issue https://github.com/electron-userland/electron-builder/issues/4736
> fix: cannot parse blockmap when auto updating

- configuration/snap.md
These are the doc changes for #5073. 
(I based the branch on a Snap doc cleanup PR I already made; #5052)
> Docs: More snap options (for #5073)

- packages/electron-updater/src/windowsExecutableCodeSignatureVerifier.ts
Our code signing certificate contains Chinese company name in the CN field. Encoding issues may be complex on Windows so I just encode the powershell output as base64-ed UTF-8 bytes.
> fix(windows): fix encoding issues while verifying signatures

- tutorials/test-update-on-s3-locally.md
This is to help others out in testing their update process, as it was a bit of a journey to put together a good process and tutorial for myself.
> docs: tutorial on testing the update flow

- packages/app-builder-lib/scheme.json
- packages/app-builder-lib/src/options/SnapOptions.ts
- packages/app-builder-lib/src/targets/snap.ts
And here's the PR for the docs: #5074
> Snap: Add appPartStage and layout options

- packages/app-builder-lib/templates/nsis/assistedInstaller.nsh
Add an optional macro to customize the finishscreen
First time contributing, not sure whether this is correctly added
> feat:(nsis): Add ability to have a custom finish page

- packages/app-builder-lib/electron-osx-sign/util.js
This is an exact copy of https://github.com/electron/electron-osx-sign/pull/169
> Codesign all binary-like files

- packages/app-builder-lib/electron-osx-sign/util.js
Revert electron-userland/electron-builder#5322
Fix #5487
@adam-lynch @develar
> Revert "Codesign all binary-like files"

- packages/app-builder-lib/src/macPackager.ts
Follow-up for #5481 fixing mas support.
@vadim-termius @mmaietta @quanglam2807
> fix(mac): Pass platformName and options in doPack 

- packages/app-builder-lib/templates/nsis/include/extractAppPackage.nsh
Fixing nsis script to properly identify arm64 vs x64 vs ia32 package files within universal installers.
Issue: https://github.com/electron-userland/electron-builder/issues/5461
> fix: windows universal installer (#5461)

- packages/builder-util/src/log.ts
This else if statement is useless. I just purge it.
> chore(build-utils): remove useless statement in log.ts

- packages/app-builder-lib/scheme.json
- packages/app-builder-lib/src/options/linuxOptions.ts
- packages/app-builder-lib/src/targets/fpm.ts
> WIP: Package name can be specified using packageName option

- configuration/snap.md
Same change as #5690 but for the docs website
> docs: Update default stagePackages for Snapcraft (docs site)

- test/snapshots/BuildTest.js.snap
Updating snapshot from a previous PR
> fix: test snap update for abi_registry.json

- packages/builder-util/src/DebugLogger.ts
more info https://github.com/electron-userland/electron-builder/issues/3012
> Fix Problem building multiple mac targets:TypeError: pattern.startsWith is not a function

- packages/app-builder-lib/src/codeSign/windowsCodeSign.ts
> Fix: Use -NoProfile Flag on getCertFromStoreInfo

- encapsulated manual update via menu.js
there is no callback for showMessageBox method, it return a promise.
https://github.com/electron-userland/electron-builder/blob/8a6c48116cbe1c1a2ad49db7648acf3080978bcc/encapsulated%20manual%20update%20via%20menu.js#L46-L53
> fix code error

- auto-update.md
`checkForUpdatesAndNotify` Signature:
https://github.com/electron-userland/electron-builder/blob/4024544a91c8f1363cb44bd3dca1efed8adbabde/packages/electron-updater/src/AppUpdater.ts#L242
https://github.com/electron-userland/electron-builder/blob/4024544a91c8f1363cb44bd3dca1efed8adbabde/packages/electron-updater/src/AppUpdater.ts#L677-L680
> docs: Add missing `downloadNotification` parameter for `checkForUpdatesAndNotify`

- packages/app-builder-lib/src/util/yarn.ts
fix: using regex to determine yarn version to account for newer releases of yarn (i.e. yarn 3). fixes: #6069
Credit to @losses
> fix: add regex to support yarn 3 and future versions 

- .changeset/brave-plants-occur.md
- packages/electron-updater/src/BaseUpdater.ts
Fix import errors for fs and path so that the test for admin priviliges functions
Closes #6134
> fix(electron-updater): fix import errors

- README.md
Adding new sponsor, Keygen.sh, to our page!  CC @ezekg
Removing zulip chat and migrating it to Github Discussions
> chore: update readme and add new sponsor logo

- .changeset/stale-rocks-wonder.md
- netlify-docs.sh
- netlify.toml
- package.json
- packages/app-builder-lib/package.json
- packages/dmg-builder/package.json
- pnpm-lock.yaml
2nd attempt at https://github.com/electron-userland/electron-builder/pull/6244
> fix: dmg-license-dependency

- .changeset/seven-needles-wash.md
- packages/app-builder-lib/templates/nsis/assistedMessages.yml
> fix: Update assistedMessages.yml with additional translations

- package.json
- test/snapshots/BuildTest.js.snap
fix: rerunning test-linux to update snapshot for upstream dep that now uses additional dependencies
> fix: update test snapshot for updated dependency

- .changeset/purple-swans-beam.md
- packages/app-builder-lib/scheme.json
- packages/app-builder-lib/src/targets/nsis/nsisOptions.ts
- packages/app-builder-lib/src/targets/nsis/nsisUtil.ts
- test/src/windows/assistedInstallerTest.ts
Downgrading nsis to 3.0.4.1 since 3.0.4.2 throws virus false positive
Resolves #6334
> fix(nsis): downgrade nsis to 3.0.4.1

- README.md
Changing the location of sponsors and adding "looking for additional maintainers"
> docs: update-readme

- .changeset/thirty-items-do.md
- packages/app-builder-lib/package.json
- pnpm-lock.yaml
I believe this should resolve #6303
> chore(app-builder-lib): update electron-osx-sign from 0.5.0 to 0.6.0

- docs/configuration/pkg.md
- packages/app-builder-lib/src/options/pkgOptions.ts
> docs: fix newline for pkgOptions

- packages/app-builder-lib/templates/nsis/README.md
- packages/app-builder-lib/templates/nsis/assistedMessages.yml
- packages/app-builder-lib/templates/nsis/messages.yml
The translation quality for Traditional Chinese was poor. Change to the preferred word in Taiwan. README is also updated to be more comprehensive.
> fix(nsis): Update zh-tw translation

- .changeset/good-moons-push.md
- docker/build.sh
> chore: Adding node 16 docker images for electron-builder

- docs/tutorials/loading-app-dependencies-manually.md
> docs(app-deps): update for electron 17+

- .changeset/ten-dragons-rest.md
- packages/electron-updater/src/providers/GitHubProvider.ts
See https://github.com/electron-userland/electron-builder/issues/6784
> fix: Unable to find latest version on GitHub

- .changeset/purple-impalas-prove.md
- .circleci/config.yml
- .github/actions/pnpm/action.yml
- .github/actions/pretest/action.yml
- docker/build.sh
- docker/node/Dockerfile
- packages/app-builder-lib/src/targets/MsiTarget.ts
- packages/electron-updater/package.json
- pnpm-lock.yaml
> fix: moving typed-emitter from devDependency to dependencies

- test/snapshots/updater/nsisUpdaterTest.js.snap
- test/src/updater/nsisUpdaterTest.ts
> chore: Adding allowPrerelease github integration tests

- .changeset/wet-kangaroos-fail.md
- packages/app-builder-lib/src/targets/pkg.ts
readd --identifier to mac pkg builds to address issue #7348
> fix: readd --identifier to mac pkg build to address issue #7348

- .changeset/sharp-olives-decide.md
- packages/electron-updater/src/BaseUpdater.ts
https://github.com/electron-userland/electron-builder/issues/7393
> fix: inherit stdio for updated processes (#7393)

- .changeset/famous-terms-crash.md
- packages/electron-updater/src/AppImageUpdater.ts
- packages/electron-updater/src/BaseUpdater.ts
> fix: NsisUpdater - only resolving true if pid !== undefined

- .changeset/bright-numbers-provide.md
- packages/electron-updater/src/BaseUpdater.ts
Resolves the issue: 
https://github.com/electron-userland/electron-builder/issues/7532
> feat: nsis install method - exposed as public to avoid quit the app for the install

- .changeset/plenty-coats-dance.md
- packages/electron-builder/package.json
- pnpm-lock.yaml
> fix: Semver Vulnerability in simple-update-notifier package

- .changeset/smart-balloons-sip.md
- packages/electron-updater/src/providers/GitHubProvider.ts
This pull request implements the fix I suggested in #7665
> fix: for isCustomChannel in GitHubProvider.ts #7665

- .changeset/little-drinks-grin.md
- .github/actions/pnpm/action.yml
- .github/actions/pretest/action.yml
- docker/node/Dockerfile
Follow-up from: https://github.com/electron-userland/electron-builder/pull/7787
> chore: update docker node to latest version 18.18.2. update pnpm to 8.9.0

- README.md
> docs: remove 404 link

- .changeset/big-rice-sneeze.md
- docs/configuration/mac.md
- packages/app-builder-lib/scheme.json
- packages/app-builder-lib/src/options/macOptions.ts
see discussion in #7859
and #7861
> docs: update notarization docs

- .github/workflows/pr-labeler.yml
Reverts electron-userland/electron-builder#7937
> Revert "chore(deps): update actions/labeler action to v5"

- test/snapshots/globTest.js.snap
fix: update unit test snapshot to account for new package dependency files
> fix: update linux test snapshot

- .changeset/flat-glasses-smell.md
- packages/app-builder-lib/src/macPackager.ts
> fix(mac): Update mac notarize keychain env var to be optional

- .changeset/pre.json
- .changeset/stale-otters-turn.md
Entering alpha release stage to prepare for new electron-updater feature and migration to electron/rebuild
> chore: Enter alpha stage

- .changeset/neat-bottles-wash.md
- docs/configuration/msi.md
- packages/app-builder-lib/scheme.json
- packages/app-builder-lib/src/options/MsiOptions.ts
- packages/app-builder-lib/src/targets/MsiTarget.ts
> feat: support additionalLightArgs

- .changeset/lucky-otters-report.md
- docs/configuration/publish.md
- packages/app-builder-lib/scheme.json
- packages/builder-util-runtime/src/publishOptions.ts
> chore(docs): update Bitbucket Options token doc

- docs/multi-platform-build.md
> fix(docs/multi-platform-build.md): broken link of build.sh

- .changeset/gentle-bags-thank.md
- packages/app-builder-lib/src/targets/AppxTarget.ts
Reverts electron-userland/electron-builder#8203
> fix: Revert "feat(appx): Update identityName for windows 10"

- .changeset/green-parrots-drum.md
- packages/app-builder-lib/package.json
- pnpm-lock.yaml
Fixes: https://github.com/electron-userland/electron-builder/issues/8212
> chore: update read-config-file dependency

- .changeset/sour-mugs-greet.md
- docs/configuration/mac.md
- package.json
- packages/app-builder-lib/scheme.json
- scripts/jsdoc2md2html.js
Removing NotarizeLegacyOptions from docs generation script to fix broken CI/CD flow
> fix: resolve CI/CD docs generation issue

- .changeset/tidy-donkeys-protect.md
- packages/app-builder-lib/src/targets/nsis/nsisLicense.ts
fix  https://github.com/electron-userland/electron-builder/issues/8294
> fix: Nsis license file encode issue

- .changeset/light-pillows-end.md
- packages/builder-util/package.json
- pnpm-lock.yaml
- run-tests-in-docker-custom-app-builder.sh
> fix: updating app-builder dependency

- Pipfile
- Pipfile.lock
- mkdocs.yml
Reverts electron-userland/electron-builder#8350
> fix(docs): Revert "chore(deps): update dependency mkdocs to <1.7"

- Pipfile
- Pipfile.lock
- mkdocs.yml
- netlify-docs.sh
updating mkdocs, mkdocs-material, and setting explicit markdown-include
> chore: upgrade docs site packages

- .changeset/quiet-pugs-doubt.md
- packages/builder-util/package.json
- pnpm-lock.yaml
> fix: upgrade app-builder-bin with downgraded appimage tool

- .changeset/small-badgers-pull.md
- packages/app-builder-lib/src/targets/snap.ts
Fix #8423
@mmaietta @Rychu-Pawel
> fix: Snap publish regression

- .changeset/many-shoes-look.md
- packages/app-builder-lib/src/codeSign/windowsSignToolManager.ts
Resolves feedback per https://github.com/electron-userland/electron-builder/issues/8559
> chore: update logging to be a debug message

- package.json
- pnpm-lock.yaml
Resolves: https://github.com/electron-userland/electron-builder/security/dependabot/30
> chore: updating lint-staged to update internal micromatch

- .changeset/slow-zoos-mate.md
- packages/builder-util/package.json
- pnpm-lock.yaml
chore(deps): update app-builder-bin to 5.0.0-alpha.11
> chore(deps): update dependency app-builder-bin to 5.0.0-alpha.11

- .changeset/khaki-schools-provide.md
- packages/electron-updater/src/MacUpdater.ts
Fix https://github.com/electron-userland/electron-builder/issues/8622
> fix: copyFileSync operation will block the main thread

- .changeset/smooth-camels-decide.md
- packages/app-builder-lib/src/asar/asarUtil.ts
- packages/app-builder-lib/src/platformPackager.ts
Fixes https://github.com/electron-userland/electron-builder/issues/8345
> fix(asar): check ResolvedFileSet src when verifying symlinks to be within project directory

- .changeset/tame-buckets-drum.md
- docker/build.sh
> fix: docker build script unable to build node 18 image

- README.md
I really enjoyed using this project, nice work! Caught a couple of typos in the README.md though 😛
> chore: Update README.md, fix typo(s)

- .github/FUNDING.yml
Resolves: https://github.com/electron-userland/electron-builder/issues/8702
> chore: Update FUNDING.yml with dedicated Github sponsor link

- .changeset/dry-gifts-joke.md
- package.json
- pnpm-lock.yaml
- scripts/renderer/src/typedoc2html.ts
fixes: https://github.com/electron-userland/electron-builder/issues/8750
> fix(docs): downgrade typedoc-plugin-markdown to fix docs site generation

- .changeset/cuddly-colts-laugh.md
- packages/app-builder-lib/package.json
- pnpm-lock.yaml
- test/snapshots/globTest.js.snap
fixes: https://github.com/electron-userland/electron-builder/issues/8655
> fix: update @electron/asar to 3.2.18 to resolve signing issue with framework symlinks

- .github/workflows/deploy-docker.yml
- .github/workflows/test.yaml
`find` operation was using the incorrect directory for searching by name.
Verified in: https://github.com/electron-userland/electron-builder/actions/runs/12847215009
> fix: docker image loader for deploy pipeline

- packages/app-builder-lib/src/platformPackager.ts
- pnpm-lock.yaml
- test/package.json
- test/snapshots/PublishManagerTest.js.snap
- test/snapshots/mac/dmgTest.js.snap
- test/snapshots/mac/macPackagerTest.js.snap
- test/snapshots/updater/differentialUpdateTest.js.snap
- test/snapshots/windows/winPackagerTest.js.snap
- test/src/filesTest.ts
- test/src/helpers/packTester.ts
- test/src/mac/masTest.ts
- test/src/windows/winPackagerTest.ts
Initial work to prepare for implementing https://github.com/electron-userland/electron-builder/issues/8660
> chore: add new tests for Asar Integrity

- .changeset/slimy-masks-collect.md
- packages/app-builder-lib/src/macPackager.ts
- packages/app-builder-lib/src/targets/pkg.ts
Dear maintainer!
I added pkg notarization for macos packager.
Thanks for your supporting!
> feat(pkg): support notarizing pkg for macos archives

- .changeset/pretty-hounds-pull.md
Adding a changeset for https://github.com/electron-userland/electron-builder/pull/8571
> chore: add changeset for previous PR

- test/snapshots/HoistedNodeModuleTest.js.snap
Some dependency changes in our test fixture. Just updating snapshots to pass CI
> chore: update test snapshots

- pages/tutorials/release-using-channels.md
> docs: warn to set release channel for github publisher

- pages/auto-update.md
Actualize a debugging section for auto-updates functionality
> docs: Update auto-update.md

- README.md
Resolves: https://github.com/electron-userland/electron-builder/issues/9104
> fix(docs): Update README.md emoji rendering

- .changeset/mean-tigers-allow.md
- packages/app-builder-lib/src/electron/ElectronFramework.ts
- pnpm-lock.yaml
- test/package.json
- test/snapshots/ExtraBuildResourcesTest.js.snap
- test/src/ExtraBuildResourcesTest.ts
- test/src/helpers/packTester.ts
Follow up on https://github.com/electron-userland/electron-builder/pull/9126#issuecomment-2942996358 by adding additional unit test for verifying unpacked electron directories
> chore: add additional stack trace to `electronDist` error message

- .changeset/shaggy-garlics-joke.md
- .github/workflows/test.yaml
- packages/builder-util/src/util.ts
- test/snapshots/builder-util/utilTest.js.snap
- test/src/builder-util/utilTest.ts
This should cover handling spaces in secrets
Fixes: https://github.com/electron-userland/electron-builder/issues/9153
> fix: scrubbing more aggressively anything in the logs
