README.md
* Clarify that the Linux instructions are specifically for Ubuntu & its derived distributions
* Hint that `add-apt-repository` and `apt-get` usually require superuser privileges
* Other typographical changes in the vicinity
=> Clarify Linux install instructions

README.md
Here is a cleaner commit for the updating of the `osx.contents` window. Sorry for taking so long to get it.
=> Added more guidance to the description of osx.contents

templates/installer.nsi.tpl
Added some extras to the nsi template. When I added this, the desktop icon of the installed app was the icon that I provide, and not the default Electron icon. Without this, the app installs and the desktop icon is the Electron icon. So, this was a definite upgrade. I tested this on Win7 and Win10.
=> nsi.template update to fix missing desktop icon

package.json
It's difficult to find `electron-builder` on [npmjs.com](https://www.npmjs.com/). For example if you search for [electron installer](https://www.npmjs.com/search?q=electron+installer), it's not even listed.
I added a bunch of keywords that users might use when trying to find a solution for building/generating Electron installers. It should improve the discoverability of this project.
=> Add keywords to improve discoverability

README.md, lib/win.js, templates/installer.nsi.tpl
Very small patch to allow for version property in the nsi templates.
Let me know what you think.
Cheers
=> Added support for windows  Unistall/DisplayVersion

index.js, package.json
I was getting this error before my fixing:
```
- Running electron-builder 2.2.0
- Ouput directory ´/Users/maxcnunes/Development/sqlectron/sqlectron-gui/dist/installers/osx/´ does not exist
fs.js:747
return binding.mkdir(pathModule._makeLong(path),
^
Error: ENOENT, no such file or directory '/Users/maxcnunes/Development/sqlectron/sqlectron-gui/dist/installers/osx/'
at Error (native)
at Object.fs.mkdirSync (fs.js:747:18)
at Object.Builder.build (/Users/maxcnunes/Development/sqlectron/sqlectron-gui/node_modules/electron-builder/index.js:45:10)
at Object.<anonymous> (/Users/maxcnunes/Development/sqlectron/sqlectron-gui/node_modules/electron-builder/cli.js:36:9)
at Module._compile (module.js:460:26)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
at …
```
=> Fix problem creating nested directories with no parent

templates/installer.nsi.tpl
If the application is already running the installation fails so just kill it. 
Maybe it would be a better solution to show some info and drop the installation but my knowledge about NSIS is still quite limited so as to implement this kind of behavior.
=> Stop process if already running

README.md
Add info on setting Windows path to find `makensis`
=> Update documentation for Windows PATH, fixes #94

index.js
Simple use absolute path for `appPath` always.
=> Always use absolute appPath. Fixes #92

README.md
Since `rpm` is not supported yet, it should be removed from the README.
=> Fix: remove `rpm` mention in the readme

lib/linux.js
I got error:
```
1. linux
Error: Command failed: fpm -s dir -t deb --architecture i386 --rpm-os linux --name "TestApp" --force --after-install /var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/4m9i3y9haqass4osg8404.tpl --after-remove /var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/6zn80qw760sgscggoggww.tpl --description "Test Application" --maintainer "Foo Bar" --version "1.0.0" --package "/Users/travis/build/develar/electron-complete-builder/test/fixtures/test-app-one/dist/TestApp-1.0.0-i386.deb" -C /var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/TestApp-1.0.0-i386.deb .
Error: Command failed: fpm -s dir -t deb --architecture i386 --rpm-os linux --name "TestApp" --force --after-install /var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/4m9i3y9haqass4osg8404.tpl --after-remove …
```
=> Linux deb target: print real error message

cli.js, package.json
Stable node 4 and latest 5 supports `Object.assign`, so, we don't need to use lodash.
=> use node Object.assign instead of lodash.assign

package.json, templates/win/installer.nsi.tpl, test/fixtures/test-app-one/package.json
test(nsis): add app title with spaces
But we don't allow/support to set custom ourFile name in the new API — we use package.json name — cannot have spaces.
Since old API is deprecated, test will be not added to cover this case.
=> fix(nsis): error on win when APP_OUT_FILE has spaces

src/codeSign.ts
The regex takes an extra newline when parsing the .p12 cert common name, in this example:
subject=/C=CY/L=Limassol/O=OrgName/CN=OrgName
issuer=/C=US/O=DigiCert
Common name ends up being: 
OrgName
issuer=
Expected:
OrgName
=> fix: ignore newline when parsing common name in .p12 certificates

package.json, src/linuxPackager.ts
Closes #239
Well, it is not a real fix, because it seems that icns2png is completely broken on Linux (ironically, yes :()
Unlikely that it will be merged in this form.
=> fix: Linux build fails at icon conversion #239

src/util.ts, test/src/BuildTest.ts
Closes #180 
Actually, was fixed as part of another commit, here only test added.
=> fix: Problems downloading electron #180

.idea/runConfigurations/osxPackagerTest.xml, README.md, docs/options.md, package.json, src/build-cli.ts, src/builder.ts, src/metadata.ts, src/packager.ts, test/src/BuildTest.ts, test/src/helpers/packTester.ts, test/src/linuxPackagerTest.ts, test/src/osxPackagerTest.ts, test/tsconfig.json
=> feat: prefix dist: as marker to package in a distributable format

README.md
As discussed in #280, let's use the only badge about npm version.
=> Added badge about npm version. Closes #276

appveyor.yml, docs/Options.md, src/linuxPackager.ts, src/metadata.ts, src/platformPackager.ts, test/src/helpers/packTester.ts, tslint.json
=> fix: deb package description according to spec

docs/Multi Platform Build.md, package.json, src/macPackager.ts, src/winPackager.ts, test/fixtures/test-app-one/package.json, test/fixtures/test-app/package.json, test/src/BuildTest.ts, test/src/helpers/runTests.ts, test/tsconfig.json, tsconfig.json, typings/signcode.d.ts
=> feat: Windows code signing from OS X

README.md, docs/Options.md, docs/Publishing Artifacts.md, src/metadata.ts
Suggestions of other areas to improve are welcome.
=> Clarify Documentation (Part 2)

package.json, src/winPackager.ts, test/fixtures/test-app-one/index.js, typings/signcode.d.ts
Fixed in Squirrel.Windows
Closes #339
=> fix: Windows shortcut doesn't work when `productName` contains a space

src/platformPackager.ts
Jenkins stores the build number in the `BUILD_NUMBER` environment variable
=> add Jenkins build number support

src/linuxPackager.ts
In previous version, "Exec" parameter of .desktop file used only executable name.
This depends on user's $PATH, that might cause the problem when launching the app.
So this commit uses the full path for "Exec" parameter.
=> fix(linux): use full path in .desktop file

docs/Options.md, src/linuxPackager.ts, src/metadata.ts, test/src/helpers/packTester.ts
Debian and Ubuntu have a libnotify-bin package that install the libnotify binary.
=> Use libnotify-bin as depends, not libnotify

docs/Loading App Dependencies Manually.md
#326 Sorry for taking so long to add a doc about it.
=> ddocs: Add docs about how to manually load app deps

src/asarUtil.ts, typings/asar.d.ts
This will allow users to have the ability to include dot folders into their asar file. This should maintain existing default functionality.
=> feat: adding dot asar option

src/util.ts
This addresses #514. Allow to pass absolute path to electron-builder during programmatic usage. Currently this leads to an error with invalid reason/message.
=> fix: allow passing absolute and relative path as userAppDir option

README.md
When you follow the instructions from the existing README, you get this warning on the console when you `npm run dist`:
```
Warning: app-bundle-id is deprecated, please use appId
```
=> Update README to recommend appId. app-bundle-id is deprecated

README.md
Add note to README about `appdmg` and `7zip` packages being optional dependencies.
Ref: https://github.com/electron-userland/electron-builder/issues/95#issuecomment-226819644
=> README note about optional deps

README.md
Include Squirrel Updates Server as an alternative to serve releases.
=> docs: Add Squirrel Updates Server to auto update section

README.md
Add clarification regarding how native addons that are not dependencies but a part of the project should be treated
https://github.com/electron-userland/electron-builder/issues/683
=> docs: clarify native addons build process

src/metadata.ts, src/packager/mac.ts
Adding support for CFBundleTypeRole for MacOS CFBundleURLTypes (protocols).
This key appears as required in Apple's documentation.
https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/TP40009249-102207-TPXREF115
=> feat: support CFBundleTypeRole for MacOS CFBundleURLTypes

.gitignore, docs/Code Signing.md, docs/Options.md
I was just trying to code sign on Windows and spent a moment to find whether it is already supported and how to use it so I allowed myself to update the docs.
=> docs: add missing certificateFile and certificatePassword options description

docs/Options.md, src/metadata.ts, src/packager.ts, src/util/util.ts
This seems to fix #787 
The only place I'm unsure of is (haven't touched yet):
https://github.com/electron-userland/electron-builder/blob/a4eeaded7a7e0da77112a1c96786d80f90e47083/src/install-app-deps.ts#L33
=> Make a setting for --build-from-option flag

src/util/util.ts
Renames the distribution URL used for downloading the v8 headers from `https://atom.io/download/atom-shell` to `https://atom.io/download/electron`.
Both URLs will be supported going forward but the old one may possibly be removed in Electron 2.0.
https://github.com/electron/electron/pull/7881
☝️ This PR is currently pending but the new endpoint is already live in production.
=> update v8 headers URL

docs/Options.md, src/metadata.ts, src/packager.ts, src/util/util.ts
I am building an electron app that uses native dependencies targeting multiple platforms. [Prebuild](https://github.com/mafintosh/prebuild) binaries are available for all of them. 
However when `npmSkipBuildFromSource` is enabled, `prebuild` downloads the binary for the installed node version instead of the electron version. This can be easily handled by specifying a `--abi=ELECTRON_ABI_VERSION` argument, but electron-builder does not allow this.
**This PR adds support for specifying any number of additional `npm rebuild` arguments to allow working around issues outlined above.**
=> feat: add ability to specify additional npm rebuild args

templates/nsis/multiUser.nsh
This should allow NSIS to determine install directory based on system architecture.
Related, https://github.com/electron-userland/electron-builder/pull/872
=> feat(nsis): Specify Windows install directory based on architecture

src/packager.ts
If wine is installed on Fedora 24/25 over the repository, the version string is rather uncommon:
$ wine --version
wine-1.9.23 (Staging)
The version comparison fails with "TypeError: Invalid Version: 1.9.23 (Staging)" if you try to create a windows build. This pull should fix the problem by cutting the version string on the first whitespace.
=> fix: wine version processing

src/winPackager.ts
`FileDescription` is used when right-clicking on a program in the task bar for example:
So I believe we should be displaying `appInfo.productName` there, as `appInfo.description` is more like a one-sentence description of your app, which could be used in an *About* dialog.
Edge, Internet Explorer, etc. use the same value for `ProductName` and `FileDescription`:
=> Use productName for FileDescription on Windows

src/targets/appx.ts, templates/appx/appxmanifest.xml
Use the architecture (ia32 / x64) that's been passed as a parameter instead of process.arch when calling makeappx.exe. Allows for 32-bit builds on 64-bit machines.
=> appx, use arch from parameters instead of process.arch

packages/electron-auto-updater/src/electronHttpExecutor.ts, packages/electron-builder-http/src/httpExecutor.ts, packages/electron-builder/src/util/nodeHttpExecutor.ts
=> fix: add request.pause() to notification about progress

docker/base/Dockerfile
Windows build *without* code signing works fine but when code signing is
enabled `osslsigncode` fails. It's apparently due to libcurl shared
dependency mismatch.
/root/.cache/electron-builder/winCodeSign/winCodeSign-1.6.0/linux/osslsigncode:
error while loading shared libraries: libcurl.so.4: cannot open
shared object file: No such file or directory
Installing libcurl3 fixes the issue.
=> fix(docker): add missing libcurl3 for osslsigncode

packages/electron-auto-updater/src/GenericProvider.ts, packages/electron-auto-updater/src/electronHttpExecutor.ts
Hi -
Love the work you guys are doing here! I've made a couple of quick changes to allow easier local testing for auto-updating, and for non-standard internal environments.
The first is to allow the options to doApiRequest to include the Protocol, and use https: if unspecified. This allows the usage of a local http server for testing. I was surprised to see that RequestOptions includes Protocol with a capital P, but it's what I needed to get this to work. Previously, I was attempting to use a self-signed certificate for a local server, but the request either stalls or fails silently (unsure which), and I don't have access to an SSL server for this internal testing.
The second is that doDownload() was not passing through the port number. This would cause a scenario where the latest version …
=> AutoUpdate: Port support for downloads, Protocol support for generic backend

packages/electron-builder/src/platformPackager.ts, packages/electron-builder/src/targets/fpm.ts
Digging through the code, this is probably not the ideal way to do this but it follows what was done for the 'deb' packaging.
Arch Linux (pacman) does not have packages available for i386 and only builds for i686 architecture or better.
Also added in the dependencies of Electron on Arch and changed the filename from ".pacman" to the correct "pkg.tar.xz".
=> fix: Arch & pacman use i686 instead of i386 and pkg.tar.xz

packages/electron-builder/templates/nsis/boringInstaller.nsh, packages/electron-builder/templates/nsis/uninstaller.nsh
This change will show a welcome and finish page during the uninstall process if using the boring installer.
The welcome page removes the need to have the message box asking if you are sure you want to uninstall.
The finish page makes it more clear that it was successfully uninstalled. It also makes it possible to customise the finish page as seen in the screenshot.
To show the remove user data box you can add an include script that contains something like the following, which closes #885 :
```
!ifdef BUILD_UNINSTALLER
Function un.AddAppData
RMDir /r "$APPDATA\Rocket.Chat+"
FunctionEnd
; Using the read me setting to add option to remove app data
!define MUI_FINISHPAGE_SHOWREADME
!define MUI_FINISHPAGE_SHOWREADME_TEXT "Remove user data"
!define MUI_FINISHPAGE_SHOWREADME_NOTCHECKED
!define …
```
=> Show welcome and finish page duing uninstall for boring uninstall

docs/Auto Update.md
Just a note why electron-updater `download-progress` event is not supported on Mac yet.
=> Update doc for download-progress event support

packages/electron-builder-squirrel-windows/src/squirrelPack.ts
Fixes #1249.
The .exe file in C:\Users\IEUser\AppData\Local\\%myapp% has a digital signature now just like Update.exe.
=> Sign the Squirrel.Windows executableStub

docs/NSIS.md, packages/electron-builder/templates/nsis/installer.nsi
Create a 'preInit' hook in the NSIS installer script that is inserted before
any other code or macros. This allows customs macros to access the initial
state of global variables.
No breaking changes
=> feat(nsins): create pre initialization hook in installer.nsi

packages/electron-builder/src/targets/appImage.ts
I got the following error when trying to build AppImage on my Ubuntu VM. The same error occurred in Travis CI.
```
Error: Exit code: undefined. stderr maxBuffer exceeded
GNU xorriso 1.4.4 : RockRidge filesystem manipulator, libburnia project.
```
Increasing the maxBuffer size fixed the problem.
=> fix: increase maxBuffer for xorriso child process

packages/electron-builder/templates/nsis/uninstaller.nsh
Instead of just nuking installation directory there is an option for the programmer to specify which files should be uninstalled when uninstalling the application. Temporary solution for #1298
=> feat(nsis): Add option to define custom files to be removed

packages/electron-builder/src/publish/PublishManager.ts
I'm pretty sure that value is either `undefined` or empty (`''`) instead of `null` if the env var is not set.
=> Publishing always fails on circleci #1303

packages/electron-builder/src/targets/fpm.ts
I added the default package dependencies for supporting Electron [Tray Menus](https://github.com/electron/electron/blob/master/docs/api/tray.md) and [Notifications](https://github.com/electron/electron/blob/master/docs/tutorial/desktop-environment-integration.md) when building `pacman` and `rpm` Linux targets (currently, this only works for deb packages, which includes `libnotify4`, `libappindicator1` per default).
The required packages **libappindicator** and **libnotify** have different names on these platforms:
- **pacman**
`libappindicator-gtk2`, `libappindicator-gtk3`, `libappindicator-sharp`, `libnotify`
- **rpm**
`libappindicator`, `libnotify`
=> Add dependencies for supporting Electron Tray (libappindicator) & Notifications (libnotify) for more Linux targets

docs/Auto Update.md
1. Add zip target attention note for macOS
2. Add `electron-updater` quick setup code snippet example
See: https://github.com/electron-userland/electron-builder/issues/1367
=> docs(updater): update Auto Update quick setup guide

packages/electron-builder/templates/dmg/dmgProperties.pl
Fix https://github.com/electron-userland/electron-builder/issues/1369
=> fix: fix productName with utf8 characters cause dmg icon position error

packages/electron-updater/src/PrivateGitHubProvider.ts, packages/electron-updater/src/electronHttpExecutor.ts
This is a partial solution for #1370. This fixes private github provider for auto updates on Windows.
However it is know that Mac still does not work, this is due to how squirrel.mac uses feed URL and cannot have its headers controlled on redirect. A solution for this is being investigated.
=> fix(updater): GitHub private repo for windows, partial solution for #1370

packages/electron-builder/templates/nsis/installSection.nsh
I have a user who wants to do an unattended install (workflowproducts/postage#177), but they don't want the desktop shortcut.
This commit adds a command line switch that I tested to work.
=> feat(nsis): add --no-desktop-shortcut argument

packages/electron-builder/src/yarn.ts
This logs the output of the rebuild process to help debug build failures like #1415
=> fix(rebuild): Log stdout and stderr

docs/Kernel extensions.md
This PR for the wiki describes how to install macOS kernel extensions using a script.
=> Installing kernel extensions using scripts

packages/electron-builder/src/targets/snap.ts
Closes #1452
Credit to: @flexiondotorg for the exact fix :smile:
=> Fix appindicator icons with snap build

docs/Auto Update.md
I was sent on a bit of a boondoggle by the sentence "simplified auto-update is not supported for Squirrel.Windows". I misinterpreted this to mean it wasn't supported on Windows at all. Perhaps I'm the only one dumb enough to make this mistake, but I wanted to clarify the sentence for those poor clods as thick headed as I am.
=> Clarify that simple auto-update works on Windows

packages/electron-builder/src/options/winOptions.ts, packages/electron-builder/src/windowsCodeSign.ts
I had the need to add an additional certificate file via the `/ac|-ac` option (similar to [this SO question](http://stackoverflow.com/questions/16571978/signed-using-pfx-file-but-uac-still-prompts-for-unknown-publisher)). This PR adds a new `additionalCertificateFile` option to `WinBuildOptions`.
=> Add support for additional certificate file

packages/electron-builder/src/options/linuxOptions.ts, packages/electron-builder/src/targets/snap.ts
For support unity global menubar integration, it needs to specify which [launcher](https://developer.ubuntu.com/en/blog/2016/07/06/announcing-new-snap-desktop-launchers/)  the app use. 
In our case, we need to specify `desktop-gtk2` in `after` in snapcraft.yaml.
This patch extends SnapBuildOption for specify after parts and necessary packages in building step.
=> Snap for extra after parts and build packages support

docs/Options.md
Was wondering why my production dependencies (`electron-updater` in particular) weren't working. As it turns out, I wasn't including `node_modules` in the build.
This PR includes the docs update for this, but an alternative could be to add `node_modules/**/*` similar to how `package.json` is always included. Happy to close this and open a different PR if you'd prefer that.
=> Add note about node_modules inclusion

packages/electron-builder/src/targets/archive.ts
The tar --transform expression did not work as intended, leading to broken sym-/hardlinks inside the archive. The intention is to match `^\.`, but the escape character is evaluated in JS before the expression is passed to tar. As a result, the first character of all paths is transformed (`^.`).
The expression still works for regular files, as all paths begin with a `.`. However, tar also transforms sym-/hardlink targets. This e.g. means that a `foo -> bar` symlink is transformed to `foo -> appname-1.0.0ar`.
Adding an extra escape character, so that the correct transform expression is used.
=> fix(tar): fix invalid sym-/hardlink targets in archive

packages/electron-builder/src/targets/nsis.ts
This will fix the last issue of #1340 when targets artifact's names are changed.
=> Cloning packager.config to prevent override

packages/electron-builder/src/packager/mac.ts, yarn.lock
This avoids throwing an ENOENT exception, if for any reason the old icon is not found to be deleted during the mac installer creation process.
```
Error: ENOENT: no such file or directory, unlink '/mypath/dist/canary/mac/Electron.app/Contents/Resources/myapp.icns'
at Object.<anonymous> (/mypath/node_modules/electron-builder/src/packager/mac.ts:154:19)
From previous event:
at Object.createApp (/mypath/node_modules/electron-builder/out/packager/mac.js:138:21)
```
=> fix: macOS failing when there is no old icon

packages/electron-builder/src/util/macosVersion.ts
Since 10.12 is a possible Sierra version, clean before doing comparison to avoid "Invalid Version" error from SemVer
=> Clean macOsVersion before gte comparison

packages/electron-builder-util/src/util.ts, packages/electron-publish/src/BintrayPublisher.ts, packages/electron-publish/src/gitHubPublisher.ts
I was building my app on Windows, but it failed with `The header content contains invalid characters`. 
After debugging, I found that the env `GH_TOKEN` on my WIndows was wrong, it ends with `\n` (`xxxxxxxx\n`), not a valid HTTP header value.
So I am adding characters checking before request, making the case clear.
=> feat: throw error when token contains invalid characters

docs/Code Signing.md
According to https://linux.die.net/man/1/base64 there are no input/output options.
```
Synopsis
base64 [OPTION]... [FILE]
Description
Base64 encode or decode FILE, or standard input, to standard output.```
=> Correct base64 command for Linux

packages/electron-builder/src/util/filter.ts
The problem occurs on Windows, when the project files are extracted in local drive root. 
That way, the _src_ argument may become 'Z:\' (drive path), which will lead to filtering out all node modules, because of taking incorrect start index in substring (_it.substring(src.length + 1)_).
=> Added path normalization for file filter

docs/Publishing Artifacts.md, packages/electron-builder-http/src/bintray.ts, packages/electron-builder-http/src/publishOptions.ts, packages/electron-builder/src/publish/PublishManager.ts, packages/electron-publish/src/BintrayPublisher.ts, packages/electron-publish/src/gitHubPublisher.ts, packages/electron-publish/src/publisher.ts, test/src/ArtifactPublisherTest.ts
This options are needed to correctly publish Debian packages to a
Bintray Debian repository.
Fixes: https://github.com/electron-userland/electron-builder/issues/1702
Signed-off-by: Juan Cruz Viotti <jv@jviotti.com>
=> WIP feat(linux): accept distribution and component Bintray options

packages/electron-builder/src/targets/appx.ts
It is very useful to set a custom `identityName` when the name of the
app in package.json contains hyphens (which are not permitted in
`appxmanifest.yml`).
Even if you set a non-hyphenated name as `identityName`,
electron-builder will still use the package.json's `name` property for
the `name` appxmanifest.yml value.
Thus, we attempt to re-use `identityName` for that case as well.
Signed-off-by: Juan Cruz Viotti <jv@jviotti.com>
=> feat(appx): attempt to use identityName for manifest name

packages/electron-builder/src/windowsCodeSign.ts
Hello,
Since we use EV cert for singing Windows binaries, we have to use a USB token for it, so we wrote a custom tool (used via `SIGNTOOL_PATH`), which copies the file to sign into Parallels, which then asks the developer to enter the PIN code, signs, and then copies the signed file back to macOS. Unfortunately, 2 minutes is sometimes not enough to finish the signing, so I'd like to make it customizable. Would this work for you?
Thank you!
=> feat: custom Windows sign tool timeout via SIGNTOOL_TIMEOUT

packages/electron-builder/src/publish/PublishManager.ts
Publishers are currently cached by the publisher provider (e.g.
"bintray") and by the platform name (e.g. "linux"). This means that if
the user has different publish configurations for targets that belong to
the same OS (e.g. deb and rpm), then one will override the other on the
cache.
Fixes: https://github.com/electron-userland/electron-builder/issues/1951
Signed-off-by: Juan Cruz Viotti <jv@jviotti.com>
=> fix(publish): cache publishers based on the target name

docs/Code Signing.md
Fixes: https://github.com/electron-userland/electron-builder/issues/1902
Signed-off-by: Juan Cruz Viotti <jv@jviotti.com>
=> docs(windows): document Windows max variable length limit

packages/electron-builder/templates/linux/AppRun.sh
Not sure if this is the only place where this change should be done.
Also don't know about the last line change.
Related to https://github.com/electron-userland/electron-builder/issues/748
=> Escape .desktop to fix RESOURCE_NAME detection

packages/electron-builder/src/appInfo.ts
This change allows having custom BUILD_NUMBERs even when running in a CI environment, without having to modify packages.json.
For instance, to have BUILD_NUMBER based on UTC timestamp instead of sequential ID, a build script only needs to do the following:
```
BUILD_NUMBER=$(date -u +"%Y%m%d%H%M%S")
```
=> Make BUILD_NUMBER higher priority than CI-defined build numbers

docs/multi-platform-build.md
Making sure that ELECTRON_CACHE and ELECTRON_BUILDER_CACHE are using /root/.cache instead of /home/travis/.cache (which is valid in the travis runner environment, but not on inside electronuserland/builder:wine).
Also fixed in example file on https://github.com/develar/onshape-desktop-shell/pull/50
=> Fixing problem with passing variables to docker

packages/electron-builder/src/appInfo.ts
In VSTS Builds, the build variable containing the build number is `BUILD_BUILDNUMBER`
https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/variables
=> Use BUILD_BUILDNUMBER env var as buildNumber for VSTS CI

docs/README.md, docs/code-signing.md, docs/configuration/mac.md, packages/electron-builder/src/options/macOptions.ts
This should resolve the "help wanted" at the end of #1196 and prevent more issues like #1967 cropping up.
This process could be improved in future by adding a configuration option for the location of the provisioning profile to pass on to electron-osx-codesign, as well as various suggestions for improvements to `electron-osx-codesign` validation.
=> Document mas-dev build target and code signing instructions

docs/auto-update.md
Related to https://github.com/electron-userland/electron-builder/issues/1167#issuecomment-340384415 - I can verify that I am receiving observing these events on MacOS now.
=> Updating docs: `download-progress` works on MacOS

docs/configuration/publish.md
'How do Publish' should be 'How to Publish'
=> Correct typo in section title

packages/electron-publish/src/gitHubPublisher.ts
When publishing from AppVeyor, the upload to GitHub sometimes fails with an `ECONNRESET` error. This is random and, when it happens, it is safe to repeat the request.
=> Repeat upload when it fails with ECONNRESET error

docs/code-signing.md
It's previously implied but people seem to struggle with figuring this out.
=> Mention how to disable code-signing on macos

packages/builder-util-runtime/src/httpExecutor.ts
https://github.com/electron-userland/electron-builder/issues/2374
fix the problem on this issues
according to electron document
[clientRequest](https://electronjs.org/docs/api/client-request#requestfollowredirect)
the event "response" and "redirect" are two separate events. 
So I split them up
=> fix the problem of redirect

packages/electron-updater/src/windowsExecutableCodeSignatureVerifier.ts
Adds the following arguments:
* `-NoProfile`: fixes #2385 (and is best practice)
* `-NonInteractive`: tells PowerShell to die instead of prompt in certain cases (this may also prevent the timeout seen in #2421, but not certain)
* `-Command`: this was implicit, but it's better explicit now that there are additional parameters
See also: https://stackoverflow.com/a/25172234/3905079
=> Add parameters to PowerShell invocation

docs/api/electron-builder.md, docs/configuration/configuration.md, packages/electron-builder-lib/src/configuration.ts, packages/electron-builder-lib/src/packager.ts, packages/electron-builder-lib/src/platformPackager.ts, scripts/jsdoc2md.js, test/out/__snapshots__/BuildTest.js.snap, test/src/BuildTest.ts
Hi
In documentation there is 2 hooks available : afterPack and beforeBuild.
I propose to add another hook : afterSign.
If defined, the callback function is called after code-signing ( but before pack into distributable format).
Regards
Jeremie
=> afterSign hook

docs/configuration/snap.md, packages/electron-builder-lib/src/options/SnapOptions.ts, packages/electron-builder-lib/src/targets/snap.ts, test/out/linux/__snapshots__/snapTest.js.snap
This pull request adds the `desktop` and `desktop-legacy` interfaces to the default interfaces used when building snaps. All snap enabled distros are able to support these interfaces now.
* `desktop`: Can access basic desktop graphical resources, such as fonts and in future will be the interface via which desktop theme integration will be exposed.
* `desktop-legacy`: Can access desktop legacy methods such as a11y and input methods.
Both interfaces are auto-connected and do not increase the size of the snap.
=> Add desktop and desktop-legacy to the default interfaces for snaps

docs/encapsulated manual update via menu.js
```
// class AppUpdater
this.on("error", error => {
this._logger.error(`Error: ${error.stack || error.message}`);
});
```
=> fix(electron-updater): remove error callback param event

packages/builder-util/src/arch.ts, packages/electron-builder-lib/src/targets/AppImageTarget.ts, packages/electron-builder-lib/src/targets/tools.ts
Note, requires arm64 support for binary repo dependancies. 7zip-bin PR has already been sent, but electron-builder-binaries PR (for appimagekit binary) is still to come.
=> feat: arm64 support

packages/electron-updater/src/windowsExecutableCodeSignatureVerifier.ts
On Windows 7 we are currently seeing a 30 second delay between the 100% `download-progress` event and `update-downloaded` event. We are not seeing the delay on Windows 10. Investigation reveals that the 30 seconds are spent during the `verifySignature` phase when calling powershell.exe. The process appears to be stuck waiting for input after invoking the command.
Adding `-InputFormat None` fixes the issue on Windows 7 (Powershell v2). Also tested that Windows 10 (Powershell v5) still works. The fix was found on https://serverfault.com/a/639007.
=> Avoid delay due to powershell.exe waiting for input

packages/electron-builder-lib/src/util/packageDependencies.ts, test/out/__snapshots__/PublishManagerTest.js.snap
Linked bug: #2685 
Some projects, like Mozilla Aframe, set a 'link' property at the root of their package.json file.
This causes problems for our packageDependencies job, which extends that object and adds 'link'
to signify the dependency dir is a symbolic link.
This PR makes sure any existing `link` in package.json is always overwritten with the appropriate value.
=> Fix: handle dependencies with package 'link' fields

packages/electron-builder-lib/templates/nsis/multiUser.nsh
Made the `setInstallModePerUser` macro look like in this [SO answer](https://stackoverflow.com/a/47164192) and it fixed the issue with win7:32 crash.
fixes #2518
=> fix: Windows 7 32 bit crash

docker/wine-chrome/Dockerfile
chromedriver couldn't start because `libgconf-2-4` was missing.
So Spectron also couldn't start Electron apps for testing.
```
/project/node_modules/electron-chromedriver/bin/chromedriver: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
```
=> fix(docker): add missing libgconf-2-4 for chromedriver

packages/electron-updater/src/NsisUpdater.ts
Right now package file doesn't escape spaces in the filename, which causes a bug where the package file passed to the nsis installer to be incorrect. This means that when the installer runs, it will fail on folders such as 
`C:\Users\first last\appdata\roaming\package-version.7z`
This issue only seems to occur upon a failed Differential update (due to perMachine) followed by a full download to the users' appdata folder.
This fixes it by forcing the whole file path to be a single arg. I believe this also fixes the following issue
#2640 
I'm unsure if #2363 is the same issue, but I see similar symptoms
=> Allow --package-file arg to escape spaces in filenames

packages/electron-builder-lib/src/targets/snap.ts, test/out/linux/__snapshots__/snapTest.js.snap, test/src/linux/snapTest.ts
In order to improve the startup time for snapped applications we can generate the mime DB and the icon caches at snap build time. In order to do this, we can use snap composition to override the desktop-gtk{2,3} part, adding an install script which does this.
The remote part can't do this by default since it could break legacy applications providing such files but this won't be the case for electron apps.
At the same time, fonts can be removed if a desktop plug is required since `/usr/share/fonts` will be bind-mounted from system.
=> Snap: initialize db and icons for faster startup and remove fonts

docs/auto-update.md
Adds a note about `dev-app-update.yml` file that is required for working against user triggered update flow without packaging.
=> Updater: note about dev-app-update.yml

docs/SUMMARY.md, docs/auto-update.md, docs/tutorials/release-using-channels.md
=> Doc - Release using channels

packages/electron-updater/src/GitHubProvider.ts, test/out/updater/__snapshots__/nsisUpdaterTest.js.snap
~Refactors GitHubProvider.ts to fetch release information solely from the~
~GitHub API rather than the atom xml feed, as the atom xml feed doesn't~
~indicate whether or not a release is marked as prerelease, and because~
~the API was being used whenever allowPrerelease was false (likely the~
~vast majority of requests).~
Makes it so that when the most recently published release is a
prerelease build, the GitHubProvider supplies the correct releaseName
and releaseNotes. Prior to this change, releaseName and releaseNotes
were always set to the name and notes from the latest published build,
even if it was prerelease, and even if allowPrerelease was false.
fixes #2742
=> fix(electron-updater): return correct release notes & name

packages/electron-builder-lib/src/electron/electronMac.ts
Currently the helper apps do not receive version numbers.  This complicates investigation of
crashes in the renderer process, as the version shown in the crash dump is "0".  This patch passes
the version number of the main app to the helper apps as well.
Fixes #2772
=> fix(mac): apply app version to helper apps

test/src/helpers/setVersions.ts
Fixes https://github.com/electron-userland/electron-builder/issues/2789
You cannot build locally on Windows without this.
=> fix: Spawn yarn.cmd on windows

packages/electron-updater/README.md, packages/electron-updater/src/AppUpdater.ts
I had an issue where my latest-mac.json was pointing to the wrong server (I had changed the AWS S3 location). In the logs on Mac it just gave this 'semver' error but in reality the app couldn't be downloaded at all. I'm not familiar with how to debug the internals of this project but I wanted to at least improve the error message to help future folks.
I also made some minor updates to the english on the corresponding Readme file
=> Expand on Autoupdate error message, minor changes to wording

packages/electron-builder-lib/templates/nsis/multiUser.nsh
The default /D parameter behavior (change installation path for silent install/software distribution) was not present in the NSIS installer. Default NSIS behavior translates /D path into an initial $INSTDIR value. 
The NSIS restriction that /D has to be the last parameter still exists, however due to use of StdUtils.GetParameter quotes are now supported.
Issue: #1551
=> fix: nsis installer /D installation path override

packages/electron-builder-lib/src/ProtonFramework.ts
babel isn't strictly required for proton-native. More importantly, this allows libui-node to use the existing infrastructure for proton-native.
Fixes #2903
Fixes https://github.com/parro-it/libui-node/issues/108
=> Proton: use babel only when installed

packages/electron-builder-lib/templates/nsis/installSection.nsh
=> fix(nsis): Installer not closed when 'runAfterFinish: false'

packages/electron-builder-lib/src/util/NodeModuleCopyHelper.ts
Hi, When building our production I got this error in Windows. (We used an npm-scope package) And I fixed it.
```shell
Error: File "" not under the source directory "C:\Users\Administrator\Desktop\splayerx\node_modules"
at getDestinationPath (C:\Users\Administrator\Desktop\splayerx\node_modules\electron-builder-lib\src\util\appFileCopier.ts:26:15)
at C:\Users\Administrator\Desktop\splayerx\node_modules\electron-builder-lib\src\asar\unpackDetector.ts:71:79
at Generator.next (<anonymous>)
From previous event:
at detectUnpackedDirs (C:\Users\Administrator\Desktop\splayerx\node_modules\electron-builder-lib\out\asar\unpackDetector.js:195:17)
at C:\Users\Administrator\Desktop\splayerx\node_modules\electron-builder-lib\src\asar\asarUtil.ts:47:13
at Generator.next (<anonymous>)
From previous …
```
=> Fix the npm-scope package cause building error in Windows

packages/electron-builder-lib/src/winPackager.ts
Currently windows packager only signs `.exe` files. This PR enables code signing for `.dll`s too.
=> Code sign .dlls on Windows

docs/multi-platform-build.md
... since node@9 goes EOL.
In addition: The description of `builder:wine` seems to be wrong, since `wine` is based on `latest` instead of `10`.
=> Update docs to node@10

packages/electron-builder-lib/src/targets/nsis/nsisUtil.ts
Info: https://github.com/electron-userland/electron-builder/issues/3054
space at the end of the path was creating problem while copying a file from src to the destination.
=> fix Issue 3054: ELECTRON_BUILDER_NSIS_DIR setting

packages/electron-updater/src/NsisUpdater.ts
This need this if artifact name also contains the version number.
`electron-updater`
=> [NSIS] Replace all occurrences of version in old blockmap file url

packages/app-builder-lib/src/util/yarn.ts
There is inconsistency in what `yarn` reports via `process.env.npm_execpath` when running `yarn` from `package.json` script in a __workspace configuration__ and when running directly from shell.
```bash
$ yarn run whoami
/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js # CULPRIT
```
You can reproduce this with the following `package.json`:
```json
{
"scripts": {
"whoami": "yarn run env | grep npm_execpath"
}
}
```
```bash
$ yarn run env | grep npm_execpath
"npm_execpath": "/usr/local/Cellar/yarn/1.7.0/libexec/bin/yarn.js" # THAT WORKS
```
The former path fails all existing checks in `electron-builder`, and tricks it into thinking that the script is being executed by `npm`. 
This assumption causes crash in my case due to unavailable `rebuild` command that `electron-builder install-app-deps` …
=> Add user agent check for yarn

packages/app-builder-lib/templates/nsis/portable.nsi
* **Version**: 20.19.2
* **Target**: windows (portable)
When executing a portable build, the exit code would always be 0, even when `process.exit(1)` was used, or an unhandled exception was raised. This is not the case if using an installed version. 
The cause was NSIS not relaying the exit code returned by the child application.
=> fix(win): Relay exit code in portable app

packages/electron-updater/src/AppUpdater.ts
Improve wording of notification that is displayed when a new version of the application has been download and is ready to be installed.
=> Fix grammar in notification message

packages/app-builder-lib/templates/nsis/include/installer.nsh
First update gives error due to __installer.exe missing. 
This is due to it failing to copy over on first install because of no appdata folder yet.
=> fix(nsis): create appdata directory before copying installer

packages/app-builder-lib/src/util/config.ts
Depends on https://github.com/electron-userland/electron-webpack/pull/221
Electron webpack does not respect the dist directory specified in `directories.output` so this PR allows the config to be passed through correctly.
=>  Electron builder yaml is now discovered through JS file

icons.md
Be explicit about the `buildResources` directory instead of referring to its default value ("build").
=> icons.md: Refer to buildResources

packages/electron-updater/src/AppUpdater.ts
It makes the promise returned by checkForUpdatesAndNotify() call **actually** catchable.
Without this change possible checkForUpdatesAndNotify() promise rejection becomes `unhandled rejection` and so only global `process.on('unhandledRejection', ...` handler is able to catch the error which is not an acceptable solution.
The simplest way to reproduce the unhandled rejection caused by checkForUpdatesAndNotify() call is to turn off the network and call the checkForUpdatesAndNotify() method. Event if you setup `.catch` handler for this call you will still get unhandled rejection with Error: net::ERR_INTERNET_DISCONNECTED error.
=> make "checkForUpdatesAndNotify()" promise actually catchable

packages/app-builder-lib/templates/nsis/include/allowOnlyOneInstallerInstance.nsh
Fixes #3484.
`ExecWait` briefly creates a command prompt, possibly causing a visual disruption during updates. [ns:Exec](https://nsis.sourceforge.io/Docs/nsExec/nsExec.txt) is a silent alterntive.
=> fix(nsis): make killing the running app silent

test/out/__snapshots__/BuildTest.js.snap
This should get the unit tests green again.
=> tests: update size in snapshot

docker/wine-mono/Dockerfile
Without tzdata Update-Mono.exe throws the exception: `System.IO.FileNotFoundException: Could not find file "/etc/localtime"` ([#3143](https://github.com/electron-userland/electron-builder/issues/3143), [#232](https://github.com/electron/windows-installer/issues/232))
=> fix(docker): Squirrel.Windows requires tzdata package

packages/app-builder-lib/src/targets/LinuxTargetHelper.ts
Since configuration document was moved to separate page, the URL was no longer correct.
=> Update URL to linux configuration documentation

packages/app-builder-lib/templates/nsis/include/allowOnlyOneInstallerInstance.nsh
This feature adds the possiblity to replace the check for running applications to be customised.
Newly introduced custom macro: `customCheckAppRunning`
=> Enable custom check if app is running.

configuration/configuration.md, includes/hooks.md
* Fixes a typo in the docs. The wrong tense was used in the documentation.
=> Fix a verb tense typo

packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/options/AppXOptions.ts, packages/app-builder-lib/src/targets/AppxTarget.ts, test/out/__snapshots__/BuildTest.js.snap
Adds option to show the app name on the tile images on the start menu. This will display the name on medium (Square150x150Logo) and wide (Wide310x150Logo) tiles.
Verified to be working on a dev build along with an app store submission.
=> feat(appx): Add AppX option to show app name on tiles

packages/app-builder-lib/src/appInfo.ts, packages/app-builder-lib/src/configuration.ts
uses the CI_PIPELINE_IID (no typo, this is the project scoped id of the
currently running pipeline)
=> add support for gitlab ci pipeline ids as buildNumber

packages/app-builder-lib/src/macPackager.ts
As per #3504, afterSign was called before the sign function was called on mac. I tracked this down to a logic error where signApp wasn't implemented for macPackager and thus immediately resolved. Mac then called the sign function directly, leading to the incorrect behaviour.
I was able to successfully build with this, and have the afterSign function called at the right time, with the changes below. I'm however not familiar with typescript (or electron-builders code standards) so likely I'll need to make some changes. This can serve as a first setup.
=> fix: implement signApp function for macPackager

packages/builder-util-runtime/src/httpExecutor.ts
When print error when request return 404,  the description is incomplete,  this maybe confuse users.
=> fix(builder-util-runtime): fix description when request 404

packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/codeSign/windowsCodeSign.ts, packages/app-builder-lib/src/options/winOptions.ts
Switches default timestamp server from `http://timestamp.verisign.com/scripts/timstamp.dll` to `http://timestamp.digicert.com`. After asking DigiCert support if the VeriSign server was down because I was having issues at the time, I was told that it will be deprecated soon. They (and their [docs](https://www.digicert.com/code-signing/signcode-signtool-command-line.htm)) recommend using the new DigiCert server.
=> fix(app-builder-lib): use DigiCert timestamp server as default

packages/app-builder-lib/scheme.json
This solves a build issue with the 'sign' dmg configuration mentioned in #3870
=> Adding ‘sign’ dmg option to scheme.json to fix build errors

packages/app-builder-lib/scheme.json
It should be allowed to include $schema property in JSON file.
Issue: #3962
=> fix: allow $schema property in electron-builder.json

packages/app-builder-lib/scheme.json
When configuring the coordinates of icons in a DMG, I had a hard time figuring out how the X and Y values actually related to the output I was seeing. I had to do quite a bit of searching to find [this documentation](https://metacpan.org/pod/distribution/Mac-Finder-DSStore/DSStoreFormat.pod) (emphasis mine):
> `'Iloc'`
>
> 16-byte blob, attached to files and directories. The file's icon location. Two 4-byte values **representing the horizontal and vertical positions of the icon's center (not top-left)**. (Then, 6 bytes 0xff and 2 bytes 0?) For the purposes of the center, the **icon only is taken into account, not any label**. The icon's size comes from the icvo blob.
In this PR, I've distilled the information and added it to the DMG configuration schema that drives the relevant …
=> Improve DMG icon coordinates documentation

packages/app-builder-lib/templates/linux/after-install.tpl, packages/app-builder-lib/templates/linux/after-remove.tpl
Debian packages should place binaries in /usr/bin rather than /usr/local/bin see [this](https://www.debian.org/doc/manuals/maint-guide/modify.en.html#destdir) for details
=> corrected path for binary in package

packages/app-builder-lib/src/targets/LinuxTargetHelper.ts
The following error occurs when I try to install a .deb file.
> ```none
> Processing triggers for shared-mime-info (1.9-2) ...
> /usr/share/mime/packages/my-app.xml:9: parser error : Extra content at the end of the document
> </mime-info>
> ^
> Failed to parse '/usr/share/mime/packages/my-app.xml'
> ```
When I look into the generated xml file for the mime type there are multiple </mime-info> closing tags. This PR fixes that issue.
=> Fix bug that generates additional </mime-info> closing tag in mime type xml file

packages/app-builder-lib/src/targets/nsis/NsisTarget.ts, packages/app-builder-lib/templates/nsis/multiUser.nsh
1) In windows Registry entry for uninstaller is located at this path 
`Software\Microsoft\Windows\CurrentVersion\Uninstall\` with just the guid as Example: `\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\ddd366r9-367b-5d51-b552-9754365` but the convention to store the key with id in registry is `\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\\{ddd366r9-367b-5d51-b552-9754365}`.
=> Fix-[#4068]:NSIS Uninstaller registry entry format change

packages/app-builder-lib/src/electron/electronMac.ts
add needed helpers (Renderer, Plugin, GPU) to fix the crash of electron 6.0.0 app at start up
=> fix electron mac : add needed helpers for electron 6.0.0

packages/dmg-builder/src/dmg.ts
Upon signing and notarization electron-builder is expanding application more than allocated size in method `computeAssetSize` which is located under: 
```
packages/dmg-builder/src/dmg.ts
```
This fix is adding 10% of additional size on temporary dmg. This fix closes #3301 among other tasks which 'no space left on device'.
=> Adding 10% on size for temporary dmg used in hdiutil 

packages/electron-updater/src/AppUpdater.ts
https://github.com/electron-userland/electron-builder/issues/4213
Change to take an update to an older version when `AllowDowngrade` is true, and the latest version is less than the currently installed version.
=> When AllowDowngrade is true and latest version is older, take the update

packages/builder-util/src/util.ts
Fixes #4176
"Integration" tokens, at least those created for GitHub Actions, are formatted as `v1.<40-char token>`, which doesn't pass this regex test and causes the publish to fail.
=> fix(electron-publish): Allow GH integration tokens

packages/app-builder-lib/src/targets/AppxTarget.ts, packages/app-builder-lib/src/targets/MsiTarget.ts, packages/app-builder-lib/src/targets/nsis/NsisTarget.ts, packages/app-builder-lib/src/targets/nsis/nsisUtil.ts, packages/app-builder-lib/templates/nsis/common.nsh, packages/app-builder-lib/templates/nsis/include/extractAppPackage.nsh, packages/app-builder-lib/templates/nsis/include/installer.nsh, packages/app-builder-lib/templates/nsis/include/webPackage.nsh, packages/app-builder-lib/templates/nsis/portable.nsi, test/src/helpers/testConfig.ts, test/src/windows/webInstallerTest.ts
Checklist:
**_Done_, pending merge [electron-userland/electron-builder-binaries#27](https://github.com/electron-userland/electron-builder-binaries/pull/27)**
=> fix(nsis): Windows on ARM support

packages/app-builder-lib/templates/linux/after-install.tpl
Add SUID bit to packaged `chrome-sandbox` so that it works out of the box on
distros like Debian.
Part of https://github.com/electron-userland/electron-builder/issues/3872
=> fix(deb): chmod SUID bit on chrome-sandbox for debs

packages/app-builder-lib/src/util/yarn.ts
I use yarn with enabled [plug’n’play](https://yarnpkg.com/en/docs/pnp) option, it means that *node_modules* directory doesn't exist instead used *.php.js* file.
https://github.com/electron-userland/electron-builder/blob/ebbd9f796e2d8d5b0720b2b699ba24dc159ee692/packages/app-builder-lib/src/util/yarn.ts#L16-L18
File contains a path resolver and mapping to dependencies paths (include devDependencies). When electron-builder calls **installDependencies** then *.php.js* file will be overwritten (without devDependencies) that break process because builder needs in devDependencies on runtime.
https://github.com/electron-userland/electron-builder/blob/ebbd9f796e2d8d5b0720b2b699ba24dc159ee692/packages/app-builder-lib/src/util/yarn.ts#L75
=> fix(app-builder-lib): yarn install break on 'electron-builder install-app-deps' when used pnp

packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/options/SnapOptions.ts, packages/app-builder-lib/src/targets/snap.ts, test/out/linux/__snapshots__/snapTest.js.snap, test/src/linux/snapTest.ts
Add support for `autostart` snap option. This allows snaps to define that they should be launched upon login.
See https://snapcraft.io/docs/snap-format:
>      # Name of the desktop file placed by the application in 
>      # $SNAP_USER_DATA/.config/autostart to indicate that application 
>      # should be started with the user's desktop session. The application
>      # is started using the app's command wrapper (<name>.<app>) plus
>      # any arguments  present in the Exec=.. line inside the autostart
>      # desktop file.
>      # (snapd 2.32.4+)
>      autostart: <command line>
Basically, this just needs to set the value of `autostart` to the name of the `.desktop` file that is created in `$SNAP_USER_DATA/.config/autostart`. E.g. an "myapp" with …
=> Add support for snap autostart option

packages/app-builder-lib/electron-osx-sign/util-provisioning-profiles.js
When building multiple targets on macOS, `getProvisioningProfileAsync` (in electron-osx-sign) would create a temporary plist file that was shared between targets. However this method also unlinked the file it created causing the other target, which was running in parallel and still needed the file to crash. 
This fix makes the temporary file name unique for each call to `getProvisioningProfileAsync` by introducing a [high-resolution timer](https://nodejs.org/api/process.html#process_process_hrtime_bigint) as a component of the temporary file name hash, so when the method unlinks the file, it doesn't cause other targets building in parallel to fail as they will have their own copy of the file.
fixes #4204
=> fix(mac): make tempFile unique for each call to getProvisioningProfileAsync 

packages/app-builder-lib/src/macPackager.ts
I noticed that running the packager on a basic vanilla repo was yielding two signing operations for mas/mas-dev targets:
```
mkdir test && cd test
yarn init
yarn add --dev electron electron-builder
echo "console.log('hello world')" > index.js
yarn electron-builder -m mas
• electron-builder  version=21.2.0 os=18.7.0
• description is missed in the package.json  appPackageFile=/Users/onaips/test/package.json
• author is missed in the package.json  appPackageFile=/Users/onaips/test/package.json
• writing effective config  file=dist/builder-effective-config.yaml
• packaging       platform=mas arch=x64 electron=6.0.12 appOutDir=dist/mas
• default Electron icon is used  reason=application icon is not set
• signing         file=dist/mas/test.app identityName=Developer ID Application: -redacted- …
```
=> Remove redundant signing op for mas and mas-dev targets

packages/app-builder-lib/src/targets/AppxTarget.ts
I tested this change using the following `package.json` ElectronBuilder `build` config:
```
"fileAssociations": [
{
"ext": "ext1",
"role": "Viewer",
"mimeType": "application/ext1+zip"
},
{
"ext": "ext2",
"role": "Viewer",
"mimeType": "application/ext2+zip"
}
],
```
I am running a Windows 10 Pro Virtual Machine (VirtualBox), in "developer mode" so I can install my test `AppX` which is code-signed (via `electron-builder`'s own `certificateFile` config) using a self-signed PFX certificate (generated using `electron-builder create-self-signed-cert -p NAME`) which I added in my "Trusted Root Certification Authorities" (using `mmc.exe` and a "Certificates" snap-in).
Once my test `AppX` is installed (simply by double-clicking on it from the Windows file explorer), I am able to double-click or …
=> Added missing support for AppX fileAssociations

CONTRIBUTING.md
Trying to build docs, missing a python dep (added to contrib readme) and additional info for getting the docs built.
Should we just move the mkdocs.yml from master branch to docs?
=> docs(contrib): Add mention of missing mkdocs dep

auto-update.md
With example of request headers
Add example code
Docs related to #4250 
Once this gets merged, would be great to get a new release as [the current release](https://www.npmjs.com/package/electron-updater) doesn't yet have the exposed classes this refers to in order to add custom request headers.
=>  docs(auto-update): Add docs for custom config

packages/electron-builder-squirrel-windows/src/SquirrelWindowsTarget.ts, packages/electron-builder-squirrel-windows/src/squirrelPack.ts
A Description in package.json is required if you want to successfully build a windows installer with squirrel.
I've added simple checks for that to alert the developer the error, instead of a 30 line mono error.
=> Fixed Squirrel Windows Description Error

packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/options/linuxOptions.ts, packages/app-builder-lib/src/targets/LinuxTargetHelper.ts
Would like to set executableArgs with executableName in builder config. So it will generate desktop.Exec with args.
For example:
```yml
linux:
target:
- deb
category: Telephony
executableName: my-app-name
executableArgs:
- --no-sandbox
```
And will generate desktop file:
```
[Desktop Entry]
Name=My Name
Exec="/opt/My Name/my-app-name" --no-sandbox %U
Terminal=false
```
Can be used to fix https://github.com/electron-userland/electron-builder/issues/3872 https://github.com/electron/electron/issues/17972
=> feat(app-builder-lib): support to set executableArgs in linux config

packages/builder-util/src/util.ts
As mentioned [here](https://circleci.com/docs/2.0/env-vars/?gclid=Cj0KCQiAq97uBRCwARIsADTziyYsyJYon6xicbXgtFgEEIaqhWwaw9Rub_IRdQsH9yuDtE3jdnfAJ68aAlLeEALw_wcB#built-in-environment-variables), `CI_PULL_REQUEST` and `CI_PULL_REQUESTS` are deprecated, and `CIRCLE_PULL_REQUEST` and `CIRCLE_PULL_REQUESTS` should be used instead.
If there's multiple PRs, `CIRCLE_PULL_REQUEST` will have one url at random, so checking that should be sufficient for CircleCI
In general, it might be worth looking into this, to support other CI tools as well: https://github.com/watson/ci-info#ciispr
=> Update deprecated env var for CircleCI

packages/dmg-builder/src/dmgLicense.ts
Fixes a bug where licenses containing characters that are outside the standard ASCII 7-bit character set would not contain the correct content when added to macOS DMGs. The RTF escape sequence used to encode these characters was missing the "placeholder" character that should be present after the code point data. This commit adds a ? (question mark) character as the placeholder.
See https://www.zopatista.com/python/2012/06/06/rtf-and-unicode/#so-does-rtf-handle-unicode
=> fix: correctly encode Unicode characters in DMG licenses

configuration/publish.md
Thanks for sharing your great builder with us! I found one documentation issue, and going to report a fix for it.
Now the command name is not `build` but `electron-builder`, then the command in `"scripts"` should be updated.
refs #4076
=> Use the latest command name in the documentation

packages/app-builder-lib/src/codeSign/windowsCodeSign.ts
The current default time server is timestamp.comodoca.com/rfc3161 and they have the following policy:
> Note: If you are signing several pieces of software with a script, please add a delay of 15 seconds or more between signings so that you're not hammering our servers.
The problem is that electron-builder currently has a retry delay of 2 seconds, which means further calls will fail. This fix simply increases the delay to 15 seconds, which should solve the problem.
=> Fixes #2795: Prevent script from hammering time server

packages/app-builder-lib/templates/nsis/messages.yml
This is a i18n issue. I just fixed.  "OK" in ZH_CN should be "确定"
Before:
=> fix(nsis) fix nsis CHECK_APP_RUNNING zh_CN text

packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/options/pkgOptions.ts, packages/app-builder-lib/src/targets/pkg.ts
Add mustClsoe key in pkg
Identifies applications that must be closed before the package is installed.
must-close: https://developer.apple.com/library/archive/documentation/DeveloperTools/Reference/DistributionDefinitionRef/Chapters/Distribution_XML_Ref.html#//apple_ref/doc/uid/TP40005370-CH100-SW77
issues: https://github.com/electron-userland/electron-builder/issues/4380
=> feat(app-builder-lib): the pkg interface adds the must-close attribute (#4380)

packages/app-builder-lib/templates/entitlements.mac.plist
This reverts commit e48681eeee6a48cf68deb6a0a0f1c5c13507d870 which regressed macOS apps (#4390).
@develar @vaibhavtel
=> Revert "fix(appx): App sandbox not enabled (ITMS-90296) (#4244)" (#4390)

packages/app-builder-lib/src/targets/nsis/NsisTarget.ts, packages/app-builder-lib/templates/nsis/multiUser.nsh
It looks like the change of the registry format has not been well thought through and it causes lots of issues (#4092 and #4126).
The change was made for pure pedantic reasons and didn't consider backwards compatibility with older installer. In our case, we are wrapping the NSIS package with an MSI wrapper that has a bit more functionality than the one provided by electron-builder which no longer works after this change.
My suggestion is to revert the commit all together and leave the registries as they were before.
This reverts commit 7518aee8e1abe0516071b350748e84dc47e35cf7.
=> Revert "fix(nsis): NSIS Uninstaller registry entry format change (#4069)"

packages/builder-util/src/util.ts
When nsis script error, spawnAndWrite reject(error.stack || error.toString()) will cause a bad error message "[object Object]" because error log handle in  expect a error object.
I just fix it.
=> fix(nsis): fix spawnAndWrite reject in util

packages/electron-builder/src/builder.ts
Currently, when I config in cli like -c.nsis.createDesktopShortcut=true will not work, because it will parsed to String instead of Boolean. 
I just fixed by using coerceTypes.
=> fix(nsis): fix cli config error when use Boolean value in -c.nsis config

packages/builder-util-runtime/src/httpExecutor.ts
electron-updater: 4.2.0
electron-builder: 22.2.0
When private github repos:
1. `NsidUpdater` calls `differentialDownloadInstaller` with `token` header
2. This calls `downloadBlockMap`, which then goes to `httpExecutor`
3. Redirects to aws, and `httpExecutor.ts:297` deletes the github token
4. header object never got shallow copied, so `NsidUpdater` higher level argument `downloadOptions` looses its token
5. the fallback passes unauthenticated headers to `httpExecutor`, which now ends up failing trying to fetch metadata from the private repo
Seems like the fix is not mutate. Related to #4544 and #4564
=> fix: nsis update fails for private github repos

packages/builder-util-runtime/src/httpExecutor.ts
Fix a bug where network error thrown when invoking `updater.downloadUpdate()` is not catchable.
Related issue: https://github.com/electron-userland/electron-builder/issues/2451
Network error such as `net::ERR_NETWORK_CHANGED`, etc could happen when a `response` stream is in progress. We do not seem to handle any cases related to this, which resulted in the error being thrown globally and the original `updater.downloadUpdate()` not resolving.
```ts
// assumes that we have a new version ready to be downloaded
// on a cold cache
try {
await autoUpdater.downloadUpdate() // When the download is in progress, disconnect
// from the internet, this will not reject
// and never settles. Additionally, a `net::ERR_...` 
// depending on the network error will be thrown
// and not caught causing an …
```
=> fix:(electron-updater) not rejecting with error when response stream gets an error

packages/app-builder-lib/src/macPackager.ts
`hardenedRuntime` causes:
- `mas-dev` build to crash with `EXC_BAD_ACCESS (Code Signature Invalid) `. Fixes: https://github.com/electron-userland/electron-builder/issues/4074.
- `mas` build to show a blank white window (screenshot taken by Mac App Store Review Team):
`hardenedRuntime` can be explicitly set to `true` if needed for `mas` build in `masOptions`.
=> fix(mas): set hardenedRuntime to false by default for mas and mas-dev

packages/app-builder-lib/src/targets/pkg.ts
When specifying the `background` option for the `pkg` target, it only appears when the installer is launched in light mode.
This patch adds the `background-darkAqua` line to the generated distribution XML file so that the background image also works in dark mode.
=> Add support for PKG background images in dark mode

packages/dmg-builder/src/dmg.ts
Prevent the internet-verb from being used with hdiutil on macOS 10.15
"Catalina" or newer, since it was removed
Fixes #4405
=> fix(mac): remove internet-enable from macOS 10.15 (#4405)

packages/app-builder-lib/src/targets/pkg.ts
When building PKG's,  "identifier" is missing from parameter list.
See Issue #4527
=> fix(mac): identifier missing from pkgbuild

packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/configuration.ts, packages/app-builder-lib/src/packager.ts, packages/app-builder-lib/src/targets/AppxTarget.ts
This PR adds a new hook, appxManifestCreated(path: string), that allows modifying the appx manifest before it is packed into the .appx installer.
=> feat(appx): add support for modifying .appx manifest

docker/wine/Dockerfile
I got the following error while building the docker image (what I have to because the public image never gets updated -> please fix that, there are several issues complaining about that) and fixed it with the recommended solution.
https://askubuntu.com/questions/1205550/cant-install-wine-on-ubuntu-actually-lubuntu-18-04
=> fix(docker): fix install of wine

packages/app-builder-lib/templates/nsis/include/webPackage.nsh
This fixes #4402. More specifically error `
!insertmacro: macro "_If" requires 4 parameter(s), passed 6!
` during build of nsis-web target
=> Fix NSIS web build

packages/app-builder-lib/src/codeSign/windowsCodeSign.ts
Resolves #4631 by transforming both `Thumbprint` and  `certificateSha1` to uppercase before comparing them.
=> fix(app-builder-lib): Allow using lowercase value for certificateSha1

packages/app-builder-lib/src/targets/AppxTarget.ts, packages/app-builder-lib/templates/appx/appxmanifest.xml
Microsoft requires the `minVersion` and `maxVersionTested` values for ARM64 builds of APPX to be at least build 10.0.16299.0 (or newer). Updated the manifest builder to apply the appropriate build values depending on the arch.
So for ARM64 builds, the `minVersion` and `maxVersionTested` values will be `10.0.16299.0` and `10.0.14316.0` for everything else.
=> Add ARM64 support for APPX

packages/builder-util-runtime/src/httpExecutor.ts
"Socket" event is not fired if Electron "net" version of request is used. It lead to issue that request will never be timed out if something went wrong. I didn't find how to set timeout request in Electron net module. I'm open to proposals of more clear approach.
This PR fixes issue https://github.com/electron-userland/electron-builder/issues/4618
=> fix(builder-util-runtime): set timeout when request is closed

packages/app-builder-lib/templates/nsis/assistedMessages.yml
Why "game" is default word for russian? I think "Приложение" (the Application) is much better and more adaptive for most case of usages electron-builder
=> change Russian locale from "game" to "application"

packages/app-builder-lib/src/codeSign/windowsCodeSign.ts
- The win custom sign script should be able to use `WinPackage` as `doSign` does.
- Export `doSign` method to allow users to wrap it in their script instead of rewrite whole code signing logic. For example, to just skip some files to sign.
=> feat: win custom sign should have same signature of doSign

.github/issue_template.md
Adding the electron version might give us a better troubleshooting, since some errors people might encounter can be electron-related and updater/builder only needs a simple change to make that work.
=> Add electron version on issue template

auto-update.md
The typing of `AppUpdater:downloadUpdate` is inaccurate here.
Rather than typing it as `Promise<any>` this should be `Promise<Array<string>>` according to the code: https://github.com/kevinlinv/electron-builder/blob/f2c374974be358b96c896dba417406b4f8106ad2/packages/electron-updater/src/AppUpdater.ts#L588
This PR is the other pair of the actual code change in https://github.com/electron-userland/electron-builder/pull/4786.
=> docs(electron-updater): Update docs for downloadUpdate resolved type

packages/electron-updater/src/electronHttpExecutor.ts
See 
https://github.com/electron-userland/electron-builder/issues/4454
and 
https://github.com/electron-userland/electron-builder/issues/4758
=> fix(electron-updater): Make updater work again when using aws s3 private buckets

packages/app-builder-lib/src/targets/AppxTarget.ts
Fixes an error when generating appx for Windows 10 arm64 due to referencing a non-existent winCodeSign path. When building for arm64, the x64 version of winCodeSign is used.
```
⨯ Exit code: ENOENT. spawn C:\Users\shibayan\AppData\Local\electron-builder\Cache\winCodeSign\winCodeSign-2.6.0\windows-10\arm64\makeappx.exe ENOENT  stackTrace=
Error: Exit code: ENOENT. spawn C:\Users\shibayan\AppData\Local\electron-builder\Cache\winCodeSign\winCodeSign-2.6.0\windows-10\arm64\makeappx.exe ENOENT
at C:\Users\shibayan\Documents\electron-quick-start\node_modules\builder-util\src\util.ts:125:16
at exithandler (child_process.js:310:5)
at ChildProcess.errorhandler (child_process.js:322:5)
at ChildProcess.emit (events.js:310:20)
at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12) …
```
=> fix(appx): Invalid code signing tool when building for windows 10 arm64

packages/dmg-builder/src/dmg.ts
Prior commit did not properly reference the desired os.release() function and caused dmg build to fail.
=> fix issue #4639: require().split is not a function

packages/electron-updater/src/DownloadedUpdateHelper.ts
Closes #4928
In my setup I was encountering a situation where there was never an `update-info.json` file created and the `cachedInfo` object in `DownloadedUpdateHelper.getValidCachedUpdateFile()` was `undefined`.
This effectively meant that an error was thrown and the update never downloaded.
This makes the code a little bit more resilient by using optional chaining and nullish coalescing from typescript to ensure that the cachedInfo object is not undefined and then that the `fileName` is not null.   If it is undefined it will fall back to the `cleanCacheDirForPendingUpdate` function.
I also changed another instance of the `==` operator to `===` as that is generally preferred.
The root cause of this issue is that the try/catch that is supposed to check if the file exists does not work. …
=> fix: cached update validation failing on undefined filename

packages/app-builder-lib/src/util/yarn.ts
Enables NPM_NO_BIN_LINKS by pushing `--no-bin-links` parameter to yarn exec args
Since yarn 2 was released `--no-bin-links` parameter was deprecated
=> chore: enable NPM_NO_BIN_LINKS for yarn 1.x.x

auto-update.md
Adding this warning to the docs because the behaviour is not mentioned in the docs currently.
Please check [this code](https://github.com/electron-userland/electron-builder/blob/2e49f0bb1bd8448e1c2ccc4e2eb9def77b1a04df/packages/electron-updater/src/AppUpdater.ts#L72) for more information.
=> docs: add warning about allowDowngrade behaviour

packages/app-builder-lib/src/binDownload.ts, packages/app-builder-lib/src/targets/nsis/NsisTarget.ts, packages/app-builder-lib/src/targets/nsis/nsisUtil.ts
Resolves #4955
Instead of busting the cache as I said in #4955, I use the environment variable content as a cache key prefix because it resolves the issue, there's less code to change, and if someone changes the environment variable back to a directory that was used before, it won't needlessly re-download items.
This promise catch wasn't the only issue. Some functions that called it were in lazy-val calls so they were caching the result. I removed the lazy-val usage making them a function that calls `getBin` / `getBinFromUrl` each time (which itself uses the promise cache anyway so I think it's fine). Maybe some variables could be renamed now but I decided to change the minimum and see what you say.
=> Re-fetch downloads if cache directory has changed

packages/electron-updater/src/AppUpdater.ts
When the app updater fails because the version string can't be parsed, we are putting `latestVersion` into the logs, which we know is `null`. That's not too helpful, but putting the raw string from `updateInfo.version` is helpful because you might be able to see what's gone wrong with parsing it.
=> Log the raw version string when AppUpdater fails to parse semver of latest version

packages/electron-updater/src/providers/BintrayProvider.ts
Reverts electron-userland/electron-builder#4921
it's a mistake, you can rollback that merge. It's was a configuration issue on our side :-(
=> Revert "Update BintrayProvider.ts"

packages/app-builder-lib/electron-osx-sign/sign.js
This fix was directly lifted from https://github.com/electron/electron-osx-sign/pull/228 authored by @MarshallOfSound
=> Sign macOS objects depth-first (close #4932)

packages/electron-updater/src/AppUpdater.ts
Added optional parameter for download notification in checkForUpdatesAndNotify
- if the parameter is not given, uses default notification message.
- if {appName} occurs in notification body or title, formatNotification changes it to application name.
- if {version} occurs in notification body or title, formatNotification changes it to application version.
=> feat: add custom download completed notification

packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/options/SnapOptions.ts, packages/app-builder-lib/src/targets/snap.ts, test/snapshots/linux/snapTest.js.snap, test/src/linux/snapTest.ts
Allow applications to expose slots when installed via snap on linux. This is needed for example in applications that want to implement the MPRIS interface to allow external media player control.
=> feat(linux): add slots option for snap builds

packages/electron-builder/src/cli/install-app-deps.ts
Change process.mainModule to require.main as process.mainModule is deprecated since nodejs v14
Should not break as require.main has been around since v0.1.17
=> fix: replace deprecated interface

packages/app-builder-lib/electron-osx-sign/index.d.ts, packages/app-builder-lib/electron-osx-sign/sign.js, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/macPackager.ts, packages/app-builder-lib/src/options/macOptions.ts
Addresses https://github.com/electron-userland/electron-builder/issues/3302 and https://github.com/electron-userland/electron-builder/issues/2035. See [this PR](https://github.com/electron/electron-osx-sign/pull/210) for the main issue: `electron-osx-sign` right now has options only for entitlements used to sign every `.app` in the bundle. This is an issue for Mac App Store builds that want to use a login helper, because `.app` files aside from the login helper need to be signed with entitlements that look like:
```
<dict>
<key>com.apple.security.app-sandbox</key>
<true/>
<key>com.apple.security.inherit</key>
<true/>
</dict>
```
while the login helper must be signed with entitlements that look like:
```
<dict>
<key>com.apple.security.app-sandbox</key>
<true/>
</dict>
```
Changes to …
=> Add loginhelper entitlement option

configuration/squirrel-windows.md
The app must be able to handle Squirrel.Windows startup events that occur during install and uninstall. Fixes missing shortcut icons, double startup, etc.
=> Squirrel.Windows documentation

auto-update.md
This does three things:
1. Makes it clear that what the difference being highlighted is between the quit-and-install flow and the non-update quit flow. I, along with others, had incorrectly thought it was pointing out a difference between how `electron-updater.autoUpdater.quitAndInstall` and `electron.autoUpdater.quitAndInstall` works.
2. Points out that users should subscribe to `before-quit-update` if they want to do something before the windows are closed (like the [Electron auto-update doc](https://www.electronjs.org/docs/api/auto-updater#event-before-quit-for-update) does).
3. Points out that it's not true for AppImage and NSIS. They manually install then call `electron.app.quit` directly, whereas `MacUpdater` (for example) calls `electron.autoUpdater.quitAndInstall`.
=> Docs: auto-update: clarify how quitAndInstall behaves

packages/app-builder-lib/src/winPackager.ts
Although the flag was checked against in signing DLLs in the extra files and resources, the files in the asar unpacked directory were
not using the same check.
Closes #4728
=> fix: respect signDlls flag on Windows in asar.unpacked

packages/electron-updater/src/differentialDownloader/multipleRangeDownloader.ts
Nothing more happen when response ends. It leads to issue that no events are pushed outside: e.g. download is successful. In successful cases - I'm not an expert in streams - but as I understand somewhere resolve is called. I didn't find more proper solution, so just wait for 10 seconds and call reject. If resolve was already called previously in success case, this will not lead to any issues.
This PR fixes issue #[4618](https://github.com/electron-userland/electron-builder/issues/4618)
@develar could you please have a look
=> fix(multipleRangeDownloader): when response ends nothing more happens

packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/codeSign/windowsCodeSign.ts, packages/app-builder-lib/src/options/winOptions.ts
I was having a codesign error (0x80096005) when using a self signed certificate with the default `rfc3161TimeStampServer` property.
After seeing this issue https://stackoverflow.com/a/62163144 I switched over to `http://timestamp.digicert.com` for `rfc3161TimeStampServer` and it worked again.
I am proposing this should be the default (unless someone can fix the comodo issue!).
=> fix(appx) Default rfc3161TimeStampServer to http://timestamp.digicert.com

packages/app-builder-lib/src/targets/nsis/NsisTarget.ts
This fixes an issue which I've observed (and documented in issue #5005) with a McAfee virus scanner: After NSIS is writing the first part of the EXE, the virus scanner locks the file for further writing for a while, which causes the second write to fail and makes it impossible to build on my work laptop, because I'm not allowed to exclude certain files from the scanner. This fix checks whether the file is writable. If not it waits and checks again every 2s until the file is released by the scanner. A corresponding message is written to the console.
=> fix(nsis): output files sometimes locked by virus scanners (#5005)

packages/electron-updater/src/NsisUpdater.ts, packages/electron-updater/src/windowsExecutableCodeSignatureVerifier.ts
This https://github.com/electron-userland/electron-builder/commit/dead150769463adbff38b19e9099df6547db0e24 commit was added as a security measure to avoid command injection when we use downloaded file path that contains quotes when running powershell command.
e.g: `Get-AuthenticodeSignature 'C:\\path\\my-bad-';calc;'filename.exe'` will start a calculator app.
Banning the quotes does stop the command injection, however it also introduce unwanted behavior when performing an update, an example, when the user's path contains a quote, update will never be installed. See: https://github.com/electron-userland/electron-builder/issues/4889
Fixes https://github.com/electron-userland/electron-builder/issues/4889 by escaping the quotation as per windows powershell documentation.
e.g. 
```ts
// …
```
=> fix(electron-updater): escape quotes instead of throwing an error

packages/app-builder-lib/src/util/yarn.ts
Same issue as https://github.com/electron-userland/electron-builder/issues/3049 but for 'darwin' target.
node-libcurl fails to download precompiled binaries for darwin target:
> 2020-08-01 05:53:38  |    node-pre-gyp verb cli [
2020-08-01 05:53:38  |    node-pre-gyp verb cli   '/usr/local/bin/node',
2020-08-01 05:53:38  |    node-pre-gyp verb cli   '/project/node_modules/node-libcurl/node_modules/.bin/node-pre-gyp',
2020-08-01 05:53:38  |    node-pre-gyp verb cli   'install',
2020-08-01 05:53:38  |    node-pre-gyp verb cli   '--fallback-to-build'
2020-08-01 05:53:38  |    node-pre-gyp verb cli ]
2020-08-01 05:53:38  |    node-pre-gyp info using node-pre-gyp@0.15.0
2020-08-01 05:53:38  |    node-pre-gyp info using node@12.16.1 | linux | x64
2020-08-01 05:53:38  |    node-pre-gyp verb …
=> Fix pre-gyp for darwin targets if build on Linux or in Docker

packages/app-builder-lib/templates/nsis/assistedInstaller.nsh
#5051  Introduced ability to define custom finish page in nsis build.
However, it always throws 
```
install function "StartApp" not referenced
```
warning/error if the user want to alter the way how the app is started.
This PR fixes this error and let the user alter the behavior of finish page completely.
=> fix:(nsis): Fix custom finish page insertion

packages/electron-publish/src/gitHubPublisher.ts
https://github.com/electron-userland/electron-builder/issues/2074#issuecomment-631292925
set EP_GH_IGNORE_TIME to true will allow us to ignore the release time on github to publish to latest release
=> make it possible to ignore release time when publish to github

packages/app-builder-lib/templates/nsis/include/installUtil.nsh
This fixes #4057, the most commented open issue.
Current behavior: when installer detects previously installed version, it tries to run its uninstaller. And if the uninstaller is missing/entire installation directory is missing/uninstaller is damaged/uninstaller fails with error code - then the installation is aborted and the user has only one option: "Cancel" button.
Proposed behavior: ignore and proceed to installation. The most popular scenario causing the bug #4057 is user manually deleting the installation directory. *After that, the user is unable to install the app again.* The only way for the user to fix the issue is to manually delete the uninstall registry entry. The sole purpose of the installer is to install the app, so I think it should proceed to installation. Error …
=> fix:(nsis): Do not abort when uninstaller fails

packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/macPackager.ts, packages/app-builder-lib/src/options/macOptions.ts
This provides support for overriding the electron-osx-sign `strict-verify` property and supersedes a prior PR that only supported boolean values here.
=> Added support for overriding ‘strict-verify’ electron-osx-sign property.

packages/app-builder-lib/src/targets/AppImageTarget.ts, test/snapshots/linux/linuxPackagerTest.js.snap
this should fix #4035
Add missing %U in .desktop file of appimages, which is missing because the `Exec` var is set, so the code to add it to the other desktop files is not active: 
https://github.com/electron-userland/electron-builder/blob/f938de5aae09cb832a6f7f742e64a0d6c025fb9f/packages/app-builder-lib/src/targets/LinuxTargetHelper.ts#L95-L105
=> Add missing %U in desktop file of appimages

packages/app-builder-lib/src/targets/snap.ts
Without this, using protocols in snaps don't work properly as the app is opened by the url isn't passed to the app.
=> add missing %U in desktop file of snap builds

packages/app-builder-lib/templates/nsis/include/installer.nsh
This fixes #2514
**Current behavior:**
Shortcut is recreated if either ```$oldDesktopLink != $newDesktopLink``` **OR** ```$oldDesktopLink exists```.
This mostly happens during update process when ```createDesktopShortcut = true``` and ```allowToChangeInstallationDirectory = false```.
**Proposed behavior:**
Change condition to **AND**. So this will result in following workflow during update.
Shortcut should be recreated ONLY if path changed or old file missing:
```
if (links changed AND Old file exists) {
// recreate lnk
} 
!ifdef RECREATE_DESKTOP_SHORTCUT
elseIf (links changed OR old file missing) {
//recreate lnk
}
!endif
```
If *links haven't changed - nothing recreated*
=> fix:(nsis): Do not delete shortcut if Path is not changed

packages/dmg-builder/package.json, packages/dmg-builder/src/dmgLicense.ts
Fixes #5319
In Big Sur the long time deprecated `Rez` and `hdiutil unflatten` tools were removed.
I am  injecting DMG license with [dmg-license](https://github.com/argv-minus-one/dmg-license) package by keeping compatibility with TXT/RTF license and buttons files.
In this first version I keep all the old code.
=> fix(dmg): build under Big Sur is not possible if license file is used

packages/electron-updater/src/DownloadedUpdateHelper.ts
This fixes #5029. I tested using DMG, NSIS, and AppImage.
=> electron-updater: don't clean temp directory if cached update file doesn't exist

packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/options/SnapOptions.ts, packages/app-builder-lib/src/targets/snap.ts, test/snapshots/linux/snapTest.js.snap, test/src/linux/snapTest.ts
This is required to allow snap-packaged app declaring mpris slots.
Compile source and schema, then `TEST_FILES=snapTest yarn test`.
I'm currently developing a [portable music player with electron](https://gihub.com/) named `melodie`.
One very basic feature is the usage of [MediaMetadata](https://developer.mozilla.org/en-US/docs/Web/API/MediaMetadata), which makes the operating system aware of which track is currently playing, and gives it a change to pause, and jump to next or previous.
On linux systems, this integrations is use [Media Player Remote Interface Specification](https://www.freedesktop.org/wiki/Specifications/mpris-spec/) (mpris): the application sends DBus commands to interact with the OS.
This works perfectly fine with all the packager I've tested, except with snap.
When …
=> feat(snap): ability to specify slot properties

packages/app-builder-lib/src/targets/AppxTarget.ts
honor publisher in `package.json`, for example:
```JSON
"build": {
"appx": {
"publisher": "CN=\"Bob Doe\", O=\"Bob Doe\", STREET=123 Fake St., L=London, S=London, PostalCode=A1042, C=GB",
}
}
```
=> fix:(appx): invalid CA publisher syntax from app-builder (#3501, #4931)

configuration/nsis.md
Add specific documentation about the the steps described in #2227 ([here](https://github.com/electron-userland/electron-builder/issues/2227#issuecomment-339662811)) for including nested installers and other install-time resources.
=> docs(nsis): Add example for including installer resources

packages/builder-util/src/arch.ts
Previous behavior: `pacman` files built for `arm64` could not be installed. Instead, `pacman` would return errors similar to:
```
error: failed to prepare transaction (package architecture is not valid)
:: package yourpackage-arm64 does not have a valid architecture
```
New behavior: `pacman` files built for `arm64` install correctly.
This change corrects the value returned by `toLinuxArchString` when `arch` is `Arch.arm64` and `targetName` is `pacman`. Pacman calls this architecture `aarch64` whereas other targets call it `arm64`. Compare to the existing code for `ia32`, which `pacman` calls `i686` and others call `i386`.
This change also adjusts the value returned by `getArtifactArchName` to better match convention when `arch` is `Arch.arm64`: both `pacman` and `rpm` use `aarch64` in …
=> fix(arm64): fix pacman build, pacman & rpm artifact names

packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/options/SnapOptions.ts, packages/app-builder-lib/src/targets/snap.ts
This pull request adds the `title` option for the `Snap` format.
The option defaults to `productName`.
The `title` attribute (see [Snap format](https://snapcraft.io/docs/snap-format)) describes:
_"An optional title for the snap, may contain uppercase letters and spaces"_
A pull request containing the supplemental documentation was created separately:
[docs(snap): add documentation for Snap `title` option (for #5350)](https://github.com/electron-userland/electron-builder/pull/5351)
=> feat(snap): add Snap `title` option

configuration/snap.md
These are the documentation amendments for this corresponding pull request:
[feat(snap): add Snap `title` option](https://github.com/electron-userland/electron-builder/pull/5350)
=> docs(snap): add documentation for Snap `title` option (for #5350)

packages/app-builder-lib/src/targets/LinuxTargetHelper.ts
If icon path is not explicitly defined in config, `sources` would be an empty array. This leads `resolveIcon` not to send `--path` argument  to `app-builder-bin`. Then `app-builder-bin` fails to create the icon set properly.
I suppose we can set a default `--path` value in `resolveIcon` or `app-builder-bin`, but for safety, I chose to only modify the `LinuxTargetHelper`.
Fix https://github.com/electron-userland/electron-builder/issues/4617
Fix https://github.com/electron-userland/electron-builder/issues/4186
Fix https://github.com/electron-userland/electron-builder/issues/2577
Fix https://github.com/electron-userland/electron-builder/issues/5014
=> fix(AppImage): Linux icon is not set if path is not explicitly defined in config

packages/dmg-builder/vendor/mac_alias/alias.py, packages/dmg-builder/vendor/mac_alias/bookmark.py, packages/dmg-builder/vendor/mac_alias/osx.py
A new version of mac_alias has been released (v2.2.0), with a fix for `arm64`. This updates a command that uses `libc['statfs$INODE64']` - this has changed for non-Rosetta python on the M1 macs.
https://github.com/al45tair/mac_alias/pull/11
=> Bump mac_alias

packages/app-builder-lib/src/macPackager.ts
This PR is based on https://github.com/electron-userland/electron-builder/issues/5383
Now “/node_modules/playwright-firefox/.local-browsers” and “/node_modules/playwright/.local-browsers” also getting ignored like “/node_modules/puppeteer/.local-chromium”.
=> fix: signing of playwright/playwright-firefox

packages/app-builder-lib/templates/nsis/include/allowOnlyOneInstallerInstance.nsh
Windows `taskkill.exe` will kill the actual installer when using the `/t` option it appears after some vigorous testing.
```
C:\Windows\system32>taskkill /t /im "Badlion Client.exe" /fi "PID ne 62548"
ERROR: The process with PID 65300 (child process of PID 57508) could not be terminated.
Reason: This process can only be terminated forcefully (with /F option).
ERROR: The process with PID 43552 (child process of PID 57508) could not be terminated.
Reason: This process can only be terminated forcefully (with /F option).
ERROR: The process with PID 59664 (child process of PID 57508) could not be terminated.
Reason: This process can only be terminated forcefully (with /F option).
SUCCESS: Sent termination signal to process with PID 62548, child of PID 57508.
ERROR: The process with PID 57508 …
```
=> fix(nsis): don't kill ourselves when upgrading

packages/dmg-builder/package.json
`dmg-license` `package.json` sets that the module is only compatible with mac. This breaks `yarn install` on `linux` and `win32`. This PR moves `dmg-license` to `optionalDependencies` so `yarn` can ignore the error.
=> fix(dmg-builder): fix dmg-license is incompatible with linux and win32

packages/app-builder-lib/src/macPackager.ts
Co-authored-by: @mmaietta 
#5426 adds Apple Silicon support and it works well with dmg/zip (non-Mac App Store builds). This PR fixes bugs and makes sure that Apple Silicon support is also ready for Mac App Store build.
Without this PR, arch-specific MAS builds will be created at the same path `dist/mas/${productName}-${version}.pkg` and overwrite each other. With this PR, MAS builds will be created at: 
- `dist/mas/${productName}-${version}.pkg` (for x64, backward compatible)
- `dist/mas-arm64/${productName}-${version}-arm64.pkg` (for arm64)
=> feat(mas): Apple Silicon support

packages/app-builder-lib/package.json, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/macPackager.ts, packages/app-builder-lib/src/packager.ts, packages/app-builder-lib/src/platformPackager.ts, packages/builder-util/src/arch.ts, packages/electron-builder/src/builder.ts, test/snapshots/mac/macPackagerTest.js.snap, yarn.lock
=> feat: Apple Silicon Universal Support

packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/configuration.ts, packages/app-builder-lib/src/electron/ElectronFramework.ts
Follow up from discussion with @lutzroeder and @quanglam2807 
https://github.com/electron-userland/electron-builder/pull/5481#issuecomment-749752069
- Enabling `electronDist` to be a function that returns the path to the electron dist directory. 
- Updated documentation for the expected options (string path vs function)
This is necessary for universal builds where an `electronDist` must be specified per-architecture and there are multiple Arch-Targets provided. This applies to Windows (ia32+x64) and Mac (x64+arm64)
```
const archs = platform === builder.Platform.MAC ? [builder.Arch.universal] : [builder.Arch.x64, builder.Arch.ia32]
const targets = platform.createTarget(null, ...archs)
```
Used in electron-builder config as::
```
electronDist: (options: …
```
=> feat: Custom electronDist callback

packages/electron-updater/src/MacUpdater.ts
If an arm64 mac is running an intel version of an app (through Rosetta) and there are no arm64 versions of the app to update to then we should update to the intel version anyway.
Without this code change then an arm64 mac would be stuck on the current version until an arm64 version is released.
=> fix(mac): Allow arm64 macs to update to x64 version if no arm64 version available

packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/macPackager.ts, packages/app-builder-lib/src/options/PlatformSpecificBuildOptions.ts, packages/app-builder-lib/src/platformPackager.ts, packages/app-builder-lib/src/targets/ArchiveTarget.ts, packages/builder-util/src/arch.ts, packages/builder-util/src/util.ts, packages/dmg-builder/src/dmg.ts
See #5495.
This adds a `defaultArch` option to `MacConfiguration` to allow switching which 'arch' gets the default target name (skipping the arch extension) for `.zip` and `.dmg` to allow transitioning from `x64` (past/default) to `universal` to `arm64`.
@mmaietta @quanglam2807 @develar
=> feat: macOS default architecture (#5495)

packages/electron-updater/src/AppImageUpdater.ts, packages/electron-updater/src/NsisUpdater.ts, packages/electron-updater/src/differentialDownloader/DifferentialDownloader.ts, packages/electron-updater/src/differentialDownloader/ProgressDifferentialDownloadCallbackTransform.ts, packages/electron-updater/src/main.ts
Fixes a bunch of issues such as #2521 #4919 #5341...and so many other duplicate tickets
I have tested this with:
- nsis
- nsis-web
- AppImage
I have not gotten to test the AppImage system, but I will test that in the next day or two. Probably works fine though since it is just using the same logic as nsis-web
Some further notes:
1. I have gone ahead and tested this with and without a `onProgress` being supplied, it works for both
2. With these logic changes it will go from 0 -> 100% on the `download-progress` event two times on `nsis-web` (and other similar packaging systems) because it will first download the blockmap, and second download the actual changes. I figured it was better to leave like this, vs change it. This makes it more clear to the user that something is happening (instead …
=> feat: send download-progress information when downloading diff packages

packages/app-builder-lib/src/electron/electronMac.ts, packages/electron-updater/src/AppImageUpdater.ts
The appimage-filename-updated event is emitted here, so that if the appimage filename is updated, the app will have the opportunity to update the path in the .desktop file
=> emit appimage-filename-updated event

packages/app-builder-lib/src/macPackager.ts, packages/app-builder-lib/src/platformPackager.ts
Resolve https://github.com/electron-userland/electron-builder/issues/5547
`@electron/universal` requires that `Contents/Info.plist` of `arm64` and `x64` build to be identical. But `asarIntegrity` of each build is different so when it is added to `Info.plist`:
```
<key>AsarIntegrity</key>
<string>xxx</string>
```
It causes `Contents/Info.plist` to become mismatched. `@electron/universal` returns `Error: Expected all non-binary files to have identical SHAs when creating a universal build but "Contents/Info.plist" did not`, causing the build process to fail.
This PR disables `asarIntegrity` for universal build.
=> fix(mac): fix "Contents/Info.plist" don't have identical SHAs when creating a universal build

packages/builder-util-runtime/src/httpExecutor.ts
Looks like the amazon dual auth problem is now on other urls than amazonaws.com because github releases is using it now too
=> Also Look for the Amazon cred header to remove auth header

packages/electron-publish/src/publisher.ts
I noticed publishing was not working in Bitbucket Pipelines, just like other CI envs, Bitbucket uses a custom env variable to set the publish tag. This PR should fix it!
Note: CI seems to be failing on all PRs.
=> Detect CI tag for Bitbucket pipelines

packages/app-builder-lib/src/asar/asarUtil.ts
Fixes https://github.com/electron-userland/electron-builder/issues/5565 by adding an `.on("open", () => {})` guard around using the file stream. 
From [the documentation](https://nodejs.org/en/knowledge/advanced/streams/how-to-use-fs-create-read-stream/):
```js
// This will wait until we know the readable stream is actually valid before piping
readStream.on('open', function () {
// This just pipes the read stream to the response object (which goes to the client)
readStream.pipe(res);
});
```
The original `createReadStream` call, without a guard, fails on my M1 mac when building multiple architectures with larger files (>7mb). This change makes packaging totally reliable and is best practice for a `readStream`.
=> Add "open" guard for AsarUtil to fix concurrent builds

packages/electron-updater/src/AppUpdater.ts, packages/electron-updater/src/MacUpdater.ts
Make `electron-updater` on macOS behave like other OSes regarding the `autoInstallOnAppQuit` flag by cheating a bit around Squirrel.Mac limitation of not being able to *not* apply an update after it has downloaded it.
I tried to make my changes as minimal as possible, and took advantage of the fact that `electron-updater` already downloads the update by itself first and only expose said update to Squirrel in a second time. The trick here is to only trigger Squirrel when we want to apply an update rather than after a successful download.
This PR is basically a rebase of #4308 which never got reviewed and had been automatically closed by the stale bot.
This feature is required for our app ([Ledger Live](https://github.com/LedgerHQ/ledger-live-desktop)) to be able to do an additional …
=> feat(electron-updater): follow `autoInstallOnAppQuit = false` on macOS

packages/electron-updater/src/differentialDownloader/DifferentialDownloader.ts
This change avoids loosing state in the logger in case users inject a logger class instead of an object with functions.
=> fix(nsis): keep injected logger state

configuration/publish.md
Closes #5636
With the arrival of GitHub Actions, more and more users are running their CI and publishing on GitHub Actions. GitHub Actions comes with a repo scoped session bounded GITHUB_TOKEN and I believe that can be used instead of a PAT.
I believe the documentation should reflect that as PAT should be AVOIDED due to its extended privileges.
Also, included GITHUB_TOKEN since it's a supported env.
=> Updated GitHubOptions to include GitHub Actions

packages/app-builder-lib/src/electron/ElectronFramework.ts, packages/builder-util/src/log.ts, packages/builder-util/src/util.ts, packages/electron-builder/src/cli/cli.ts, test/snapshots/BuildTest.js.snap, test/snapshots/mac/macPackagerTest.js.snap, test/src/helpers/packTester.ts
Providing an alternative approach to #5664
Fixes double wrapping of an error message (duplicated `formatOut`)
Significantly improves logging readability for debugging issues. Also adds `task.name` to the cli logging in order to more easily identify where a function is throwing
=> chore: improving log readability

packages/app-builder-lib/src/options/SnapOptions.ts
The documentation says that the following packages are staged by default:
https://github.com/electron-userland/electron-builder/blob/0b03f106d3215f5f9206776899bdc69ceccfb8d4/packages/app-builder-lib/src/options/SnapOptions.ts#L39
However, `getDefaultStagePackages` returns the following:
https://github.com/electron-userland/electron-builder/blob/0b03f106d3215f5f9206776899bdc69ceccfb8d4/packages/app-builder-lib/src/targets/snap.ts#L306
=> docs: Update default stagePackages for Snapcraft

packages/electron-updater/src/BaseUpdater.ts
In my application I wish to set `autoInstallOnAppQuit` to false, so that electron-updater doesn't install the update when the application quits. However it turns out that when you set `autoInstallOnAppQuit` after you have called `checkForUpdates`, the quitHandler will already be added. And there is no further check in place to prevent the app from installing the update. So even if `autoInstallOnAppQuit` is set to false it will still install the update on quit.
I have added a check to prevent the above from happening. And thus making `autoInstallOnAppQuit` behave as expected.
=> fix: make autoInstallOnAppQuit behave as expected

packages/app-builder-lib/src/fileMatcher.ts
There is a single `}`, but it is a part of the expansion pattern `${}` not the glob pattern.
=> fix: typo in `fileMatcher`'s default patterns

packages/electron-updater/package.json, packages/electron-updater/src/NsisUpdater.ts, packages/electron-updater/src/main.ts, packages/electron-updater/src/util.ts, pnpm-lock.yaml, test/src/urlUtilTest.ts
The updater derives the path to the old blockmap file by using the url of the new blockmap file and changing the version. The code uses a RegEx with the replace function in order to replace all occurrences of the version number.
The problem is that the version number is a string like '0.1.9-2+273e2eb' and contains characters like '.' and '+' that get interpreted as regex characters. This works in most cases since a simple version string like '0.1.9' will accidentally match a typical filename. However it would aggressively match a filename like 'My-Application0A1B9-Setup-0.1.9.exe', and will fail with versions containing plus signs. 
I initially tried using String.ReplaceAll but it was only recently added in Chrome 85. Some sort of escaping needs to happen, so I used lodash.escapeRegExp …
=> fix: Escape version in NSIS Updater during replace

CONTRIBUTING.md
While going through contributing steps, I came across a couple of errors:
1. The link to the repo was outdated.
2. `tsc` failed to resolve when running `pnpm compile` without first installing dependencies.
=> fix: update repo in CONTRIBUTING.md

packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/configuration.ts, packages/app-builder-lib/src/electron/ElectronFramework.ts, packages/app-builder-lib/src/electron/electronMac.ts, packages/app-builder-lib/src/index.ts, packages/electron-builder/src/index.ts
The Electron project contains a [BRANDING.json](https://github.com/electron/electron/blob/665ac6f9c830edbf85596369b49844e1b910c59a/shell/app/BRANDING.json) file which will modify the resulting executable file names. A project I'm working on does exactly this in a fork of Electron.
Exposing these branding options allows Electron forks to build properly if branding has changed.
=> feat: add Electron branding options

packages/app-builder-lib/src/codeSign/macCodeSign.ts, packages/app-builder-lib/src/macPackager.ts
This PR adds support for the newer "Apple Development" certificates, mentioned in the [Xcode 11 release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-11-release-notes).
> Xcode 11 supports the new Apple Development and Apple Distribution certificate types. These certificates support building, running, and distributing apps on any Apple platform. Preexisting iOS and macOS development and distribution certificates continue to work, however, new certificates you create in Xcode 11 use the new types. Previous versions of Xcode don’t support these certificates. (45527608)
=> Add Apple development as valid development cert

.eslintrc.js
Now, CI testing always error because 
"prettier/prettier": process.env.CI ? "error" : "warn",
I change to 
"prettier/prettier": "warn"
=> chore: fix CI test error

packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/configuration.ts, packages/app-builder-lib/src/packager.ts, packages/app-builder-lib/src/util/config.ts, test/src/BuildTest.ts
This allows to mixin a config from multiple other configs, as if you `Object.assign` them, but properly combine `files` glob patterns.
=> Add support for recursive mixin-like extends

packages/app-builder-lib/templates/nsis/include/installUtil.nsh, packages/app-builder-lib/templates/nsis/installSection.nsh
Due to https://github.com/electron-userland/electron-builder/pull/5292, installers created using the default NSIS script ignore any errors returned by uninstallers, for example if files cannot be replaced, or if the uninstaller has been deleted. This behavior is often unwanted.
The changes here allow users to define `customUnInstallCheck` to handle such cases. In `customUnInstallCheck`, the error flag is set if the uninstaller cannot be executed at all (probably because it is missing). If the error flag is not set, `$R0` contains the return status/error level, which should be set to 0 if the uninstaller exits successfully.
=> feat: add custom macro for checking uninstallation results

packages/app-builder-lib/src/platformPackager.ts, packages/app-builder-lib/src/targets/nsis/NsisTarget.ts, test/snapshots/mac/macArchiveTest.js.snap
feat: When archs are specified in the `win.targets` config AND `${arch}` template is present in artifact name, then also build individual installers in addition to the universal dist
Implements:
#2554
#4467
=> feat: build additional arch-specific nsis installers when ${arch} template is provided

code-signing.md
Follow up to #5735 with some updated documentation for the new certs.
I'm not completely certain which certs are still required to sign for MAS since we are still using the old certificate types. But from my reading I believe the `3rd Party Mac Developer Installer:` is still required alongside either `Apple Distribution` (new cert) or `3rd Party Mac Developer Application:` (old)
=> Add documentation for Apple Development and Apple Distribution certs

packages/app-builder-lib/templates/nsis/assistedInstaller.nsh
Ability to add macros to uninstaller BEFORE the finish page
=> fix: Nsis custom uninstall page extension point

packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/configuration.ts, packages/app-builder-lib/src/packager.ts, packages/app-builder-lib/src/targets/MsiTarget.ts
Add a hook to allow modification of `project.wxs` before packaging.
Same idea as #4613 but for MSIs.
=> Adding msi project created hook.

.github/workflows/test.yaml, packages/app-builder-lib/src/linuxPackager.ts
- retaining previous default target behavior pre-flatpak merge since it is experimental.
- fixing test.yaml config where it incorrectly referenced an env var matrix
=> chore: default linux target + ci config

packages/electron-updater/src/MacUpdater.ts
Hello,
We are using `autoInstallOnAppQuit=false` (non mandatory updates). After the update, it stopped working for us on Mac. It's because we use `downloadPromise` to wait for the package to be downloaded. The promise never resolves on Mac. The promise never resolves because it depends on `autoInstallOnAppQuit` being `true` and the package being handed to Squirell.
I am not sure whether this is the correct solution to this problem or whether it's just a misunderstanding of the API contract, but I am sure you folks can advise.
Additionally, I am not sure whether we want the HTTP server should be running for `autoInstallOnAppQuit=false` all the time. Perhaps the whole server should only be started when `autoInstallOnAppQuit` is `true` and on `quitAndInstall` call when `autoInstallOnAppQuit` …
=> Fixing downloadPromise not resolving on Mac.

index.md
The following statement in the index.md file needs better tuning:
Before: `To ensure your native dependencies are always matched electron version`
After: `To ensure your native dependencies always matched the electron version`
=> Straighten out statement on index page

packages/builder-util-runtime/src/httpExecutor.ts
Related to #4676 and propably some more
As an electron app takes up more than 50 MB pretty easily the updater stops working due to the very low chunk size limit of currently 50 MB.
=> Extend http file limit

packages/electron-updater/src/main.ts
Export `CancellationToken`, `PackageFileInfo`, `ProgressInfo`, `UpdateFileInfo` directly from `"electron-updater"` as these types are already used in other exported types.
Fixes #5675.
=> Re-export some of the "builder-util-runtime" types directly from "electron-updater"

docker/base/Dockerfile, docker/build.sh, docker/wine-mono/Dockerfile, docker/wine/Dockerfile
While this is not strictly necessary right now (Ubuntu 18.04 is still supported until 2023), this makes it possible to move back to official wine packages (change included) instead of relying on the OBS packages (which seem to be missing a winehq-stable package at the moment, so this would also fix #5579)
Not sure if I can somehow test this change, FWIW my own builds still work with this container image 😄 
(Would also be nice if someone could update the images on Docker Hub afterwards)
=> feat(docker): update to Ubuntu 20.04 LTS

packages/app-builder-lib/src/version.ts
This is used eg. in the CLI to show the current electron-builder version
=> fix: update version.ts to match package.json

packages/app-builder-lib/templates/nsis/include/extractAppPackage.nsh, packages/app-builder-lib/templates/nsis/messages.yml
Unlike 7zip, zip decompression pushes a return value on stack. If it not
`success` installer should fail and display the error to the user
instead of assuming that installation was successful.
One of the causes of decompression errors might be a lingering child
process that still uses dlls and node.js bindings so that they cannot be
overwritten. In such case, prior to this patch nsis installer would
update some of the non-locked files and start the app as if it had been
fully updated.
=> fix: quit on decompression errors in NSIS

packages/app-builder-lib/package.json, packages/electron-builder/package.json
fix: Reducing node version to be >=14 as opposed to explicitly 14.17.0 (latest node 14 is 14.17.0) 
Fixes: #5893
=> fix: reduce node 14 version minimum to >=14.0.0

packages/app-builder-lib/src/targets/pkg.ts
Enabling arm64 builds for pkg distributions. Requires `arch` to be specified for build name, otherwise it'll try to build x64 and arm64 with the same name 
Fixes: #5847
=> fix(mac): adding arch suffix to pkg target to enable non-universal pkg builds

packages/dmg-builder/src/dmg.ts
Enables `dmg-builder` to use a custom python path. This is a necessary option to provide as `/usr/bin/python` may be python 3 and `dmg-builder` depends on python 2.7.
Closes #5889
=> feat: allow python path to be configurable

packages/app-builder-lib/src/targets/nsis/NsisTarget.ts
There are two problems here as reported in Issue #5857 
If you are only using one architecture and you have a ${arch} in the pattern you get the file twice, once from this.archs and once from inside the loop added on line 124. This duplication meant that the builder was trying to output to the same file with two builds and failed. I have added a check to only add individual architectures, if the size of this.archs is greater than 1.
I've also changed each arch to build sequentially. The reason for this is the build was failing because it couldn't access the 7zip files or uninstaller for the build process because it was locked, causing the build to fail.
This *seems* to fix things, though someone else might have a better way of doing it?
=> Issue 5857 ${arch} causes a build fail

packages/app-builder-lib/templates/nsis/include/allowOnlyOneInstallerInstance.nsh, packages/app-builder-lib/templates/nsis/messages.yml
Do not continue installation while the app is running. The running
executable and dlls are locked until the app is closed and the 7z
extraction will result in a partial update. If app cannot be quit
forcibly - ask user to close it manually and retry the app check in
the loop until success.
This situation might happen when the app runs in elevated permissions
mode while the installer is started normally.
=> fix(nsis): retry closing the app until success

packages/electron-updater/package.json, packages/electron-updater/src/MacUpdater.ts, packages/electron-updater/src/util.ts, pnpm-lock.yaml
Fix for https://github.com/electron-userland/electron-builder/issues/5672
=> Allow updating mac version running inside Rosetta to native ARM

docker/base/Dockerfile, docker/base/test.sh, test/snapshots/BuildTest.js.snap
The dockerfile upgrade to ubuntu 20 removed libxtst6 from the image. Adding it explicitly to install 
Fixes: #5907
=> fix/dockerfile-libxtst6 (#5907)

packages/electron-updater/src/main.ts
[Document](https://www.electronjs.org/docs/api/auto-updater#event-update-not-available)
=> Added missing `event-update-not-available` in UpdaterEvents

packages/app-builder-lib/src/targets/fpm.ts, packages/app-builder-lib/templates/linux/after-install.tpl, test/snapshots/linux/debTest.js.snap, test/src/linux/debTest.ts
Debian .deb packages built when linux.executableName is not the same as the "productName" from package.json don't run properly, because the post-inst script doesn't refer to the binaries at the appropriate path.
Add a test for the correct behavior.
Expose the correct sanitizedProductName value for the after-install.tpl postinst script template.
Still expose the productFilename, too, because users supplying their own templates might still be using it.
Make the associated "executable path in postinst script" test pass.
Closes: #5933
=> fix(linux): executable path in Debian postinst script

packages/app-builder-lib/src/targets/fpm.ts, test/snapshots/linux/debTest.js.snap
Set default debian package priority to "optional" since "extra" is deprecated. Updated debian tests. This should fix https://github.com/electron-userland/electron-builder/issues/5930.
=> Set default debian package priority to "optional"

packages/electron-updater/src/NsisUpdater.ts
Fix an incorrect use of blockmapFiles function providing the right
old and new versions.
Closes: #5940
=> fix(nsis): differential download

packages/app-builder-lib/src/electron/ElectronFramework.ts
Since `.lproj` is a folder 🙃 
Fixed #5917
=> Add `recursive: true` to `fs.rm` wnen removing locales

packages/builder-util-runtime/src/index.ts, packages/builder-util-runtime/src/publishOptions.ts, packages/electron-updater/src/providerFactory.ts
Currently, the custom publisher can't be used in combination with `electron-updater`: there is a hard-coded list of update providers, and an exception is thrown if the publisher isn't one of the known ones.
This adds the ability to use a custom provider; however, the caller must pass in a custom `options` object where one of the fields contains a constructor function.
This doesn't seem to affect the tests (that is, they still pass fine).
=> feat(electron-updater): allow custom update providers (#3656)

packages/dmg-builder/src/dmg.ts
Fixes an issue when the `productName` contains apostrophes. this is needed because in the python script it creates a literal string but the string is not escaped so an apostrophe terminates the string.
I have also added the backslash to the regex for completeness sake even though I don't think it's needed because it's sanitized out.
=> Escaping special characters in DMG entries

test/snapshots/BuildTest.js.snap, test/src/BuildTest.ts
chore: Tests break due to node-abi dependency `abi_registry.json` periodically changing file size.
- Removing node-abi from snapshot as its creating test instability even when `master` branch was already stable.
- Adding BuildTest posix unpack tests to default to running.
=> chore: ignoring node-abi in test snapshot to achieve consistent unit test results

packages/app-builder-lib/package.json, packages/builder-util-runtime/package.json, packages/builder-util/package.json, packages/dmg-builder/package.json, packages/electron-builder-squirrel-windows/package.json, packages/electron-builder/package.json, packages/electron-forge-maker-appimage/package.json, packages/electron-forge-maker-nsis-web/package.json, packages/electron-forge-maker-nsis/package.json, packages/electron-forge-maker-snap/package.json, packages/electron-publish/package.json, packages/electron-updater/package.json
This will allow various bots (as a renovate) to correctly find changelogs in the monorepos.
=> chrore: Add `repository.directory` to packages `package.json`

.github/issue_template.md, .github/workflows/issue-labeler.yml, packages/app-builder-lib/src/targets/ArchiveTarget.ts, test/snapshots/mac/macArchiveTest.js.snap
Building a separate blockmap file instead of embedding within zip for mac targets. Embedding the blockmap breaks codesigning.
Fixes: #4299
=> fix: write blockmap file for mac zip archives

packages/app-builder-lib/src/targets/nsis/NsisTarget.ts, packages/builder-util/src/util.ts
In order to sign the uninstaller, we generate it by building the installer in a special mode and then run it immediately to get the uninstaller stub which we can then sign.  If the installer is set to require administrative rights to run, this can lead to the build breaking as it would then require administrative rights to generate the (to-be-signed) uninstaller.  We can work around this by setting an environment variable to request Windows to ignore the embedded manifest and always run (the stub installer) as the invoker instead.
Fixes #5575
=> fix(nsis): generate uninstaller without elevating (#5575)

packages/app-builder-lib/templates/nsis/include/allowOnlyOneInstallerInstance.nsh
MessageBox shouldn't be shown if the app was killed or wasn't running.
Otherwise, it aborts the uninstallation in silent mode as IDCANCEL is the default action.
Introduced by [PR 5902](https://github.com/electron-userland/electron-builder/pull/5902)
=> fix: fix silent uninstallation for running app

index.md
Made same changes as #6056 in `docs` branch
=> docs: fix misused command in quick setup guide

README.md
`yarn pack` is a built-in command of yarn: https://classic.yarnpkg.com/en/docs/cli/pack
We should run `yarn run pack` to execute the npm script.
=> docs: fix misused command in README.md

packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/macPackager.ts, packages/app-builder-lib/src/options/macOptions.ts, test/src/mac/macPackagerTest.ts
I noticed that the `timestamp` option from electron-osx-sign was missing.
=> feat(app-builder-lib): Add timestamp for electron-osx-sign options

packages/electron-updater/src/BaseUpdater.ts
Proposed fix to the situation on Windows where an Electron is installed for all users of the machine e.g. into Program Files, but fails to update (installed app version is deleted but the update is never installed) due to failure to request admin rights.
node v12.16.2
npm v6.14.4
Current build.nsis settings in package.json: 
{
"oneClick": false,
"allowToChangeInstallationDirectory": true,
"allowElevation": true,
...
}
=> fix: Windows update fails for custom paths that require admin rights

.changeset/great-pumas-trade.md, packages/app-builder-lib/src/macPackager.ts
fix(mac): Adding Developer ID Application entry for development signing when building not a mas target. Fixes: #6094
fix(mac): Removing 3rd Party Mac Developer Application certificate selector. Fixes: #6101
=> fix(mac): signing cert filter incorrectly selects certificates (#6094) (#6101)

CONTRIBUTING.md
I'm not formatting the commit message as a patch, since only documentation is being affected.
=> fix(docs): Minor grammar/formatting fixes

packages/app-builder-lib/templates/nsis/uninstaller.nsh
Currently, if uninstall When `Silent is true` and `ONE_CLICK is defined`, the uninstaller will try to unisntall the app without closing it, which cases problems if uninstall it sliently when the app is running, the uninstaller can't remove all files, so left a broken app dir.
How to reproduce:
create an app, set `"oneClick": true` in config, make a `NSIS` installer, install it and try `Uninstall {appName}.exe /S` to silently uninstall it when the app is **running**.
Actual behavior: see above description.
Expected behavior: close the app then do the uninstall.
=> fix(nsis): should close app when `Silent` and `ONE_CLICK`

empty-ties-argue.md, packages/electron-updater/src/providers/GitHubProvider.ts, packages/electron-updater/src/providers/Provider.ts, test/snapshots/updater/nsisUpdaterTest.js.snap
Modify the GitHubProvider to provide the tag name of the latest
release as apart of its UpdateInfo (which is now encapsulated in the
GithubUpdateInfo interface) so that it uses that same tag name later
when it resolves the files to download.
fix electron-userland/electron-builder/issues/6076
=> fix: use tag name instead of version when resolving GitHub files

.changeset/stale-chairs-dress.md, packages/electron-updater/src/MacUpdater.ts
The issue https://github.com/electron-userland/electron-builder/issues/6120
=> fix(electron-updater): small cleanup and add more debug logging for MacUpdater to investigate #6120

packages/electron-updater/src/MacUpdater.ts
When using a github private repo as update server, the `file.url.pathname` for an arm64 version does not actually include the `arm64` string, and instead it just looks like a github release artifact ID. Looking at `file.info.url`, which contains the actual name of the dmg, seems more robust.
=> fix(electron-updater): arm64 updating issue with Github private repos as update server

.changeset/honest-comics-switch.md, packages/electron-updater/src/NsisUpdater.ts
Removing `data` from error being thrown. It's unnecessary and also unnecessarily large to be passing to the console
Resolves: #6131
=> fix: console log data is far too large

.changeset/stale-carrots-listen.md, packages/electron-updater/src/MacUpdater.ts
This PR addresses an issue where macOS updates fail due to a `null` object reference.
Node's HTTP server `address()` method returns `null` until the server is listening for connections. `electron-updater` 4.4.4 and 4.4.5 contain a bug where `MacUpdater` attempts to log the server port before it is listening, which causes an error.
To fix this while maintaining the completeness of the added logs, I removed the server address from the existing log event but otherwise kept it in place. When the server is listening, a new event is recorded that includes the server address.
=> fix(electron-updater): `null` object error when MacUpdater logs server port before it is listening

.changeset/honest-pandas-sneeze.md, packages/app-builder-lib/src/util/yarn.ts
Closes https://github.com/electron-userland/electron-builder/issues/6130
I found out on https://docs.npmjs.com/cli/v7/using-npm/config#cache-min that we can replace deprecated `--cache-min` with `--prefer-offline` to avoid pnpm install failure.
This is the commit where pnpm added support for `--prefer-offline`: https://github.com/pnpm/pnpm/commit/b553c5cfe07d2fe9c0f6f3f8003950b64ec6b5bb
=> fix: replace deprecated --cache-min option

.changeset/five-worms-work.md, packages/electron-updater/src/AppAdapter.ts, packages/electron-updater/src/AppImageUpdater.ts, packages/electron-updater/src/differentialDownloader/downloadPlanBuilder.ts, packages/electron-updater/src/providerFactory.ts, packages/electron-updater/src/providers/Provider.ts
Vite replaces process.env.* during builds. 
This leads to problems with the updater. 
A known workaround is to replace process.env.* with process.env["*"].
https://github.com/vitejs/vite/issues/3176
=> fix: workaround vite replacing process.env in updater

.changeset/config.json, package.json, pnpm-lock.yaml
Migrating changesets to use changelog-github to add additional annotations to our releases
Example: https://github.com/atlassian/changesets/blob/main/packages/changelog-github/CHANGELOG.md
=> chore: use github changelogs

.changeset/lovely-coats-grow.md, packages/electron-updater/src/MacUpdater.ts
On Intel macs, the error `No files provided` is thrown on the latest version of electron-updater (4.5.1) when the latest files include both arm64 and x64 builds.
The current filtering done when there are arm64 files available will return an empty array since there are arm64 files but we are not on a arm64 machine
https://github.com/electron-userland/electron-builder/blob/64fd696527e6f07cea7efc494d667276a9001430/packages/electron-updater/src/MacUpdater.ts#L55-L57
This change adjusts MacUpdater to filter the files to this criteria: 
- On an Intel Mac: Filter files to only include non-arm64 builds
- On an arm64 Mac: Filter files to only include arm64 builds
- If no arm64 builds are available: This will fallback to the condition to filter files to only include non-arm64 builds
**Steps to …
=> fix: (mac) Fix intel mac upgrade flow when both x64 and arm64 published

docs/generated/DebOptions.md
* [libappindicator: deprecated in Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895037)
* `gconf2` and `gconf-service` useless for KDE, package is for legacy applications and no longer used by GNOME.
Test under:
```
Operating System: Debian GNU/Linux 11
KDE Plasma Version: 5.20.5
KDE Frameworks Version: 5.78.0
Qt Version: 5.15.2
Kernel Version: 5.10.0-8-amd64
OS Type: 64-bit
```
=> docs: add tips for Debian and KDE

.changeset/tiny-dolls-smoke.md, packages/app-builder-lib/src/options/MsiOptions.ts, packages/app-builder-lib/src/targets/MsiTarget.ts, packages/app-builder-lib/templates/msi/template.xml
fix (msi): broken shortcut icon (#5965)
Add MSI option "iconId", replaces old static "icon.ico" icon identifier.
=> fix(msi): fix broken shortcut icon when using msi target

.changeset/wild-rabbits-do.md, packages/app-builder-lib/templates/nsis/messages.yml
`appCannotBeClosed` is displayed (quite prominently) when the NSIS
installer cannot proceed with the installation due to app still running
in the background. This commit translates it to several languages.
=> fix(nsis): internationalize appCannotBeClosed

.changeset/young-roses-sniff.md, packages/app-builder-lib/src/publish/BitbucketPublisher.ts
The way BitbucketPublisher is written, you can't use it to publish to repositories if you are not the owner of them. The PR introduces a new environment variable that allows you to change the override the username if necessary.
Closes https://github.com/electron-userland/electron-builder/issues/6292
=> fix(publish): Bitbucket publish can have username different from owner

.changeset/neat-buttons-press.md, packages/app-builder-lib/src/util/yarn.ts
Since node-gyp >= 8.4.0, building modules for old versions of Electron requires passing `--force-process-config` due to them lacking a valid config.gypi in their headers.
See also https://github.com/nodejs/node-gyp/pull/2497.
=> fix: latest node-gyp with old Electron versions

.changeset/spotty-clouds-invent.md, packages/app-builder-lib/src/publish/BitbucketPublisher.ts, packages/builder-util-runtime/src/publishOptions.ts
- use fs-extra to support Node < v14
- update optional config options for Token and Username (Bitbucket Private Repos)
=> refactor: update Bitbucket publisher

.changeset/afraid-lizards-juggle.md, packages/app-builder-lib/src/targets/LinuxTargetHelper.ts
https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables
If linux `executableArgs` already contains one of the mutually exclusive(%f / %u / %F / %U) code，don't append `%U`.
=> fix(linux): mutually exclusive exec command args

.changeset/olive-weeks-look.md, packages/electron-updater/src/MacUpdater.ts
- Would never call nativeUpdater.checkForUpdates() if not installing on
quit. Thus neither squirrelDownloadedUpdate was true nor the
nativeUpdater's event "update-downloaded" be emitted. Leading to
nothing happening.
- This commit fixes it by calling the checkForUpdates() in
MacUpdater.quitAndInstall() when necessary
Signed-off-by: Sebastian Malton <sebastian@malton.name>
fixes #6389
=> fix: quitAndInstall not working on macOS with autoInstallOnAppQuit=false

.changeset/beige-roses-itch.md, packages/builder-util/package.json, packages/builder-util/src/nodeHttpExecutor.ts, pnpm-lock.yaml
makes use of 'http_proxy' and 'https_proxy' environment variables
in order to allow for various tasks to be performed from behind a
corporate proxy. Requires third party dependencies because node's
standard built in http.Agent does not handle proxies natively.
closes #5906
fixes #6286
=> fix(builder-util): enable proxy handling in NodeHttpExecutor

.changeset/sixty-queens-tell.md, packages/electron-updater/src/BaseUpdater.ts
Signed-off-by: Sebastian Malton <sebastian@malton.name>
fixes #6394
=> fix: Emit 'before-quit-for-update' when updating via novel means

.changeset/plenty-drinks-wash.md, light-boxes-glow.md, packages/app-builder-lib/src/targets/AppImageTarget.ts
I've noticed that `--no-sandbox` is hardcoded into the arguments list when building an `AppImage`. This seems to be a good default for many implementations, but doesn't work for all of them. Example being the Mattermost Desktop App (see this issue: https://github.com/mattermost/desktop/issues/1804)
I've created this PR in order to potentially add an override option for users to specify their own arguments when launching the AppImage, using the `executableArgs` field which doesn't appear to be used by the AppImage at this time.
Let me know if this change makes sense and if I can make any further edits to support this.
=> feat: make `--no-sandbox` optional for building with AppImage

.changeset/channel-alternation-github.md, packages/app-builder-lib/scheme.json, packages/builder-util-runtime/src/publishOptions.ts
After upgrading from v22.11.11 to v22.14.8 I can't alternate the channel file name anymore due to schema validation.
=> fix(app-builder-lib): channel alternation for github is not working

.changeset/few-elephants-rhyme.md, packages/app-builder-lib/templates/nsis/include/allowOnlyOneInstallerInstance.nsh
Only find and kill processes owned by current user on per-user install.
Closes #6104
=> fix(nsis): Ignore other users processes

.changeset/shiny-kangaroos-juggle.md, packages/electron-publish/src/gitHubPublisher.ts
Explicitly set the protocol to https on the request objects to allow publishing to work from behind a proxy server when the https_proxy environment variable is set.
Closes #6286
=> fix: specify protocol as https to complete proxy support fix

packages/app-builder-lib/src/codeSign/macCodeSign.ts
In the M1 macOS laptop, If you skip code signing, it will cause your bundled macOS app not to work as behavior.
1. Localization description will not visible in the request permission action.
2. The request permission grant notify will trigger multiple times
I suggest that we can have an indicator description to guide our developer to know this case.
=> fix: optimize macCodeSign

.changeset/nervous-pandas-film.md, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/asar/asar.ts, packages/app-builder-lib/src/asar/asarUtil.ts, packages/app-builder-lib/src/asar/integrity.ts, packages/app-builder-lib/src/electron/electronMac.ts, packages/app-builder-lib/src/options/PlatformSpecificBuildOptions.ts, packages/app-builder-lib/src/platformPackager.ts, test/snapshots/globTest.js.snap, test/src/BuildTest.ts, test/src/globTest.ts, test/src/helpers/packTester.ts
See: https://github.com/electron/electron/pull/30667
Fix: #6506
Fix: #6507
=> feat(mac): ElectronAsarIntegrity in electron@15

.changeset/healthy-peaches-deliver.md, packages/app-builder-lib/templates/msi/template.xml
Disable advertised shortcuts, since MSIs with advertised Start Menu shortcuts that have a
Shortcut Property fail to install when deployed machine-wide via GPO, but work fine in all
other contexts. This might be a bug in Windows, or a misdiagnosis; see #6508 for more details.
Closes #6508
BREAKING CHANGE: Admins using advertisement must apply an MST to re-enable it. See #6508.
=> fix(msi): MSI fails to install when deployed machine-wide via GPO

.circleci/config.yml, .github/workflows/test.yaml
Stubbing circleci build to report a green status since we can't turn off the CircleCI build job.
=> fix: Stub CircleCI config since we can't disable it from dashboard

.changeset/spicy-crabs-draw.md, docker/base/Dockerfile, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/options/SnapOptions.ts, packages/app-builder-lib/src/options/linuxOptions.ts, packages/app-builder-lib/src/targets/snap.ts, packages/app-builder-lib/templates/snap/snapcraft.yaml, packages/builder-util/package.json, pnpm-lock.yaml, test/snapshots/linux/snapTest.js.snap, test/src/linux/snapTest.ts
Fixes https://github.com/electron-userland/electron-builder/issues/5881
Signed-off-by: Omer Akram <om26er@gmail.com>
=> feat(snap): add Snap compression option

.changeset/giant-dryers-beg.md, .changeset/serious-peas-help.md, packages/app-builder-lib/src/options/FileAssociation.ts, packages/app-builder-lib/src/options/MsiOptions.ts, packages/app-builder-lib/src/targets/MsiTarget.ts
Also fix iconId sometimes containing invalid characters, and iconId config option being ignored (was added in #6247, but it doesn't seem to have been used).
Marking this as a draft and targeting [v23.0.0-alpha](https://github.com/electron-userland/electron-builder/tree/v23.0.0-alpha) because I think there's some more related changes that should be made:
- I'm not sure why the iconId config option was added, and I think it should be removed. I don't see why anyone would want to manually configure it when we should be able to generate it ourselves. Even if the product name contains all invalid-for-MSI-Id characters, we could still generate a valid unique Id somehow (base64, seeded RNG, whatever).
- Even if we _do_ want to keep the option to manually configure it, it's now too specific – we …
=> feat(msi): add fileAssociation support for MSI target

.changeset/nervous-cherries-speak.md, packages/app-builder-lib/templates/nsis/include/extractAppPackage.nsh
`Nsis7z::Extract` ignores the errors when copying the files and thus can
leave us with the app that has old asar and bindings, but new assets. In
addition to that, the app will firmly believe that it is still running
an old version and would attempt to repeatedly auto-update until fixed,
leading to excessive bandwidth use and very unhappy customers.
This change extracts the contents of 7z archive into a separate
directory before attempting to copy them with `CopyFiles` function that
(unlike `Nsis7z::Extract`) does detect and report failures. To make our
lives easier the `CopyFiles` will also erase all files on a failure so
after retrying a few times we will ultimately have to fallback to old 7z
extraction directly into output folder.
The easiest way to trigger the failure is to:
1. Go to …
=> fix(NSIS): prevent partial overwrites

.changeset/chilly-trains-study.md, packages/app-builder-lib/templates/nsis/include/extractAppPackage.nsh, packages/app-builder-lib/templates/nsis/include/installUtil.nsh, packages/app-builder-lib/templates/nsis/messages.yml, packages/app-builder-lib/templates/nsis/uninstaller.nsh
Previously uninstaller would run `RMDir /r $INSTDIR` to remove the
currently installed version, but this operation is not atomic and if
some of the files will fail to delete it will leave them in the
directory while erasing the rest. If we are updating, however, this
leads us to a tricky situation where we cannot update these files, but
cannot also cancel the installation. Because of the erased files the app
won't be able to start if the installation won't completely at least
partially. However, the downside of that is that the app can have new
asar.unpacked files along with the old asar, executable, and bindings.
The approach of this change is to recursive use `Rename` instead of a
single `RMDir /r` in uninstaller (when `isUpdated` is true) to move the
whole app directory file by file to …
=> fix(nsis): use atomic rmdir on update

.changeset/cyan-carpets-cry.md, packages/electron-publish/src/gitHubPublisher.ts
I split this up into two commits, one with the actual fix, then one refactor so you could actually understand what the if statement was looking for before calling `this.overwriteArtifact`
=> fix: socket hang up error 422 issues in github publish

.changeset/seven-elephants-sing.md, packages/electron-updater/src/AppUpdater.ts, packages/electron-updater/src/NsisUpdater.ts
This PR allows the disabling of web installer files for `electron-updater` when it is only expected that a full installer should be downloaded.
This prevents a potential flaw in which an attacker using a webinstaller could serve a package not authorized by the developer to the end-user with malicious code inside.
=> fix: Allow disabling of webinstaller files to avoid confusion with actual installers

.changeset/violet-zoos-roll.md, packages/electron-updater/src/windowsExecutableCodeSignatureVerifier.ts, test/snapshots/updater/nsisUpdaterTest.js.snap, test/src/updater/nsisUpdaterTest.ts
This PR changes the certificate validation for NSIS installer to allow for validation of the entire DN instead of just the Common Name portion. This should allow for a more secure certificate validation.
=> fix: Update certificate validation on Windows to check full DN

.changeset/clean-kangaroos-serve.md, packages/app-builder-lib/package.json, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/macPackager.ts, packages/app-builder-lib/src/options/macOptions.ts, pnpm-lock.yaml
@electron/universal@1.2.0 introduced `mergeASARs` and `singleArchFiles`
options that enable merging of x64 and arm64 ASARs into one. This change
adds appropriate properties to the MacConfiguration interface and passes
them along to @electron/universal.
Tested by building our app with linked packages.
=> feat: use `mergeASARs` API by @electron/universal

.changeset/github-channel-support.md, packages/electron-updater/src/providers/GitHubProvider.ts
Allows for apps to run updates using provided channel track.
This only works if `options.allowPreRelease` is true.
If Channel is set in the updater, then latest will return the latest release that satisfies the logic in the [builder docs](https://www.electron.build/tutorials/release-using-channels.html#your-application)
If Channel is NOT set but prerelease is set, then latest will return the latest release.
technically this also supports custom channels, but if you run one of those you will never be able to return to the Latest track. 
I have marked this as a PR Draft as I would like to get discussion to make sure my logic is correct as well as this being my first contribution to this repo.
Tag:
#1722
#4988
=> feat(updater): Add Channel Support for Github with PreRelease

.changeset/good-scissors-listen.md, packages/electron-updater/src/MacUpdater.ts
This PR fixes a few issues I found when I was testing the MacUpdater:
- `crypto` doesn't export a default module, so you have to import the method you want.
- We were encoding the auth header backwards, now we encode into `base64` and decode to `ascii`
- There's an issue with Electron/Squirrel.Mac in which when the proxy server is hit to get the file, it doesn't send any of the specified headers. So I had to rework to just check the first hit for authentication (which you need to get the file name anyways), and the second for the first itself will not be authenticated. Since the file name is randomly generated, this should still avoid the security issue in which an attacker could shut down the server. NOTE: We might want to make the file name a little more secure, but that's up for …
=> fix: fixes for server auth for MacUpdater

.changeset/neat-socks-dress.md, .changeset/real-avocados-search.md, packages/electron-updater/src/MacUpdater.ts, packages/electron-updater/src/windowsExecutableCodeSignatureVerifier.ts
2 more small fixes:
- Removed backtick escaping for Windows code signing as it is unnecessary for Powershell and can cause the script to attempt to access the wrong file
- Updated the proxy filename to be more secure (512-bit string)
Let me know if I need to split these up or if I can leave it as one commit.
=> fix: More small security fixes

.changeset/thick-bikes-sleep.md, packages/dmg-builder/src/dmg.ts, packages/dmg-builder/vendor/dmgbuild/core.py, test/snapshots/BuildTest.js.snap
Adding python 3 support to dmg-builder in order to support mac os 12 which has entirely removed python2
Fixes: #6606
=> fix(dmg-builder): Support python 3

.changeset/sweet-parrots-wait.md, packages/electron-updater/src/AppUpdater.ts, test/snapshots/BuildTest.js.snap, test/src/helpers/updaterTestUtil.ts, test/src/updater/differentialUpdateTest.ts, test/src/updater/macUpdaterTest.ts, test/src/updater/nsisUpdaterTest.ts
Moving `isUpdaterActive` check to `checkForUpdates` which is utilized by `checkForUpdatesAndNotify`. Fixes: #6322
=> fix(updater): Remove checks for app-update.yml when auto-updates are not supported

.changeset/angry-starfishes-divide.md, packages/app-builder-lib/src/packager.ts
When the configuration has a artifactBuildCompleted file which needs to be waited, the upload starts anyway as it listens to the artifactCreated event. This resolves that by first waiting for any hooks, then dispatching the event.
=> fix(packager): wait for event before starting an upload

.changeset/pre.json
chore: Exiting `pre` mode to trigger a new 23.0.0 major version release
=> chore: Exit prerelease mode

.changeset/eleven-rivers-confess.md, packages/app-builder-lib/src/macPackager.ts
Without this PR, the `binaries`'s absolutely calculated paths will be concatenated with to their non-absolute paths.
This causes an error when building, where it tries to sign **both** the absolute **and** relative paths, failing on the relative paths. Example:
package.json:
```
"mas": {
"binaries": [
"Contents/Resources/ffmpeg",
"Contents/Resources/ffprobe"
]
}
```
Build output from `electron-builder --mac -m mas-dev`:
```
• Signing addtional user-defined binaries: [
"/Users/mifi/lossless-cut/dist/mas-dev/LosslessCut.app/Contents/Resources/ffmpeg",
"/Users/mifi/lossless-cut/dist/mas-dev/LosslessCut.app/Contents/Resources/ffprobe"
]
• signing         file=dist/mas-dev/LosslessCut.app identityName=Apple Development: Mikael Finstad (JH4PH8B3C8) …
```
=> fix: signing of user-defined binaries

.changeset/cold-crabs-destroy.md, packages/dmg-builder/vendor/dmgbuild/core.py
Fix #6606
python3 can't run our modified script since it can't find `reload` properly:
As `executePython("python3")` failed, it fellback to `executePython("python")` and fail:
```
NestedError: Cannot cleanup: 
Error #1 --------------------------------------------------------------------------------
Error: Exit code: ENOENT. spawn /usr/bin/python ENOENT
at /Users/pan93412/Projects/YesPlayMusic/node_modules/builder-util/src/util.ts:133:18
at exithandler (node:child_process:406:5)
at ChildProcess.errorhandler (node:child_process:418:5)
at ChildProcess.emit (node:events:520:28)
at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
at onErrorNT (node:internal/child_process:478:16)
at processTicksAndRejections (node:internal/process/task_queues:83:21)
Error #2 …
```
=> fix(dmg-builder): the "import" unbound issue

.changeset/olive-cobras-boil.md, packages/app-builder-lib/src/asar/asar.ts
See [discussion here](https://github.com/electron-userland/electron-builder/pull/6511#discussion_r818931948).
cc @mmaietta
=> fix(app-builder-lib): export missing TS types

.changeset/lucky-mice-smell.md, packages/app-builder-lib/src/winPackager.ts
This PR adds `swiftshader` to the directories that contain `.dll` file that are required to be sign for windows in order  to satisfy AppLocker policy.
Closes https://github.com/electron-userland/electron-builder/issues/5236
=> fix(signing): Include swiftshader in signing directories for windows

docs/configuration/configuration.md
Fix in documentation: the link to `SquirrelWindowsOptions` in [configuration](https://www.electron.build/configuration/configuration) leads to 404
=> fix(docs): link to SquirrelWindowsOptions in configuration

.changeset/cold-masks-bathe.md, .github/workflows/test.yaml, docs/generated/NsisOptions.md, package.json, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/targets/nsis/NsisTarget.ts, packages/app-builder-lib/src/targets/nsis/nsisOptions.ts, packages/app-builder-lib/templates/nsis/common.nsh, test/src/windows/assistedInstallerTest.ts
Exposing `customNsisBinary` and changing env var for `debugLogging` so that it doesn't conflict with other custom nsis scripts that use `DEBUG_LOGGING` env var. Also adding warning that electron-builder does not natively support the feature.
Fixes: #6715
=> fix: Change DEBUG_LOGGING env var for nsis installers as part of `customNsisBinary` config

.changeset/metal-elephants-remain.md, packages/electron-updater/src/MacUpdater.ts
If squirrelDownloadedUpdate is false, then we still need to have the proxy server opened for the `"update-downloaded"` event. Otherwise you're getting following error:
```
[2022-03-26 17:18:30.258] [info]  Proxy server for native Squirrel.Mac is closed (fileToProxy=https://utils.pacprotocol.com/yansafe-testnet/build/mac/yanSAFE-testnet-2.2.1-testnet.4-arm64-mac.zip)
[2022-03-26 17:18:30.274] [warn]  Error: Verbindung zum Server konnte nicht hergestellt werden.
[2022-03-26 17:18:30.274] [error] Error: Error: Verbindung zum Server konnte nicht hergestellt werden.
```
"Error: Verbindung zum Server konnte nicht hergestellt werden." = "Error: Could not connect to the server."
Moving `this.server.close()` after `this.nativeUpdater.quitAndInstall()` fixes the issue.
=> fix: Updater "Error: Could not connect to the server." in macOS

.changeset/nine-ants-wait.md, packages/app-builder-lib/templates/nsis/include/allowOnlyOneInstallerInstance.nsh
GIT-SCM installation can override window's native `find` command line
tool with the one from unix tools. This in turn changes the exit code of
the whole find process command and makes us detect the app as running
even though it is not.
Credit and original fix by @theAddict
See https://github.com/signalapp/Signal-Desktop/issues/5856
=> fix(nsis): specify full path to system's find

.changeset/polite-bugs-sparkle.md, .github/workflows/test.yaml, packages/app-builder-lib/scheme.json, scripts/fix-schema.js
fix: Overriding `additionalProperties` to allow electron-builder's schema validator to read requestHeaders. It seems that the schema generator does not read `NodeJS.Dict<number | string | string[]>` properly, which then doesn't allow any entries for `publish.requestHeaders` to be provided.
Fixes: #6635
=> fix(app-builder-lib): Overriding OutgoingHttpHeaders schema props

.changeset/rare-dolls-sin.md, packages/dmg-builder/src/dmg.ts
=> fix(dmg-builder): exec python fail on Macos12.3

.changeset/spotty-impalas-listen.md, .changeset/swift-masks-appear.md, packages/app-builder-lib/package.json, packages/app-builder-lib/src/targets/archive.ts, pnpm-lock.yaml
`7zip` on UNIX-based systems does not support conserving permissions when creating tarballs (see Backup and limitations: https://linux.die.net/man/1/7za), so tarballs created by `7zip` were always world-writable (permissions on files were set to `777` for all files added to the archive).
This is generally considered bad practice since it can lead to privilege escalation. This PR replaces the use of `7zip` with `tar` when creating the initial tarball, which preserves the permissions from the unpackaged folder. It also allows the user to change the permissions (in `afterPack`, if they want to) before creating the archive.
I couldn't find an issue created for this, so I'm not sure if this approach is correct, but I'd like to offer it as a solution to the issue described above. Open to …
=> feat: Use tar instead of 7zip to preserve file permissions in tar.gz packages

.changeset/fifty-schools-arrive.md, packages/app-builder-lib/templates/nsis/include/extractAppPackage.nsh
Before attempting to extract files with non-discriminating
`Nsis7z::Extract` that ignores the errors remove the temporary folder so
that we don't require twice as much disk space for this last resort
measure.
Additionally, replace `Quit` with a `Goto DoneExtract7za` so that the
last resort measure actually works.
=> fix(nsis): cleanup temporary 7z folder

.github/workflows/docker-deploy.yml, .github/workflows/issue-labeler.yml, .github/workflows/pr-labeler.yml, .github/workflows/semantic-pr.yml
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
=> chore: Set permissions for GitHub actions

.changeset/poor-windows-heal.md, packages/app-builder-lib/src/targets/nsis/NsisTarget.ts, test/snapshots/windows/assistedInstallerTest.js.snap, test/src/windows/assistedInstallerTest.ts
If the electron app needs a custom NSIS installer script (aka. oneClick option is false), the electron installer cannot get isAdminRightsRequired and failed to update when the electron app is running on window service because it requires installer that being admin rights.
It seems that any other reason does not exist when the electron builder NSIS oneClick option is false, update-info's isAdminRightsRequired is false.
Thank you!
=> fix(nsis): If window service needs to run installer for update, the installer must have admin previlege. #6786

.changeset/giant-dancers-march.md, packages/electron-updater/src/providers/GitHubProvider.ts
This PR address issue #6809 by casting channel string in typescript, instead of converting undefined to a string 'undefined' in javascript.
=> fix: github provider prerelease typescript cast

docker/wine/Dockerfile
Force winehq to use version 6.0.4 for docker images. Fixes #6780
=> fix: Lock wine version to v6 in docker image

.changeset/thin-toys-report.md, packages/electron-updater/package.json, packages/electron-updater/src/AppUpdater.ts, packages/electron-updater/src/electronHttpExecutor.ts, packages/electron-updater/src/main.ts, pnpm-lock.yaml, test/src/helpers/updaterTestUtil.ts, test/src/updater/nsisUpdaterTest.ts
- Helps with not having to look up the specific types for the events
that are emitted
Signed-off-by: Sebastian Malton <sebastian@malton.name>
=> refactor: Add better typing support on AppUpdater as an event emitter

.changeset/blue-carrots-begin.md, packages/electron-publish/src/gitHubPublisher.ts
This reverts commit [6a116b027504d1b3d44f78ba3df20f68d01dcb32](https://github.com/electron-userland/electron-builder/commit/6a116b027504d1b3d44f78ba3df20f68d01dcb32).
The GitHub release name is set to the version number instead of being left undefined.
Fixes  #6819
=> fix: set github release name to match the app version

.changeset/good-cooks-sniff.md, packages/builder-util/src/deepAssign.ts
With these changes, electron-builder can merge extraResources from parent config and current conifg. For example:
common.json:
```
{
"extends": null,
"extraResources": [
"common/*.files",
"common.file"
]
}
```
specific.json:
```
{
"extends": "common.json",
"extraResources": [
{
"from": "specific",
"to": ".",
"filter": ["file.txt"]
},
]
}
```
The merged config - dist/builder-effective-config.yaml:
```
directories:
output: dist
buildResources: build
extends: common.json
extraResources:
- filter:
- common/*.files
- common.file
- from: specific
filter:
- file.txt
files: []
electronVersion: 16.2.3
```
=> fix: Merge arrays from same config key.

.changeset/mean-elephants-sin.md, packages/builder-util/src/arch.ts
Add "arm" as an alias for armv7l as `process.arch` outputs `arm` on armv7l hosts
=> fix: Add "arm" as an alias for armv7l

.changeset/rich-hounds-flow.md, packages/app-builder-lib/templates/nsis/messages.yml
This changes the `appRunning` string to include a suggestion try closing the app manually if everything else fails (we saw a few reports where the app was still running in the background after clicking the "Ok" button in the dialog).
Additionally, we added a few translations for various strings in nsis messages template.
=> fix(nsis): change strings, add translations

.changeset/serious-buttons-exist.md, packages/app-builder-lib/src/targets/nsis/Commands.ts, packages/app-builder-lib/src/targets/nsis/Defines.ts, packages/app-builder-lib/src/targets/nsis/NsisTarget.ts
Because I wanted to list the environment variables that can be used in the NSIS script.
=> refactor(nsis): make ambiguous types strict

.changeset/flat-donkeys-cough.md, packages/app-builder-lib/src/targets/MsiTarget.ts
project.wxs contains invalid XML chars when building a package
containing an ampersand.
All attributes are already escaped thanks to EJS engine but the part
about files is built as a string and injected as-is in the template.
The next step would be to use an EJS template for the files too.
https://github.com/electron-userland/electron-builder/issues/5387
=> fix(msi): manually escape XML special characters when building XML

.changeset/wet-ligers-heal.md, packages/app-builder-lib/src/macPackager.ts
The universal target for macOS fires the afterPack hook after both x64 and arm64, but not after the final package has been created. This is a problem, as there may need to be some final opportunity to adjust the final package before signing in doSignAfterPack.
**Context**:
In my scenario, this comes up when I'm embedding a macOS appex extension (not a kernel extension) in my PlugIns folder. I can't pre-sign my extension, as electron-builder and by extension, @electron/universal seems to require that my extension is separated out into 2 distinct arch extensions (x64, and arm64) for combining them via makeUniversalApp.
I cannot sign these in the current afterPack hooks, because each arch-dependent package gets signed, and then upon the attempted package combination, fails as the packages …
=> fix: add afterPack call after macOS universal package is created

docs/configuration/configuration.md, docs/configuration/flatpak.md, docs/configuration/linux.md, mkdocs.yml, packages/app-builder-lib/src/options/linuxOptions.ts, scripts/jsdoc2md2html.js
This should have been a part of #5711 but, as I've [mentioned](https://github.com/electron-userland/electron-builder/pull/5711#issuecomment-817012077) before, I had some issues getting the documentation system to work on my machine in the past.
After some trial and error I did manage to get it working (fwiw, part of the problem was that version 1.2.4 of `mkdocs` is not compatible with Python 3.10 but downgrading to Python 3.8 fixed the problem), so now the `FlatpakOptions` should be properly [documented](https://deploy-preview-6893--car-park-attendant-cleat-11576.netlify.app/configuration/flatpak).
=> docs: add Flatpak documentation

.changeset/ninety-gifts-swim.md, CONTRIBUTING.md
Reflected what was posted in [this issue](https://github.com/electron-userland/electron-builder/issues/6820)
=> docs: Improved CONTIRUBTING.md

.changeset/strong-carrots-invent.md, packages/app-builder-lib/src/publish/KeygenPublisher.ts, packages/electron-updater/src/providers/KeygenProvider.ts
As part of an upcoming change to Keygen's API, we need to pin electron-builder's integration to v1.0 of Keygen's API so that newer Keygen users on v1.1 (the soon-to-be new default) can still utilize the current integration as-is. I wanted to get this integration updated before we roll out the newer API version in the coming weeks.
Below is a list of notable things that will be changing in v1.1 of Keygen's API:
1. The Release object's has-one Artifact relationship has been replaced with a has-many Artifacts relationship. The endpoint for the has-one Artifact relationship has been deprecated, i.e. `PUT /releases/<release>/artifact`.
1. A `status` attribute has been to the Release object, which can be `DRAFT` or `PUBLISHED`. New Release objects will default to a draft state and must be …
=> fix: pin Keygen integration to API v1.0

.changeset/famous-cheetahs-run.md, packages/app-builder-lib/src/macPackager.ts, packages/app-builder-lib/src/options/macOptions.ts
Some projects need to ship x64 binaries which will be run under
Rosetta2 on arm64 Macs.
This option allows a packager to specify that they're aware that
certain files in their distribution which are included in both x64
and arm64 builds are actually x64 binaries in both builds.
Without this option, electron/universal will attempt to lipo
the two binaries together, resulting in a build failure.
=> feat: electron/universal has a new minimatch option 'x64ArchFiles'

.github/renovate.json5
- https://docs.renovatebot.com/modules/manager/github-actions/#additional-information
- Pinned actions by SHA https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies
>Pin actions to a full length commit SHA
>Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release.
> Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository,
> as they would need to generate a SHA-1 collision for a valid Git object payload.
- https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
- https://github.com/renovatebot/.github/blob/b0c3aa85ef2bb242580f20b02b380ca532b4ce17/default.json#L13
=> chore: renovate bot setting to pin actions to a full length commit SHA

docs/code-signing.md
- Made it clear that ' If the configuration values are provided correctly in your package.json, then signing should be automatically executed.' (as answered in a previous discussion)
- Added alternative codesigning methods paragraph. This makes it clear to noobs that there are alternative methods of codesigning, so they dont not have to wrestle with fully understanding the built in process and can instead choose
=> docs: Amended codesigning docs

.changeset/seven-frogs-attend.md, packages/app-builder-lib/src/publish/KeygenPublisher.ts, packages/electron-updater/src/providers/KeygenProvider.ts, test/src/ArtifactPublisherTest.ts, test/src/updater/nsisUpdaterTest.ts
Follow up to #6909, which covers the API changes more in-depth. This should have no breaking changes for app's that are upgrading from v1.0 to v1.1 of the API, since it's only related to publishing (the auto-upgrade functionality still works as it did before from a consumer standpoint), so I think it's safe to include in a minor electron-builder update.
I don't think this should be merged until #6920 is out, to give an option to pin to v1.0 for whatever reason (via #6909).
=> feat: upgrade Keygen integration to v1.1

.changeset/wild-crabs-prove.md, packages/electron-publish/src/gitHubPublisher.ts
In the case that overriding an existing github artifact fails, it will continually retry until github reaches an API limit. This change should prevent retrying an unnecessary amount of times (but doesn't fix the root issue of why the override failed in the first place).
=> fix: prevent infinite looping of overwriteArtifact

.changeset/long-goats-attack.md, packages/electron-updater/src/providers/KeygenProvider.ts
This PR adds a product qualifier to artifact download requests. Resolving an issue where, in the case of a Keygen account distributing multiple products using electron-builder, a conflict can arise due to a shared filename across products. In most cases, this happens with `stable.yml` and its `yml` friends.
This issue will present itself under the following circumstances:
1. One or more products have an `OPEN` distribution strategy, meaning no license is required to view or download the artifacts. For example, Product A has a `LICENSED` distribution strategy, while Product B has an `OPEN` distribution strategy. This may result in Product A's updater requesting the `latest.yml` artifact without a product qualifier, causing our API to return the artifact of Product B, given it was released …
=> fix: add product scope to keygen provider

.changeset/little-ways-watch.md, packages/app-builder-lib/src/macPackager.ts
Despite the "Developer" in the name, this is only used for Mac App
Store Distribution.
This was by accident removed in #6105
=> fix(mas): Allow signing with "3rd Party Mac Developer Application"

.changeset/soft-planes-jam.md, packages/app-builder-lib/templates/nsis/assistedMessages.yml
This fixes a typo in a German NSIS installer message (perUserInstallExists).
=> fix(nsis): fix typo in German installer message

.changeset/cuddly-books-approve.md, packages/app-builder-lib/src/targets/nsis/WebInstallerTarget.ts, packages/app-builder-lib/templates/nsis/include/webPackage.nsh
When specifying `appPackageUrl` in the `NsisWebOptions` config `APP_PACKAGE_URL_IS_INCOMPLETE` would not be set to `null` and thus the installer would not include the packages.
Now I'm not sure if `APP_PACKAGE_URL_IS_INCOMPLETE` is even needed or if the check in `webPackage.nsh` could even be removed.
=> fix: nsis-web target set APP_PACKAGE_URL_IS_INCOMPLETE

.changeset/silly-moose-brush.md, docs/configuration/nsis.md
This environment variable is set and it's very useful, but the documentation missed it.
- https://github.com/electron-userland/electron-builder/blob/8ffd9d42d89634be76fd4554f659f2b2512f2081/packages/app-builder-lib/templates/nsis/portable.nsi#L78
- Refs https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/1331
- Refs https://github.com/electron-userland/electron-builder/issues/3186
=> docs: add missing PORTABLE_EXECUTABLE_FILE

.changeset/stupid-kiwis-eat.md, packages/app-builder-lib/src/options/SnapOptions.ts, packages/app-builder-lib/src/targets/snap.ts, test/snapshots/linux/snapTest.js.snap
=> fix: Remove DISABLE_WAYLAND for snaps

.changeset/curly-oranges-attack.md, docs/api/electron-builder.md, packages/electron-updater/src/AppUpdater.ts, packages/electron-updater/src/NsisUpdater.ts
Add installDir property for NsisUpdater. Now is it posible change install folder from AppUpdater.
#6818
=> feat: Add installDir property for NsisUpdater

.changeset/thirty-numbers-lick.md, packages/app-builder-lib/src/publish/KeygenPublisher.ts
Applying #6975 to the Keygen publisher as well. As covered in the linked PR, in the case of an `OPEN` product, the Keygen publisher's find-or-create method could receive a false positive if an open release is already available which has the same version as the one being created. This resolves the issue by adding a product qualifier to all release `GET` requests.
=> fix: add product scope to Keygen publisher

.changeset/gentle-singers-sip.md, packages/app-builder-lib/templates/nsis/include/allowOnlyOneInstallerInstance.nsh
Conditionally include nsProcess only if it has not previously been included or defined. 
There is a use case where you include `nsProcess.nsh` in your own custom install script. If you do that this file throws an error indicating that `nsProcess` has already been defined. I suspect it is due to the invocation order and how your custom scripts logic runs before the logic in this file.
=> fix: Wrap the nsProcess include in a !ifndef

.changeset/fair-gifts-explain.md, packages/electron-updater/src/providers/GitHubProvider.ts
Adding support for channels on GitHub was breaking change for those using only pre-release status without channel tags.
**Example 1:**
- User has app version 1.0.0 with `allowPrerelease=true`
- App has available updates on GitHub:
- 2.0.0-beta
- 4.0.0 latest
Expected result is to offer latest 4.0.0 version, but in current state it offers 2.0.0-beta. 
**Example 2:**
- User has app version 1.0.0 with `allowPrerelease=true`
- App has available updates on GitHub:
- 2.0.0 latest
- 3.0.0 in pre-release state
Expected result is to offer pre-released 3.0.0 version, but in current state it offers no update at all.
=> fix(electron-updater): fix backward compatibility for GitHub provider without channels

docs/configuration/nsis.md
The docs doesn't cover customWelcomePage for NSIS installer as it is not possible to configure the Welcome Page using configuration.
This is useful if one need to display Welcome Page for NSIS installer as the default behaviour is intentionally omitted. Refer to https://github.com/electron-userland/electron-builder/issues/1501#issuecomment-297274642
=> docs: Add customWelcomePage example to Custom NSIS script

.changeset/mean-cheetahs-look.md, packages/builder-util/src/deepAssign.ts
Follow up from: https://github.com/electron-userland/electron-builder/pull/6841#issuecomment-1125215560
Filters out duplicate assign's when cascading configs (files, extraFiles, etc.) by converting to Set first
=> fix: Duplicate values during deep assign of extra files

.changeset/chatty-trains-agree.md, docs/api/electron-builder.md, docs/configuration/publish.md, package.json, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/electron/electronVersion.ts, packages/app-builder-lib/src/publish/BitbucketPublisher.ts, packages/app-builder-lib/src/publish/KeygenPublisher.ts, packages/app-builder-lib/src/publish/PublishManager.ts, packages/builder-util-runtime/src/httpExecutor.ts, packages/builder-util-runtime/src/publishOptions.ts, packages/electron-publish/src/gitHubPublisher.ts, packages/electron-publish/src/publisher.ts, pnpm-lock.yaml, test/snapshots/PublishManagerTest.js.snap, test/src/ArtifactPublisherTest.ts
=> feat: Adding timeout to publisher config for api requests and uploads

.changeset/tidy-singers-carry.md, docs/configuration/configuration.md, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/appInfo.ts, packages/app-builder-lib/src/configuration.ts, packages/app-builder-lib/src/targets/fpm.ts, packages/app-builder-lib/src/winPackager.ts, packages/builder-util/src/util.ts, packages/electron-builder/src/cli/install-app-deps.ts
Fixes #6945.
`buildNumber` is not overridable in the config and is provided directly by the CI, this should be `buildVersion` instead.
Dashes are not supported for iteration in some versions of fpm, so I replaced dashes with underscores. https://github.com/jordansissel/fpm/issues/1833
Also, the linter complained, so I fixed up the type definition for the `use` function.
=> fix: use `buildVersion` not `buildNumber` for fpm `--iteration` flag

.changeset/violet-comics-cover.md, packages/app-builder-lib/src/macPackager.ts
Swaps `["3rd Party Mac Developer Application", "Apple Distribution"]` to `["Apple Distribution", "3rd Party Mac Developer Application"]` fixing the problem with code signing to publishing the MAS package on Mac Apple Store.
I found the issue #7040 while trying to fix the problem, followed the suggestion, and validated it.
=> fix: Invalid code signing for MAS build (#7040)

.changeset/weak-mice-boil.md, docs/api/electron-builder.md, docs/auto-update.md, packages/electron-updater/src/AppUpdater.ts
According to [the documentation](https://github.com/electron-userland/electron-builder/blob/a1d86fd75bbc7b252403c16966430a2e3562205d/docs/auto-update.md?plain=1#L980-L985), `downloadUpdate() ⇒ Promise<any>`.
According to [the code comment](https://github.com/electron-userland/electron-builder/blob/a1d86fd75bbc7b252403c16966430a2e3562205d/packages/electron-updater/src/AppUpdater.ts#L445-L448), `downloadUpdate() ⇒ Promise<string>`.
According to [the code](https://github.com/electron-userland/electron-builder/blob/a1d86fd75bbc7b252403c16966430a2e3562205d/packages/electron-updater/src/AppUpdater.ts#L476-L483), `downloadUpdate() ⇒ doDownloadUpdate() ⇒ Promise<Array<string>>`
This PR fix the typing to match with what the `downloadUpdate` code is doing.
- `downloadUpdate(cancellationToken: …
=> fix: improve `downloadUpdate` typing

.changeset/green-buses-beg.md, packages/app-builder-lib/src/options/macOptions.ts
Added some details on what an entitlment.plist file should contain and why wrong entitlements can make a build crash.
Also updated links to the default entitlement.plist as the previous one was giving a 404 (it's been moved adn renamed). Not sure if I linked the right files though. Maybe adding a link to the whole `entitlements` [folder](https://github.com/electron/osx-sign/tree/main/entitlements) instead  would be more suitable, as it contains self-explanatory filenames for the different usecases ?
Thanks to @jeremyspiegel @mmaietta and @idanwork for helping pinpoint the issue.
Closes #7050
=> chore: Add details to entitlement option for macOS configurations

.changeset/clean-gifts-ring.md, docker/base/Dockerfile, docker/wine/Dockerfile
Reverts electron-userland/electron-builder#6922
Fixes:
https://github.com/electron-userland/electron-builder/issues/7092
https://github.com/electron-userland/electron-builder/issues/7101
https://github.com/electron-userland/electron-builder/issues/7102
=> fix: Revert "feat: Upgrade to Ubuntu 22.04 and python 3.10"

.changeset/wild-crews-eat.md, docs/api/electron-builder.md, packages/electron-updater/src/AppUpdater.ts
=> feat: allow dev update config to be forced for testing auto-updater flow

README.md
Because of yarn 3 use PnP by default, but electron-builder still need node-modules.
So add configuration in the  `.yarnrc.yaml`:
```
nodeLinker: "node-modules"
```
will declare to use node-modules instead of PnP.
=> docs: declare node-linker when using Yarn 3

.changeset/smart-countries-decide.md, docs/generated/NsisOptions.md, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/targets/nsis/nsisOptions.ts
FIx typo of `docs/generated/NsisOptions.md`.
=> docs: fix typo

.changeset/tasty-pianos-jump.md, docs/generated/NsisOptions.md, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/targets/nsis/Defines.ts, packages/app-builder-lib/src/targets/nsis/NsisTarget.ts, packages/app-builder-lib/src/targets/nsis/nsisOptions.ts, packages/app-builder-lib/templates/nsis/assistedInstaller.nsh
<subject>add nsis option to remove the default uninstall welcome page</subject> <BLANK LINE>
<Scope>nsis</scope>
<body>until now we can't modify the default unwelcome page, this feature adds the option removeDefaultUninstallWelcomePage to give the possibility to remove from the nsis option this default page in order to custom it in the installer.nsh </body> <BLANK LINE>
<footer>BREAKING CHANGE: the nsis option removeDefaultUninstallWelcomePage is used in the assistedInstaller.nsh to decide if we must add the MUI_UNPAGE_WELCOME or not. based on the issue based on this issue https://github.com/electron-userland/electron-builder/issues/6987 </footer>
=> feat: add nsis option to remove the default uninstall welcome page

.changeset/chilled-items-fail.md, packages/builder-util/src/util.ts
add GithubActions environment variable to isPullRequest method.
GITHUB_BASE_REF environment variable is set in pull request build.
see: https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
=> feat: add Github Actions environment variable to isPullRequest method

.changeset/heavy-buttons-thank.md, docs/configuration/pkg.md, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/options/pkgOptions.ts
=> fix: formatting of Code in the MacOS PKG docs

.github/workflows/label-manager.yml, .github/workflows/pr-release.yml, .github/workflows/test.yaml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> fix(ci): workflows security hardening

.changeset/chilly-days-yawn.md, docs/api/electron-builder.md, packages/electron-updater/src/AppUpdater.ts, packages/electron-updater/src/BaseUpdater.ts, packages/electron-updater/src/MacUpdater.ts
Currently method _quitAndInstall_ only in silent installation mode allows user to set "isForceRunAfter" value to decide whether to run the installed application. Actually sometimes in non-silent installation mode, the user does not want to run the installed application after the installation is complete. In order to avoid breaking change previous functionality I add new method _quitAppAndInstall_ , it's will quit the app and explicit installs the update and allows to set "isForceRunAfter" value to decide whether to run the installed application.
=> feat: non-silent mode allow not to run the app when the installation is complete

README.md, docs/index.md
It will more clear to developer to see that note in `electron-builder` docs. This line was taken from pnpm [docs](https://pnpm.io/npmrc#public-hoist-pattern)
=> feat: update note for pnpm

.changeset/smooth-hounds-peel.md, packages/electron-updater/src/AppAdapter.ts
On macOS, `~/Library/Application Support` is where applications persist data, and caches are stored in `~/Library/Caches`.
Currently `electron-updater` mistakenly created its own `Caches` directory under `~/Library/Application Support`, which is bad practice and not align with e.g. the usage of `XDG_CACHE_HOME` below.
=> fix: inappropriate `electron-updater` cache directory on macOS

.changeset/empty-ligers-turn.md, packages/app-builder-lib/src/targets/snap.ts
The `executableArgs` option value is ignored for snap target, this PR fixes that bug
=> feat: Extending `linux` executableArgs option to be utilized for Snap target (fixes #4587)

.changeset/chilled-queens-think.md, packages/app-builder-lib/src/appInfo.ts
Fixes #7173
This new code allows the user to not the lower version parts, and have them default to zero instead. With this change the resulting weird-windows-version will be:
```
'1.2.3' => '1.2.3.0'
'1.2' => '1.2.0.0'
'9.2-beta' => '9.2.0.0'
'45' => '45.0.0.0'
'2022.6-beta2-dev-afafaf' => '2022.6.0.0'
```
=> fix: Allow non-semver versions in getVersionInWeirdWindowsForm

.changeset/two-eels-kiss.md, packages/electron-publish/src/publisher.ts
fixes https://github.com/electron-userland/electron-builder/issues/7066
If we use `getCiTag()` on GitHub Actions, we should return `GITHUB_REF_NAME`.
https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
=> fix: get CI tag in GitHub Actions

.changeset/real-olives-film.md, packages/electron-updater/src/windowsExecutableCodeSignatureVerifier.ts
Fixes https://github.com/electron-userland/electron-builder/issues/6917
In environments where PowerShell is in Constrained Language Mode, `[Convert]::ToBase64String` and `[System.Text.Encoding]::UTF8.GetBytes` won't work.
We're currently converting the output of `Get-AuthenticodeSignature -LiteralPath '${tempUpdateFile}' | ConvertTo-Json -Compress` to base64 in powershell to get possibly non-ascii data, which would otherwise be output in the current ANSI code page. This workaround was added in https://github.com/electron-userland/electron-builder/pull/5071, FYI @orzFly @hezhuojie.
I first tried setting PowerShell's `[console]::OutputEncoding`, but that is also not allowed in Constrained Language Mode. So this fix is to run `chcp 65001 > NUL` before running powershell.exe. See …
=> fix: support powershell constrained language mode

docs/index.md
Sync the readme.md from GitHub https://github.com/electron-userland/electron-builder/pull/7113
=> docs: add note for yarn3

.changeset/olive-planets-grin.md, packages/app-builder-lib/templates/nsis/installSection.nsh
I want a user to undestand why they cannot shutdown a computer, because the installation process have not been completed yet.
On windows we can use ShutdownBlockReasonCreate to show a better message when shutdown is blocked instaed of default one.
Before
After
=> feat(nsis): add ShutdownBlockReasonCreate for blocking Win Shutdown prompt

.changeset/small-paws-clean.md, docs/index.md
I propose add my own boilerplate [vite-electron-builder](https://github.com/cawa-93/vite-electron-builder) to list. I create it almost 2 year ago.
=> docs: Propose add vite-electron-builder to boilerplates

.changeset/spotty-vans-pay.md, packages/app-builder-lib/src/codeSign/windowsCodeSign.ts
We were running into an issue where windows builds on osx were trying to use `osslsigncode` in our parallels VM rather than signtool
=> fix: don't use osslsigncode in a vm

.changeset/good-balloons-admire.md, packages/app-builder-lib/scheme.json, packages/builder-util-runtime/src/publishOptions.ts
Currently it appears there's no support for the s3 accelerated bucket option.
Attempting to supply an endpoint causes the bucket to be appended on the URL, pushing the artifacts into a subfolder.
This PR adds the option to 'accelerate' the s3 bucket, where the s3 URL will be formatted as expected by s3.
For more information on s3 bucket acceleration and the expected URL formats, see:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/transfer-acceleration.html
Let me know if I missed anything, I'm happy to throw this PR away if I am off the mark, or there's an easier way to achieve this.
=> feat: Add the accelerate option for s3 buckets

.changeset/lazy-icons-ring.md, docs/configuration/snap.md, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/options/SnapOptions.ts, packages/app-builder-lib/src/targets/snap.ts, test/src/linux/snapTest.ts
Related to https://github.com/electron-userland/electron-builder/issues/7319 and https://github.com/electron-userland/electron-builder/pull/6976
This would unblock users facing issues related use to the older `core18` base type.
Motivation for this PR came from https://github.com/Kong/insomnia/issues/5531. 
@mmaietta let me know if there's anything that I can do to help move either this PR or https://github.com/electron-userland/electron-builder/pull/6976 forward. ~~I'm not sure if I'm also missing some changes e.g. (like the changeset mentioned bellow, or how to update the docs)~~ Updated changeset, schema and docs.
=> feat: Add base option for snapcraft

.changeset/violet-seahorses-wait.md, packages/app-builder-lib/src/util/appFileCopier.ts
Current behavior: If a directory includes only symlinks, the directory is not created and so symlink creation fails.  (Version: 23.6.0)
Fix: Create the parent directory or directories if needed using the fs-extra method "ensureSymlink". The dependency "fs-extra" is already present in this package.
Situation I was encountering:  Our application has a directory in which there are currently only symlinks. The directory and contents are not created and the result is a failedTask=build error with message "ENOENT: no such file or directory, symlink 'path-to-target' -> 'path-to-symlink'". (I've redacted the paths.) I observed that if I added even one non-symlink file into the directory, then the directory and all its contents would be created successfully.
=> fix: Ensure parent directories of symlinks are created

.changeset/plenty-spoons-prove.md, packages/app-builder-lib/src/util/license.ts
Regarding issue #7334  
[https://github.com/electron-userland/electron-builder/issues/7334]( https://github.com/electron-userland/electron-builder/issues/7334)
there was missing the `.html` extension.
=> fix: missing html extension for multi language license files in nsis target

.changeset/slow-avocados-carry.md, docs/configuration/win.md, packages/electron-updater/src/NsisUpdater.ts, packages/electron-updater/src/main.ts
Replace the PowerShell with [a native verify signature module](https://github.com/beyondkmp/win-verify-trust)， but not all users will have access to a Windows build machine if their project does not currently require a native module. For instance, compiling with Wine on linux/docker would no longer work. 
Providing a custom verify function interface, if the user want to use native verify module, they can pass it and they need to have an access to a windows build machine. If they don't pass it, will use the default verify signature function(https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/windowsExecutableCodeSignatureVerifier.ts).
**Interface**
```js
/**
* The verifyUpdateCodeSignature. You can pass …
```
=> feat: Provide a custom verify function interface in NsisUpdater

.changeset/chilled-shoes-sort.md, packages/app-builder-lib/src/macPackager.ts
cc @mmaietta 
Trying (almost) the same fix as suggested by @mayfield in this comment https://github.com/electron-userland/electron-builder/issues/7317#issuecomment-1351168459. I'm leaving the old legacy options in for now, I reckon they will be ignored when using the new https://github.com/electron/osx-sign ?
Not sure if in this case we should leave the legacy stuff in. There's a migration guide that can be checked for reference: https://github.com/electron/osx-sign/blob/a9cfce77512358420a850abfc102f784e02f8138/MIGRATION.md
=> fix: Update MacOS signOptions on macPackager #7317

.changeset/old-shrimps-drive.md, docs/configuration/publish.md, packages/app-builder-lib/scheme.json, packages/builder-util-runtime/src/publishOptions.ts, yalc.lock
According to the issue that I opened https://github.com/electron-userland/electron-builder/issues/7323. 
I think now it will be easier to understand.
=> docs: replaced 'access token' with 'app password' from BitbucketOptions

.changeset/nervous-zebras-accept.md, packages/electron-updater/src/windowsExecutableCodeSignatureVerifier.ts
We cannot catch the whoops error. Because all synchronous errors are handled. But here the error is generated not while the executor is running, but later. So the promise can’t handle it.
```typescript
new Promise(function(resolve, reject) {
setTimeout(() => {
throw new Error("Whoops!");
}, 1000);
}).catch(e => console.log('test is here:', e));
```
The verifySignature function has the same problem. we cannot catch  the error throw by the function handleError.
```typescript
export function verifySignature(publisherNames: Array<string>, unescapedTempUpdateFile: string, logger: Logger): Promise<string | null> {
return new Promise<string | null>(resolve => {
execFile(
"chcp 65001 >NUL & powershell.exe",
["-NoProfile", "-NonInteractive", "-InputFormat", "None", "-Command", …
```
=> fix: add reject in handleError in Windows `verifySignature` function

docs/tutorials/code-signing-windows-apps-on-unix.md
The executable path is missing in the JSign procedure cmd and the `configuration.path` variable was not explicitly explained in the exemple script for signing.
I think that this two changes improve the code signing understanding.
=> docs: improve the code-signing-windows-apps-on-unix.md page

.changeset/eleven-trainers-brake.md, packages/app-builder-lib/src/macPackager.ts
Currently, MAS builds are always signed, even if `identity: null` is explicitly passed. In fact, sign is called twice, first time ignored:
```
• skipped macOS code signing  reason=identity explicitly is set to null
• signing         file=dist/mas-arm64/Nozbe.app identityName=xxxx identityHash=yyy provisioningProfile=none
```
It should be possible to force a MAS build to be unsigned. (in my use case, I need this because I need additional modifications to the app before it can be Universalized, and only then it can be signed)
=> fix: Allow MAS builds to be unsigned if `identity: null` is explicitly passed

.changeset/empty-onions-own.md, packages/app-builder-lib/src/macPackager.ts
It's possible to force electron-builder to explicitly name build archs by setting, for example `defaultArch: ia32`. In this case, you'll get builds like `dist/mac-x64`, `dist/mac-arm64`. However, MAS builds are not behaving consistently, as defaultArch was ignored.
=> fix: MAS builds should respect arch suffix per `defaultArch` config

.changeset/thin-terms-change.md, packages/app-builder-lib/src/targets/snap.ts
=> fix: Remove adapter if core22 is set as base on snapcraft

packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/macPackager.ts, packages/app-builder-lib/src/platformPackager.ts, packages/app-builder-lib/src/winPackager.ts, test/src/BuildTest.ts
Only activating `afterSign` hook if the signing step wasn't explicitly skipped
This is a Breaking Change since previous behavior was always executing `afterSign` hook (albeit, probably incorrectly)
Fixes: #7257
=> fix: Execute `afterSign` hook only when signing is completed (BREAKING)

.changeset/brown-tigers-check.md, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/options/PlatformSpecificBuildOptions.ts
We've been running a version of this patch internally for awhile and decided that it is time to submit it as a Pull Request.
The idea of this change is to allow to pass a custom `vendor` object down to the `.yml` file. This object might have some custom properties on it like `requireManualUpdate` or `minOSVersion` that the vendor's updater could be checking when deciding whether to update to this release or not.
I understand that this will be ignored by the auto-updater bundled in electron-builder, but at least in our case we are running our own updater and we really find this additional information handy.
=> feat: vendor information in releaseInfo

.changeset/purple-phones-sin.md, .github/issue_template.md, docs/configuration/configuration.md, docs/generated/PlatformSpecificBuildOptions.md, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/options/PlatformSpecificBuildOptions.ts, packages/app-builder-lib/src/platformPackager.ts, scripts/jsdoc2md2html.js
Manually resetting `GYP_MSVS_VERSION` for multi-arch builds due to electron-rebuild and node-gyp overwriting the default var
Fixes: #7256
=> fix: reset `GYP_MSVS_VERSION` for multi-arch builds before `beforePack`

.github/workflows/test.yaml, docs/generated/PlatformSpecificBuildOptions.md, packages/app-builder-lib/src/winPackager.ts, test/snapshots/BuildTest.js.snap
fix: enable signing of .node modules in order to support WDAC (all code must be codesigned).
Fixes: #7329
=> fix: enable signing of .node modules in order to support WDAC

.changeset/stale-dots-build.md, packages/app-builder-lib/src/codeSign/windowsCodeSign.ts, packages/app-builder-lib/src/macPackager.ts, packages/app-builder-lib/src/platformPackager.ts, packages/app-builder-lib/src/winPackager.ts, packages/builder-util/src/fs.ts
fix: report the correct status result when `doSign` exits early from `macPackager` and `winPackager`. Updated function definition to return `Promise<boolean>` to properly flag intellisense
Follow-up from @nsrCodes PR: https://github.com/electron-userland/electron-builder/pull/7431
=> fix(packager): report the correct status result when `doSign` exits early

.github/workflows/test.yaml, test/snapshots/BuildTest.js.snap, test/src/BuildTest.ts
Due to the subdependency tree, the versions are not pinned, so randomly the `posix smart unpack` test will fail due to the new npm releases of those subdependencies. This PR changes all the "size" of the dependencies to be saved in the snapshot as `<size>`, however the directory tree of the asar header will still be verified. (i.e. if packages were to add new **files** to an npm package, then this test will still fail, but that should be expected since the asar header is a file system map)
=> fix: Removing file size from BuildTest smart unpack

.changeset/real-toes-beam.md, packages/app-builder-lib/src/codeSign/windowsCodeSign.ts, packages/app-builder-lib/src/index.ts, packages/app-builder-lib/src/packager.ts, packages/app-builder-lib/src/platformPackager.ts, packages/app-builder-lib/src/util/NodeModuleCopyHelper.ts
- beforePack
- afterSign
- artifactBuildStarted
- artifactBuildCompleted
- appxManifestCreated
- msiProjectCreated
- beforeBuild
- afterPack
- afterAllArtifactBuild
- sign
- onNodeModuleFile
fixes https://github.com/electron-userland/electron-builder/issues/7441
=> feat: Support mjs files for lifecycle operations

.changeset/real-toes-beam.md, .changeset/tall-bees-pay.md, packages/app-builder-lib/src/codeSign/windowsCodeSign.ts, packages/app-builder-lib/src/index.ts, packages/app-builder-lib/src/packager.ts, packages/app-builder-lib/src/platformPackager.ts, packages/app-builder-lib/src/util/NodeModuleCopyHelper.ts
Reverts electron-userland/electron-builder#7442
CI seems to have broken for all Windows tests, it consistently exits with error code 3221225477 (windows error 0xC0000005)
https://answers.microsoft.com/en-us/windows/forum/all/application-error-0xc0000005/6224ae45-a251-4f21-b076-74524618d00a
Attempting to revert commit to see if it resolves the issue
=> fix: Revert "feat: Support mjs files for lifecycle operations"

.changeset/cold-dingos-taste.md, .changeset/six-dogs-prove.md, docker/build.sh
Adding node 18 docker images for electron-builder (Electron 23 uses node 18).
=> chore: Adding node 18 docker images for electron-builder

.changeset/real-poets-compare.md, packages/app-builder-lib/src/codeSign/windowsCodeSign.ts, packages/app-builder-lib/src/macPackager.ts, packages/app-builder-lib/src/winPackager.ts
Recent changes (https://github.com/electron-userland/electron-builder/pull/7311) in platform packager `afterSign` hook show that the correct success status was not being returned after signing the app on macOS
This results in the app being signed but the terminal has the following message
>  skipping "afterSign" hook as no signing occurred, perhaps you intended "afterPack"?
found this on electron-builder v24.0.0-alpha.12
_Couldn't get a local development environment properly setup, so hoping someone could help test if these help solve the issue_
=> fix(packager): return success status from doSign function calls

.changeset/honest-mugs-invite.md, docs/configuration/configuration.md, packages/app-builder-lib/package.json, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/configuration.ts, packages/app-builder-lib/src/electron/ElectronFramework.ts, pnpm-lock.yaml, typings/electron-packager-plugin-non-proprietary-codecs-ffmpeg.d.ts
Implements #7210 
Credit to @burnhamup for PR example https://github.com/electron-userland/electron-builder/pull/7247 🙂
=> feat: Adding new downloadAlternateFFmpeg option to download non-proprietary ffmpeg library

.changeset/selfish-games-sniff.md, packages/builder-util/src/arch.ts
It feels like just having `aarch64` in the filename is not sufficient.
```
[root@7b42929061f0 /]# uname -a
Linux 7b42929061f0 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
yum install https://github.com/MuhammedKalkan/OpenLens/releases/download/v6.4.4/OpenLens-6.4.4.aarch64.rpm
Error:
Problem: conflicting requests
- package open-lens-6.4.4-1.arm64 does not have a compatible architecture
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```
There is also an fix available on [fpm](https://github.com/jordansissel/fpm/commit/cc0a4e736941401ed6f3a5b20269d1415c53f45c), but this requires fpm 1.13.0 or higher
=> fix(arm64): RPM architecture name

.changeset/old-melons-taste.md, .github/workflows/test.yaml, docs/configuration/mac.md, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/macPackager.ts, packages/app-builder-lib/src/options/macOptions.ts, test/fixtures/test-app-one/build/entitlements.mac.inherit.plist, test/fixtures/test-app-one/build/entitlements.mac.login.plist, test/fixtures/test-app-one/build/entitlements.mac.plist, test/src/PublishManagerTest.ts, test/src/mac/dmgTest.ts, test/src/mac/macArchiveTest.ts, test/src/mac/macIconTest.ts, test/src/mac/macPackagerTest.ts, test/src/mac/masTest.ts, test/src/updater/differentialUpdateTest.ts
Adding additional typesafety and fixing large issue where entitlements don't seem to be applied properly due to major semver bump in electron/osx-sign
Fixes: https://github.com/electron-userland/electron-builder/issues/7471
=> fix: updating SignOptions to leverage `optionsForFile` for entitlements

packages/app-builder-lib/templates/nsis/uninstaller.nsh
for issue https://github.com/electron-userland/electron-builder/issues/7489
=> fix: Missing quote syntax error in nsis uninstaller

CONTRIBUTING.md
The publish and link commands were grouped together, even though they needed to be run from entirely different locations.
=> chore(docs): clarify yalc setup instructions

.changeset/cyan-carpets-allow.md, packages/builder-util/package.json, packages/electron-builder/package.json, packages/electron-publish/package.json, packages/electron-updater/package.json, pnpm-lock.yaml
There were a good number of DefinitelyTyped packages in the non-dev dependencies.
=> chore(deps): Include all DefinitelyTyped packages as dev dependencies

docs/configuration/msi-wrapped.md, docs/configuration/msi.md, mkdocs.yml, scripts/jsdoc2md2html.js
=> chore(docs): adding msi and msi-wrapped to documentation site

.changeset/tricky-flies-bow.md, packages/electron-updater/src/BaseUpdater.ts
Fixes #7523 
When deciding if a process that we attempted to spawn actually started, we need to look at the PID of the spawned process (which will be `undefined` if it failed to start), not the PID of the original Electron process. #7503 introduced this error.
=> fix: Fix electron-updater error handling when spawning a process asynchronously

.changeset/gold-ladybugs-rhyme.md, packages/electron-updater/src/differentialDownloader/DifferentialDownloader.ts
the error will just be thrown by the net module if there's no error handler, leading to issues like #2398
our use case is that we get a lot of reports about these uncatchable errors with each release (https://github.com/tutao/tutanota/issues/5338)
I'm not sure if there needs to be additional cleanup after the first response fails, but it seems to fix the problem in my local tests and tries to fall back to full download properly.
=> fix(updater): handle errors on responses in differential download

.changeset/little-spies-double.md, packages/builder-util-runtime/src/httpExecutor.ts
=> fix: Don't use the content-length HTTP header to check size of data

.changeset/modern-waves-compete.md, packages/app-builder-lib/src/targets/nsis/Defines.ts, packages/app-builder-lib/src/targets/nsis/NsisTarget.ts, packages/app-builder-lib/src/targets/nsis/nsisUtil.ts, packages/app-builder-lib/templates/nsis/common.nsh, packages/app-builder-lib/templates/nsis/installer.nsi, packages/builder-util/src/fs.ts
Implements #7487
Used NSIS `SectionSetSize` function to set correct space.
=> feat(nsis): display "Space required" text for NSIS installer

.changeset/sixty-paws-rush.md, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/options/linuxOptions.ts, packages/app-builder-lib/src/targets/FpmTarget.ts
Closes https://github.com/develar/app-builder/issues/87
`deb.fpm: ['--deb-recommend=blah']` is insufficient as https://github.com/develar/app-builder always forces a `libappindicator3-1` into the recommendeds.
=> feat: allow specifying recommended dependencies for deb target

.changeset/shiny-jars-fetch.md, packages/app-builder-lib/src/targets/MsiWrappedTarget.ts, test/snapshots/windows/msiWrappedTest.js.snap, test/src/windows/msiWrappedTest.ts
Target names are not case sensitive, and are normalized by this function: https://github.com/electron-userland/electron-builder/blob/cd7b79f8273a32d3d6a4f4c4a139d847835df637/packages/app-builder-lib/src/targets/targetFactory.ts#L67-L78
This PR makes it so that the `msiWrapped` target doesn't complain when the `nsis` target has leading/trailing spaces or is not all-lowercase.
=> fix: msiWrapped: Normalize target names before checking for NSIS target

.changeset/two-goats-shop.md, packages/app-builder-lib/templates/nsis/assistedInstaller.nsh
During the first program install when the selected directory doesn't exist it's not enforced that path contains application name as sub-folder. On subsequent installs e.g. on update, that condition is enforces though, which creates a new installation in sub-folder.
This tries to address #6885
=> fix(nsis): Ensure application name sub-folder on fresh installs.

.changeset/large-items-argue.md, packages/builder-util/src/util.ts, packages/dmg-builder/src/dmgUtil.ts
We are [experiencing a lot of flakiness](https://github.com/Expensify/App/issues/20283) with our Electron deploys in a GitHub Actions macos-12 runner. This PR is an attempt to wrap the failing command in a retry, as has been done elsewhere in this repo.
I also added a simple backoff mechanism to the retry function.
=> fix(mac): Wrap hditutil detach in retry w/ backoff

.changeset/famous-shrimps-return.md, packages/app-builder-lib/src/electron/electronMac.ts, packages/app-builder-lib/src/macPackager.ts
This changes allows packaging different macOS targets with different CFBundleIndetifiers.  
It makes the `createMacApp` to look for a CFBundleIdentifier in mas config, if the app is MAS.
Solving the issue related here: #7570 
Current implementation ignores any `appId` specified in `mas`, directly using `appInfo.macBundleIdentifier` when writing Plist file.
=> fix: Allow building MAS and dmg targets with different appId

.changeset/nervous-readers-worry.md, packages/app-builder-lib/src/targets/archive.ts
Option for enable compression filter.
Example:
```
process.env.ELECTRON_BUILDER_7Z_FILTER = 'bcj2'
process.env.ELECTRON_BUILDER_COMPRESSION_LEVEL = 5;
```
BCJ2 is sets as default only for compression level 9, but is very slow.
If compression level sets to 5 and filter sets to `-mf=bcj2`, compression is very good with fast speed.
=> feat: added env variable for 7z filter

.changeset/great-seas-admire.md, packages/app-builder-lib/src/macPackager.ts
=> fix(mac): use Identity `hash` instead of `name` if it exists

.changeset/strange-planes-judge.md, packages/electron-updater/src/BaseUpdater.ts
=> fix: removing stdio from spawnSync to fix crash on rpm/deb updaters

.changeset/forty-ways-pay.md, packages/app-builder-lib/package.json, packages/app-builder-lib/src/packager.ts, packages/app-builder-lib/src/util/yarn.ts, packages/electron-builder/src/cli/cli.ts, pnpm-lock.yaml
fix: use electron-rebuilder API directly so as to override the platform for cross-platform prebuild compilations
Credit to debugger @cocktailpeanut in https://github.com/electron-userland/electron-builder/pull/7465
=> fix: use electron/rebuild Rebuilder directly for cross-platform builds

.changeset/empty-pears-hammer.md, packages/electron-updater/src/AppAdapter.ts, packages/electron-updater/src/DebUpdater.ts, packages/electron-updater/src/ElectronAppAdapter.ts, packages/electron-updater/src/RpmUpdater.ts
=> fix: trigger `app.relaunch()` if `isForceRunAfter = true` for rpm and deb updaters

.changeset/honest-comics-bake.md, packages/app-builder-lib/src/targets/FpmTarget.ts, packages/app-builder-lib/src/targets/LinuxTargetHelper.ts
fix #7601
this replaces all hyphens (`-`) in versions when targeting `"pacman"` with underscores (`_`) to follow [the pacman version format](https://wiki.archlinux.org/title/PKGBUILD#pkgver).
* i am only replacing the version of the package, not of the `.pacman` file, since doing so would (i think) require overwriting the version in `appInfo.version`, which is marked as readonly,
https://github.com/electron-userland/electron-builder/blob/285aa766c2675448689f2e465b6fa2b2acacdbc6/packages/app-builder-lib/src/appInfo.ts#L24
or adding a seperate rule to the `macroExpander`, which, as far as i can tell, does not have access to the current build target (which could be solved fairly easily with a new optional parameter tho)
https://github.com/electron-userland/electron-builder/blob/285aa766c26754 …
=> fix(linux): make semver pre-release versions valid for "pacman" and "rpm" target

.changeset/proud-balloons-applaud.md, packages/electron-updater/package.json, packages/electron-updater/src/AppUpdater.ts, pnpm-lock.yaml
The "typed-emitter" package pulls in a number of dependencies, including the large "rxjs" library.
=> fix: change typed-emitter to tiny-typed-emitter 

.changeset/lemon-cows-thank.md, docker/build.sh, docker/node/Dockerfile
node v14 is no longer maintained. Update node to current LTS version.
=> build: update Dockerfile -- Outdated Node version v14 --> v18

.changeset/slow-buttons-provide.md, packages/app-builder-lib/src/macPackager.ts
right now if `hardenedRuntime` is set to false, it default to `undefined`, while osx-sign is defaulting it to `true`, so basically the `false` will never work.
=> fix: use nullish coalescing operator for hardenedRuntime default

.changeset/four-starfishes-invite.md, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/macPackager.ts, packages/app-builder-lib/src/options/macOptions.ts
We recently upgraded from v22 to v24, and start getting `Not available for testing` in testflight, after comparing the entitlements, it looks like the issue is due to auto entitlements from osx-sign, after disabling it locally the issue is resolved.
Also this should address https://github.com/electron-userland/electron-builder/issues/7579
default should be true as osx-sign is checking for false with `===`: https://github.com/electron/osx-sign/blob/cd9e8f1146610fb0f1bb0d88a5219b208594e5b1/src/sign.ts#L211
=> feat:  Added support for overriding ‘preAutoEntitlements’ for electron/osx-sign

.changeset/sweet-monkeys-listen.md, packages/app-builder-lib/templates/msi/template.xml
Hi,
There is no option to change the target directory during the installation process(assisted+perMachine) for MSI. It says 'You can change the default installation folder' but, actually, you can't. This PR should fix it.
1. 
2.
=> fix: re-enable changeDir step for assisted, perMachine installs

.changeset/fast-plums-play.md, packages/app-builder-lib/package.json, packages/app-builder-lib/src/electron/electronVersion.ts, packages/app-builder-lib/src/packager.ts, packages/app-builder-lib/src/util/packageMetadata.ts, packages/app-builder-lib/src/util/yarn.ts, packages/electron-builder/src/cli/cli.ts, pnpm-lock.yaml, test/snapshots/BuildTest.js.snap, test/src/BuildTest.ts
fix: reverting migration to electron-rebuild since Cxx flags were backported to the latest versions of Electron
=> fix: reverting migration to electron-rebuild

.changeset/lazy-buttons-invent.md, packages/app-builder-lib/src/util/yarn.ts, packages/electron-builder/src/cli/install-app-deps.ts
=> fix: add back missing `createLazyProductionDeps` that was missed during revert

docker/build.sh
Downgrading docker for this month's docker release since 18.16 has a major semver bump in npm version, so 18.15.0 is the stopgap before then
Fixes: #7667
=> chore(docker): Set docker base node version to 18.15.0

docker/build.sh, docker/node/Dockerfile
fix: adding `IMAGE_VERSION` arg for docker `node` image so that it force rebuilds when pnpm is updated on any new date
=> fix: force rebuild all docker images for latest pnpm

CONTRIBUTING.md
Fixed typos in CONTRIBUTING.md.
This line:
By participating, you are expected to uphold this code. Please file issue to report unacceptable behavior.
changed to:
By participating, you are expected to uphold this code. Please file an issue to report unacceptable behavior.
Added space after comma in this line:
Unfortunately,the `yalc publish` command cannot pass multiple packages.
changed to:
Unfortunately, the `yalc publish` command cannot pass multiple packages.
=> docs: Fix typos in CONTRIBUTING.md

.changeset/poor-jobs-fold.md, packages/app-builder-lib/src/index.ts
Only schedule upload for unique files, otherwise it would try to upload the same files multiple times.
=> fix: duplicated uploads

.changeset/curvy-pugs-pull.md, packages/app-builder-lib/package.json, packages/app-builder-lib/src/index.ts, pnpm-lock.yaml
Updating to the latest `@electron/osx-sign`
Fixes: #7653
CC @quanglam2807
=> chore: update @electron/osx-sign

.changeset/large-brooms-jump.md, packages/app-builder-lib/src/macPackager.ts
For details about the problem, please see [Issue-7587](https://github.com/electron-userland/electron-builder/issues/7587), [this](https://github.com/Koppel-Zhou/electron-rebuild-error-demo) is a demo created to reproduce the problem
=> fix(mac): fix errors using native modules that require rebuild when the mac target is multiple and contains mas

.changeset/funny-geckos-clap.md, packages/dmg-builder/src/dmg.ts
=> fix(mac): Enhance the usage boundary of iconTextSize (#7769)

.changeset/real-planets-float.md, docs/configuration/nsis.md, packages/app-builder-lib/templates/nsis/assistedInstaller.nsh
An optimization scheme for this problem
https://github.com/electron-userland/electron-builder/pull/7141
https://github.com/electron-userland/electron-builder/issues/6987
=> feat: add customUnWelcomePage macro for nsis

.changeset/silent-cats-travel.md, packages/app-builder-lib/src/fileMatcher.ts
Adds `electron-builder.env` to the default file ignore list.
[Documentation](https://www.electron.build/configuration/configuration) currently suggests the use of this file for environment variable. However, if a developer uses `electron-builder.env` to store secrets (a common development practice), the default configuration will include these secrets in the packaged app. Adding the file to the default ignore list prevents this inadvertent secret disclosure.
Closes #7777
=> fix: exclude electron-builder.env from app

.changeset/yellow-games-beg.md, packages/app-builder-lib/src/platformPackager.ts
Windows build will fail because the icon.ico will put to ${version}/.icon-ico/ dir, not x.x.x/.icon-ico/ dir.
=> fix: bug #7711.

.changeset/nice-dogs-remain.md, docs/configuration/mac.md, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/macPackager.ts, packages/app-builder-lib/src/options/macOptions.ts, packages/app-builder-lib/src/platformPackager.ts
Extracting Notarize Notary and Legacy options into distinct interfaces so that only `teamId` is allowed when using `notary` tool.
Ref: https://github.com/electron-userland/electron-builder/issues/7683#issuecomment-1726471047
=> fix: Extract `NotarizeNotaryOptions` and `NotarizeLegacyOptions` to explicitly define required vars

.changeset/tough-roses-attend.md, packages/app-builder-lib/src/targets/nsis/NsisTarget.ts
This fixes #7791 by making `nsis` and `portable` builds not run in parallel.
This change should not break anyone's build process, but it could make it slower. However, I think slower is better than sometimes broken.
=> fix: Make nsis builds (and portable builds) not run in parallel

.changeset/bright-toys-camp.md, docs/configuration/snap.md, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/options/SnapOptions.ts
https://snapcraft.io/docs/base-snaps#Choosing%20a%20base
> core22 is the currently recommended base for the majority of snaps. But much like choosing a distribution base for a project or server, the best base for an application is dependent on an application’s requirements and which plugins or extensions a base supports. If there are specific dependencies that cannot be easily met with core22 then core20 is a valid and supported alternative, as is the older core18.
=> docs: add snap base core22 as an option

.changeset/smooth-lies-thank.md, packages/app-builder-lib/src/macPackager.ts
I just switched from `electron-builder-notarize` to the new built in `notarize` system. `electron-builder-notarize` will check and not notarize `mas` builds: https://github.com/karaggeorge/electron-builder-notarize/blob/efb683af5f4c5428ea6aa02df6a09a360563bfa0/index.js#L49 however https://github.com/electron/notarize does not seem to do that. This causes the notarization to fail because Mac App Store signed `mas` builds cannot be notarized:
```bash
Processing: /Users/runner/work/lossless-cut/lossless-cut/dist/mas-universal/LosslessCut.app
...
CloudKit query for LosslessCut.app (2/830f452ef727fad7dc1ae62586bf2442bff5fcb5) failed due to "Record not found".
Could not find base64 encoded ticket in response for 2/830f452ef727fad7dc1ae62586bf2442bff5fcb5
The staple and validate action failed! …
```
=> fix: Don't notarize mas builds

.changeset/brave-bats-brake.md, .changeset/spicy-kiwis-float.md, docs/auto-update.md, package.json, packages/builder-util-runtime/src/httpExecutor.ts, pnpm-lock.yaml, scripts/jsdoc/helpers.js
due to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66783 we got a downstream type error on httpExecutor's RequestHeaders
fixed by using OutgoingHttpHeader from node
bumped repo's @types/node to verify fix
=> fix: compat with newest @types/node

.changeset/quick-comics-cross.md, packages/app-builder-lib/package.json, packages/app-builder-lib/src/targets/FpmTarget.ts, packages/app-builder-lib/src/targets/archive.ts, packages/app-builder-lib/src/targets/nsis/NsisTarget.ts, packages/builder-util/package.json, packages/builder-util/src/util.ts, packages/electron-builder-squirrel-windows/package.json, packages/electron-builder-squirrel-windows/src/squirrelPack.ts, pnpm-lock.yaml, test/package.json, test/src/helpers/packTester.ts
Update `7zip-bin` to 5.2.0 which includes `win\arm64\7za.exe`.
Fixes error below when running `npx electron-builder --win` on Windows on ARM.
```
⨯ Exit code: ENOENT. spawn x\node_modules\app-builder-lib\node_modules\7zip-bin\win\arm64\7za.exe ENOENT  failedTask=build stackTrace=Error: Exit code: ENOENT.
```
=> fix(deps): Update 7zip-bin to support Windows on ARM

docs/auto-update.md
This PR has been made to add the "deb" and "rpm" targets to the list of auto-updatable targets, as deb and rpm auto-updaters seem to have been implemented in `electron-updater` since v24.0.0, which released in March.
=> fix: add deb and rpm to the auto-updatable targets list

.changeset/nervous-cheetahs-move.md, packages/app-builder-lib/src/targets/FlatpakTarget.ts
Fixes #7854
> When building for Flatpak, electron-builder (or rather app-builder-bin) creates a set of icons from the Mac icns file which includes a 1024x1024 sized icon. According to the [Flatpak spec](https://docs.flatpak.org/fr/latest/conventions.html#application-icons) however, icons must not be larger than 512px. This is the reason why the Flatpak build fails e.g. with the following error:
=> fix: flatpak build failing due to too large icons

.changeset/poor-lobsters-report.md, packages/app-builder-lib/src/macPackager.ts
see also #7859
I've tested this here https://github.com/mifi/lossless-cut/actions/runs/6719326573/job/18260738394
with a [patched macPackager.js](https://github.com/mifi/lossless-cut/blob/master/.yarn/patches/app-builder-lib-npm-24.8.0-51e1f5cd3f.patch)
=> feat: allow api key and keychain notarize

.changeset/popular-countries-type.md, packages/app-builder-lib/src/macPackager.ts, packages/app-builder-lib/src/targets/FlatpakTarget.ts
Pass buildOptions down to notarization to explicitly pull build options for `mas`. Don't run notarize if options are not provided
Fix: #7873
=> fix(mac): pass in correct notarize options

.changeset/silver-buckets-design.md, packages/app-builder-lib/src/macPackager.ts
introduced in #7861 
looking at the code, i noticed that this is probably a bug, here is the dist patch that's working: https://github.com/mifi/lossless-cut/blob/master/.yarn/patches/app-builder-lib-npm-24.8.0-51e1f5cd3f.patch
=> fix: fix probable bug

.changeset/metal-adults-impress.md, packages/app-builder-lib/src/macPackager.ts
#7861 added ways of api key auth. However, if we'd like to use api key, `teamId` must not be provided.
https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/macPackager.ts#L550C9-L550C15
The validation logic can be found at: https://github.com/electron/notarize/blob/main/src/validate-args.ts#L92-L98
=> fix(mac): notary with pure api key auth

.changeset/warm-pets-double.md, packages/app-builder-lib/src/electron/electronMac.ts
Electon uses the application name (CFBundleName) to resolve helper apps: https://github.com/electron/electron/blob/79e714a82506f133516749ff0447717e92104bc1/shell/app/electron_main_delegate_mac.mm#L65.
Fixes #6962.
=> fix(mac): use product name for helper apps

.changeset/thick-flowers-bathe.md, packages/app-builder-lib/src/appInfo.ts, packages/app-builder-lib/src/macPackager.ts, packages/app-builder-lib/src/util/filename.ts
Fixes issues when `productName` and `executableName` contain characters that have different NFC and NFD form, e.g., diacritics and Hangul (Korean). These seem to be internally normalized to the NFD form at some point, failing string comparison and other operations. Specifically,
- fixes codesign failing with `code object is not signed at all In subcomponent:`,
- fixes #6912
- https://github.com/electron-userland/electron-builder/issues/3169#issuecomment-800113654
- #5977
- https://github.com/electron/osx-sign/issues/155
- fixes DMG layout,
- #1234
- #1369
- #6282
- and possibly related:
- #2125
- #4697
=> fix(mac): normalize filename to NFD form

.changeset/nine-rings-bow.md, packages/dmg-builder/vendor/mac_alias/alias.py
This reverts commit 37a17f222b4802282c0638c163f76df35983c8d3 (#4841).
Since names are normalized to NFD as of #7901, normalizing them back to NFC leads to a similar error:
```
File "node_modules/dmg-builder/vendor/dmgbuild/core.py", line 290, in <module>
build_dmg()
File "node_modules/dmg-builder/vendor/dmgbuild/core.py", line 261, in build_dmg
icvp['backgroundImageAlias'] = biplist.Data(alias.to_bytes())
^^^^^^^^^^^^^^^^
File "node_modules/dmg-builder/vendor/mac_alias/alias.py", line 649, in to_bytes
self._to_fd(b)
File "node_modules/dmg-builder/vendor/mac_alias/alias.py", line 535, in _to_fd
cnid_path = struct.pack('>%uI' % len(self.target.cnid_path),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: 'I' format requires 0 <= number <= 4294967295
```
The error ony occurs in: …
=> revert: fix(mac): should normalize unicode strings from file system before used in string compare

.changeset/swift-dingos-live.md, packages/app-builder-lib/src/targets/snap.ts
This fixes #7907 "The channels option from SnapStoreOptions is not applied when publishing using Snapcraft"
=> fix: pass publish options to snap publisher

.changeset/silver-ties-taste.md, docs/configuration/win.md, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/options/winOptions.ts
=> docs: Update docs to include `msi-wrapped` target

.changeset/forty-teachers-run.md, packages/app-builder-lib/src/codeSign/windowsCodeSign.ts
fix: pull `resultOutputPath` from `CustomWindowsSignTaskConfiguration` (fixes: #7910)
=> fix(win): use `resultOutputPath` to sign custom location for windows

.changeset/cold-carpets-move.md, packages/app-builder-lib/src/util/NodeModuleCopyHelper.ts, test/snapshots/BuildTest.js.snap
Allowing `test.js` in compiled asar to allow testing mechanisms like Playwright
Fixes #7795
=> fix: Allow `test.js` in compiled asar

.changeset/long-suits-act.md, packages/dmg-builder/src/dmgUtil.ts
adding `-debug` to `hdiutil detach` for when it fails and attempts a force detach, such as for errors like "Resource is busy"
=> chore: add debug data for `hdiutil detach` when it initially fails

.changeset/quick-rocks-cover.md, packages/app-builder-lib/src/appInfo.ts, packages/app-builder-lib/src/codeSign/windowsCodeSign.ts, packages/app-builder-lib/src/index.ts, packages/app-builder-lib/src/options/metadata.ts, packages/app-builder-lib/src/packager.ts, packages/app-builder-lib/src/platformPackager.ts, packages/app-builder-lib/src/util/NodeModuleCopyHelper.ts
Use dynamic `import()` when `package.json` is set to [ES modules](https://nodejs.org/api/packages.html#type).
#7935
=> feat: ES module support

.changeset/shaggy-plums-live.md, packages/app-builder-lib/src/macPackager.ts
Notarization wasn't actually running when the API key is set and notarize was set to true. The notarize tool library throws when a API key is provided and teamId is set, so you have to set notarize to true, but when you do currently, the step never runs.
=> fix: notarization with an apple API key

.changeset/happy-otters-heal.md, packages/app-builder-lib/templates/nsis/include/allowOnlyOneInstallerInstance.nsh
On Windows 11, when the length of APP_EXECUTABLE_FILENAME exceeds 25 characters, the image name found through the tasklist command will be omitted, causing subsequent finde.exe to fail to find the specified process.
=> fix: product file name is too long causing the find process exe failed

.changeset/violet-icons-approve.md, docs/api/electron-builder.md, packages/electron-updater/src/AppUpdater.ts, packages/electron-updater/src/NsisUpdater.ts
add new option to skip differential download attempt and default to full download
Closes #4682
=> feat(nsis): add option to disable differential download

.changeset/dull-brooms-search.md, docs/generated/NsisOptions.md, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/targets/nsis/Defines.ts, packages/app-builder-lib/src/targets/nsis/NsisTarget.ts, packages/app-builder-lib/src/targets/nsis/nsisOptions.ts, packages/app-builder-lib/templates/nsis/assistedInstaller.nsh
Add the possibility to create an assisted NSIS installer and select per Machine as default option for installation.
We need this for our installer.
=> feat(nsis): add NsisOption to specify selectPerMachineByDefault

.changeset/forty-hats-press.md, packages/app-builder-lib/src/targets/archive.ts
I discovered that when I use the `--dir` option and `--prepackaged -c` to build different installers with various NSIS configurations, electron-builder repeatedly compresses the unpacked directory with 7zip. This process is time-consuming - in my case, it takes about 5 minutes to build one installer. To improve this, I implemented a modification time (mtime) check before the compression step, which is a common practice in build systems like GNU make. This change reduces the build time to 15 seconds per installer, making this use case more practical. It should not break the API.
=> feat(archive): skip archive when up to date

.changeset/stupid-bears-hammer.md, packages/app-builder-lib/src/targets/LinuxTargetHelper.ts
Fixes: https://github.com/electron-userland/electron-builder/issues/7977
This PR translates the `-` pre-release separator (as mandated by the [semver 2.0.0 spec](https://semver.org/), which is the format [accepted by `package.json`](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#version)) to a `~`, to match Debian's expectations on package versioning.
See the below examples:
```
$ dpkg --compare-versions 1.0.0 gt 1.0.0-rc1; echo $?
1
$ dpkg --compare-versions 1.0.0 gt 1.0.0~rc1; echo $?
0
```
The reason why using `~` fixes this is because [Debian orders the `~` "lower" than the end-of-string character](https://www.debian.org/doc/debian-policy/ch-controlfields.html#version), and afaiu the reason such a special character was needed is exactly for use cases such as pre-releases. …
=> fix(linux): Use ~ as pre-release separator for deb targets

.changeset/fresh-poems-greet.md, docs/configuration/mac.md, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/index.ts, packages/app-builder-lib/src/macPackager.ts, packages/app-builder-lib/src/options/macOptions.ts
Signal Desktop has a patch to enable this for its builds, but others may want this kind of extensibility in the future, and it matches the Windows config!
Please let me know if I've missed anything!
=> feat(mac): Support for a custom 'sign' function in mac config

.changeset/thirty-bobcats-beg.md, packages/app-builder-lib/src/codeSign/macCodeSign.ts
Rather than using something arbitrary, found on `PATH`, this makes sure we run Apple's signing utilities
Fixes #7997.
=> fix: Use full path to macOS signing utilities

.changeset/empty-ears-do.md, packages/electron-publish/src/publisher.ts
=> fix: use CI_COMMIT_TAG instead of CI_BUILD_TAG for Gitlab CI

.changeset/fifty-lions-burn.md, packages/app-builder-lib/src/electron/electronMac.ts, test/snapshots/mac/macPackagerTest.js.snap, test/src/mac/macPackagerTest.ts
`mac.extendInfo` may already contain entries for `CFBundleDocumentTypes`. Before this change, `fileAssociations` would overwrite previous `CFBundleDocumentTypes` properties. Now it merges.
I'm using this functionality so that I can add support for `public.folder`, so users can drag a folder onto the dock icon and the Electron app will recognise it.
=> fix(mac): merge `fileAssociations` with existing `CFBundleDocumentTypes` if defined in `mac.extendInfo`

.changeset/little-pumas-check.md, docs/configuration/configuration.md, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/configuration.ts, packages/app-builder-lib/src/util/NodeModuleCopyHelper.ts, test/snapshots/BuildTest.js.snap, test/src/BuildTest.ts, test/src/helpers/verifySmartUnpack.ts
=> feat: allow `onNodeModuleFile` to return a boolean to force include the package to be copied

.changeset/cold-sheep-camp.md, packages/app-builder-lib/package.json
seeing error with pnpm:
```
⨯ Cannot find module 'dmg-builder'
Require stack:
- /xxx/node_modules/.pnpm/app-builder-lib@24.13.0_patch_hash=rhv5z6uqia42ljlrohzdneemdi/node_modules/app-builder-lib/out/macPackager.js
- /xxx/node_modules/.pnpm/app-builder-lib@24.13.0_patch_hash=rhv5z6uqia42ljlrohzdneemdi/node_modules/app-builder-lib/out/packager.js
- /xxx/node_modules/.pnpm/app-builder-lib@24.13.0_patch_hash=rhv5z6uqia42ljlrohzdneemdi/node_modules/app-builder-lib/out/index.js
- /xxx/node_modules/.pnpm/electron-builder@24.13.0/node_modules/electron-builder/out/builder.js
- /xxx/node_modules/.pnpm/electron-builder@24.13.0/node_modules/electron-builder/out/cli/cli.js
- /xxx/node_modules/.pnpm/electron-builder@24.13.0/node_modules/electron-builder/cli.js  failedTask=build stackTrace=Error: Cannot …
```
=> fix: add dmg-builder and squirrel-windows to peerDependencies for pnpm

.changeset/twelve-boxes-film.md, packages/app-builder-lib/src/macPackager.ts
Fixes: https://github.com/electron-userland/electron-builder/issues/8040
=> fix(mac): only skip notarization step when `notarize` is explicitly false

.changeset/orange-goats-brake.md, packages/app-builder-lib/src/platformPackager.ts
Use `pathToFileUrl` to fix this error on Windows:
```
Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'  failedTask=build stackTrace=Error: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
```
#7935
=> fix: Windows ES module support

.changeset/mighty-pumpkins-battle.md, packages/app-builder-lib/src/platformPackager.ts, packages/app-builder-lib/src/targets/pkg.ts
Provide `BundlePreInstallScriptPath` and/or `BundlePostInstallScriptPath` when a pre/postinstall script is provided to pkg installer via buildResourcesDir -> `scripts` config
Fixes: #8063
=> fix(pkg): provide `BundlePreInstallScriptPath` and/or `BundlePostInstallScriptPath`

.changeset/chatty-dolphins-poke.md, packages/app-builder-lib/src/targets/MsiTarget.ts
Build x64 MSI installers when targeting the arm64 architecture. This results in an x64 MSI installer that installs an arm64 version of the application.
An x64 MSI installer is an improvement because building arm64 MSI targets errors with:
```
error CNDL0264 : The parameter 'arch' is missing or has an invalid value arm64.
Possible values are x86, x64, or ia64.
```
This is a stopgap until the electron-builder-binaries wix version is upgraded to a version that supports arm64 which is currently blocked by a number of breaking changes between 4.0.0.5512.2 and 4.0.1. This upgrade is discussed in #6077.
=> feat(msi): build emulated arm64 MSI installers

.changeset/lovely-fishes-impress.md, packages/app-builder-lib/templates/linux/after-install.tpl, test/snapshots/linux/debTest.js.snap
Soft symlink as fallback for `update-alternatives` to handle when /opt is on a separate partition
Also only execute `update-desktop-database` and `update-mime-database` when exists on the system
Fixes: #5721
=> fix(deb): only execute `update-desktop-database` and `update-mime-database` when exists on the system

.changeset/eighty-bobcats-eat.md, packages/app-builder-lib/src/codeSign/windowsCodeSign.ts
Revert "fix(win): use `resultOutputPath` to sign custom location for windows (#7919)". The property `resultOutputPath` is not meant to be overridden externally during the `sign` hook, other internal app-builder-lib logic explicitly depends on it for when the host machine is not Windows.
This reverts commit 4e930a74d7c2e9b53d47e37997b444da95680a24.
Fixes: #7973
=> fix(mac): sign NSIS on mac 

.changeset/wild-buttons-pretend.md, packages/app-builder-lib/src/codeSign/macCodeSign.ts, packages/app-builder-lib/src/macPackager.ts
=> fix(mac): add retry in mac code sign

.changeset/chatty-zebras-greet.md, packages/builder-util-runtime/src/updateInfo.ts, packages/electron-updater/src/AppUpdater.ts
=> feat: add minimumSystemVersion in electron updater

.changeset/pre.json, .changeset/twelve-points-whisper.md, .github/actions/pretest/action.yml, docs/configuration/configuration.md, packages/app-builder-lib/package.json, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/configuration.ts, packages/app-builder-lib/src/electron/electronVersion.ts, packages/app-builder-lib/src/util/packageMetadata.ts, packages/app-builder-lib/src/util/rebuild/rebuild.ts, packages/app-builder-lib/src/util/rebuild/remote-rebuild.ts, packages/app-builder-lib/src/util/yarn.ts, pnpm-lock.yaml, test/fixtures/test-app-two-native-modules/package.json, test/src/mac/macPackagerTest.ts
Feat: implementing electron/rebuild with config option `nativeRebuilder` default: `legacy` to preserve current functionality.
Yarn 3 removed the implicit link between `install` and `rebuild` steps, now requiring `rebuild` to be called directly. electron-builder's native rebuilding utilizes `app-builder` Go binary, which is not actively maintained and does not support yarn 3.
Setting `nativeRebuilder: 'sequential' // or 'parallel'` will utilize electron/rebuild during both the dependency installation phase (to make sure native modules are built the first time since `install` simply doesn't trigger it) and used again for any subsequent builds (such as mac universal builds). `sequential` and `parallel` values determine the `RebuildMode` for electron/rebuild
This inadvertently also enables …
=> feat: yarn 3 support for native modules

.changeset/dirty-rats-happen.md, docs/configuration/configuration.md, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/configuration.ts, packages/app-builder-lib/src/platformPackager.ts
=> feat: add disableSanityCheckPackage to asar to allow custom electron fork asar integrity implementations

.changeset/dirty-rats-happen.md, .changeset/mighty-spies-knock.md, docs/configuration/configuration.md, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/configuration.ts, packages/app-builder-lib/src/platformPackager.ts
fix: move `disableSanityCheckPackage` to within `checkFileInPackage` to not bypass non-asar usage
Renamed to `disableSanityCheckAsar` for more explicit definition
=> fix: move `disableSanityCheckAsar` to within `checkFileInPackage` for non-asar verification

.changeset/spotty-foxes-count.md, packages/app-builder-lib/src/winPackager.ts
=> fix(win): use appInfo description as primary entry for FileDescription

.changeset/fair-pants-talk.md, packages/app-builder-lib/src/asar/asarUtil.ts, test/snapshots/HoistedNodeModuleTest.js.snap, test/snapshots/globTest.js.snap
ASAR file begins with a header that list all files and an offset to each file in the rest of the file. When a file placed early in ASAR changes its length - it means that all subsequent file declarations in the header will have their offsets updated. While harmless by itself, this negatively affects the incremental download size as more of the installer binary is different from what it used to be.
In this change we order files in asar such that:
- Dependencies/node_modules come first (they change least often)
- Main app files come last (they change more frequently)
Additionally, files in asar are now ordered alphabetically within each fileset to guarantee stable output.
All of above results in 2x improvement of incremental download size for updates that don't change dependencies.
=> fix: order files in asar for incremental updates

.changeset/fast-maps-dress.md, packages/builder-util/src/util.ts, packages/dmg-builder/src/dmg.ts, packages/dmg-builder/src/dmgUtil.ts, packages/dmg-builder/src/hdiuil.ts
attempting to wrap all hdiutil's in a common retry mechanism for CI stability
=> fix: adding retries to account for dmg `hdiutil` flakiness 

.changeset/popular-jobs-protect.md, packages/app-builder-lib/templates/nsis/include/allowOnlyOneInstallerInstance.nsh
=> fix: replace SYSTEMROOT with SYSDIR

.changeset/selfish-experts-wonder.md, packages/builder-util/src/7za.ts
=> fix: should not chmod for 7za when process.env.USE_SYSTEM_7ZA is true

.changeset/moody-years-poke.md, docs/configuration/mac.md, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/macPackager.ts, packages/app-builder-lib/src/options/macOptions.ts
Previously, we supported notarizing with the legacy `altool` or the new `notarytool` API. The legacy tool has since been decommissioned.
1. Look at `APPLE_TEAM_ID` environment variable for getting the team to notarize as. Previously, when authenticating with an Apple ID, this property was used to determine whether to notarize with the old or new API. It's confusing to have the authentication split across these two places.
2. Mark legacy notarize API as deprecated and remove old validation.
Fixes https://github.com/electron-userland/electron-builder/issues/7812
=> feat: Make notarization with Apple ID more usable

.changeset/serious-pumpkins-suffer.md, docs/configuration/publish.md, packages/electron-publish/src/gitHubPublisher.ts
Reference: https://github.com/electron-userland/electron-builder/issues/5688 - Discussion about keeping two separate tokens; one for publishing to Github releases and the other used by the app to make requests for auto-update updates.
Now you can set a release token that has write permissions to publish your release.
The release token will be used instead of a GH_TOKEN || GITHUB_TOKEN ONLY during publishing.
The Github token defined via the Github options or environment variable will still be used as normal.
mac: ``` export GITHUB_RELEASE_TOKEN=<my token> ```
I used the Contents permission for a New fine-grained personal access token with "Read and write". "Read-only" for the usual app-update token.
So even if the app-update token is inside your app-update.yml its only read-only, yay! …
=> feat: Add Support for a separate Github release token to the auto-update token

docs/auto-update.md, docs/configuration/publish.md
I got so confused by the generic server options that I thought I'd document its behavior.
(Apparently GitHub Web cleaned up the trailing spaces for me …)
=> docs: Update auto updater docs

.changeset/gentle-bags-thank.md, packages/app-builder-lib/src/targets/AppxTarget.ts
Updated the identityName rule
https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-identity
Fixes: #8199
=> feat(appx): Update identityName for windows 10

.changeset/tough-clouds-think.md, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/configuration.ts, packages/app-builder-lib/src/platformPackager.ts
Add a hook that triggers after the prebuilt Electron binary has been extracted to the output directory.
What I was looking for is a `beforeAsar` (or `afterCopy`) hook, but looks like the file copying function is tightly coupled with asar transformation, this is the next best option.
Partially solves https://github.com/electron-userland/electron-builder/issues/8188 + https://github.com/electron-userland/electron-builder/issues/5619 + https://github.com/electron-userland/electron-builder/issues/4422 + https://github.com/electron-userland/electron-builder/issues/5709
=> feat: add `afterExtract` hook

.changeset/four-taxis-doubt.md, docs/configuration/configuration.md, docs/configuration/mac.md, packages/app-builder-lib/package.json, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/macPackager.ts, packages/app-builder-lib/src/options/macOptions.ts, pnpm-lock.yaml
Update [electron/osx-sign](https://github.com/electron/osx-sign), add macos signing option `additionalArguments`.
https://github.com/electron/osx-sign/pull/316
https://github.com/electron/osx-sign?tab=readme-ov-file#signing-with---deep
@develar @mmaietta TBR;
=> feat(mac): support macos signature additionalArguments parameter 

.changeset/selfish-turtles-fold.md, docs/api/electron-builder.md, packages/electron-updater/src/AppUpdater.ts
The `channel` option was documented as not working with GitHub, but it *does* work. Updated docs accordingly.
=> docs: channel works with Github

.changeset/thick-flies-carry.md, packages/app-builder-lib/package.json, packages/app-builder-lib/src/electron/ElectronFramework.ts, packages/app-builder-lib/src/electron/electronWin.ts, pnpm-lock.yaml
Electron 30-x-y added support for ASAR integrity fuse on Windows. When enabled the app would fetch the ELECTRONASAR resource out of the executable file and use it to verify the integrity of the ASAR when reading the data from it.
=> feat: write asar integrity resource on windows

.changeset/quiet-jars-leave.md, packages/builder-util-runtime/src/error.ts, packages/builder-util-runtime/src/httpExecutor.ts, packages/builder-util-runtime/src/index.ts, packages/builder-util-runtime/src/uuid.ts, packages/builder-util-runtime/src/xml.ts
After importing `electron-updater`, Rollup would log this warning:
```
(!) Circular dependencies
../../node_modules/.pnpm/builder-util-runtime@9.2.5-alpha.2/node_modules/builder-util-runtime/out/index.js -> ../../node_modules/.pnpm/builder-util-runtime@9.2.5-alpha.2/node_modules/builder-util-runtime/out/httpExecutor.js -> ../../node_modules/.pnpm/builder-util-runtime@9.2.5-alpha.2/node_modules/builder-util-runtime/out/index.js
../../node_modules/.pnpm/builder-util-runtime@9.2.5-alpha.2/node_modules/builder-util-runtime/out/index.js -> ../../node_modules/.pnpm/builder-util-runtime@9.2.5-alpha.2/node_modules/builder-util-runtime/out/uuid.js -> ../../node_modules/.pnpm/builder-util-runtime@9.2.5-alpha.2/node_modules/builder-util-runtime/out/index.js …
```
=> refactor: builder-util-runtime, separate newError to eliminate circular dependency

docs/configuration/contents.md
If I assume correctly, the order has accidentally been reversed, as `*/**` doesn't seem to make much sense to me.
=> fix(docs): get rid of typo in default glob pattern

.changeset/nice-weeks-sip.md, packages/app-builder-lib/src/util/NodeModuleCopyHelper.ts, packages/app-builder-lib/src/util/appFileCopier.ts
Fix https://github.com/electron-userland/electron-builder/issues/8252
=> fix: @electron/remote wrongly into Windows app.asar

.changeset/tender-countries-drive.md, packages/app-builder-lib/package.json, packages/app-builder-lib/src/index.ts, packages/app-builder-lib/src/macPackager.ts, packages/app-builder-lib/src/options/macOptions.ts, pnpm-lock.yaml
Updates @electron/notarize to v2.3.2 which should fix the issue with parsing errors created by `notarytool`
https://github.com/electron/notarize/pull/191
=> fix(deps): Update notarize tool

.changeset/spotty-timers-shave.md, packages/app-builder-lib/src/publish/PublishManager.ts
When using a custom publish provider, it is first attempted to be imported from the build resources, then if that fails, it attempts to import it from node_modules.
Currently, if the first attempted path fails, it logs the error to the console.
This happens multiple times per publish, and adds a lot of noise to the output.
Considering it's a (possibly) expected error, it would be better to move this to a debug log, with explanation.
=> fix: don't log ignored error when requiring custom publisher

.changeset/lazy-buttons-hunt.md, packages/app-builder-lib/src/asar/asar.ts
fix https://github.com/electron-userland/electron-builder/issues/8284
Refers to https://github.com/electron/asar/pull/253
=> fix: Folder's named "constructor" not being included in asar 

test/src/filesTest.ts, test/src/helpers/packTester.ts
Re-enabling extra resources and files tests now that the arch-specific build machines have been identified as the core reason for the flakiness. (Likely due to the new rollout of arm64 mac machines on Github Runners?)
=> chore: re-enable CI tests in FilesTest

.changeset/lovely-bottles-allow.md, packages/app-builder-lib/src/asar/unpackDetector.ts
If a module contains a folder with a name like `test.app` or `test.framework`, and there are binary files inside, it will be incorrectly processed and the module will be placed in `app.asar` instead of being smartly unpacked into `app.asar.unpacked`.
=> fix: binary checking

docker/build.sh, docker/node/Dockerfile, package.json
I just added node20 in build.sh, nothing mre
=> chore(docker): Add node20 build in docker/build.sh

.changeset/brave-bottles-sell.md, packages/app-builder-lib/src/util/yarn.ts, test/fixtures/test-app-two-native-modules/app/package.json, test/fixtures/test-app-two-native-modules/app/yarn.lock, test/snapshots/HoistedNodeModuleTest.js.snap, test/snapshots/mac/macPackagerTest.js.snap, test/src/helpers/verifySmartUnpack.ts, test/src/mac/macPackagerTest.ts
Setting `disablePreGypCopy: true` to handle mac universal builds (fixes #8347)
=> fix: setting `disablePreGypCopy: true` and updating unit test with `node-pty` native module

.changeset/polite-impalas-shout.md, packages/app-builder-lib/src/platformPackager.ts
fix: adding additional logging when importing/requiring a module in case the hook script is invalid or unable to be executed
=> fix: adding additional logging when importing/requiring a hook script

.changeset/purple-terms-sing.md, packages/app-builder-lib/templates/linux/after-install.tpl, test/snapshots/linux/debTest.js.snap
Fix #7545 (already closed but as stale, not actually fixed)
Setuid for chrome-sandbox is not needed on the vast majority of systems where user namespaces are available, as this more secure mechanism is used for sandboxing instead. Root setuid binaries like this are a general security risk, and appear to cause specific problems in various cases today (e.g. making a deb package unusable on Ubuntu 24.04: https://github.com/httptoolkit/httptoolkit/issues/602, making rpm packages fail validation on Fedora: https://github.com/bitwarden/clients/issues/5153)
User namespaces were implemented in 2013 (kernel 3.8), and have been enabled by default widely for many years. Chrome themselves stopped setting this in 2016, describing it as unnecessary on all supported Linux platforms: …
=> fix(linux): Don't setuid chrome-sandbox when not required

.changeset/silly-impalas-relax.md, packages/app-builder-lib/src/macPackager.ts, packages/app-builder-lib/src/platformPackager.ts, packages/builder-util/src/util.ts
Checking cancellation token during synchronous `build`, `universal` mac packaging, and any retry tasks to exit early on process "cancel" Ctrl+C
=> fix: cancellation token management for packager and retry logic

.changeset/happy-monkeys-rule.md, packages/app-builder-lib/src/util/NodeModuleCopyHelper.ts
Add the following filtering rule in the `files` section to exclude all files in the `headers` directory.
```
"files": [
"package.json",
"!**/*.{h,cpp}"
]
```
This will result in an empty directory, which will not generate a corresponding empty directory in `app.asar.unpack`. However, the symbolic links for `headers` will still be present. This will cause an error during signing, stating that the corresponding files cannot be found.
=> fix: delete the symlink file when the target is empty

.changeset/green-brooms-mix.md, packages/electron-updater/src/AppUpdater.ts
Calling `autoUpdater.checkForUpdates()` twice initiates two download processes that conflict and results in update failure. This PR adds a global download promise limiting the download processes to 1.
Fixes: https://github.com/electron-userland/electron-builder/issues/7063
=> fix: Add global download promise to limit concurrent downloads to 1

docs/index.md
Currently based on Vite v5 not v2
=> chore: update outdated docs for vite

.changeset/good-news-stare.md, packages/app-builder-lib/src/codeSign/windowsCodeSign.ts
Fixed: #7729 #8055
Signed-off-by: Kevin Cui <bh@bugs.cc>
=> fix(windows,code-sign): cannot sign binary files in Github Actions

.changeset/brown-singers-breathe.md, packages/app-builder-lib/src/asar/unpackDetector.ts, test/snapshots/BuildTest.js.snap
All npm C++ native modules generate a file ending in .node, which is an executable file. Currently, it is default practice to place these inside app.asar, which seems problematic for several reasons:
1. .node files are executables that need to be signed. If packed directly into app.asar, they cannot be signed.
2. According to official documentation, placing .node files inside app.asar can lead to performance issues and file not found errors.
https://www.electronjs.org/docs/latest/tutorial/asar-archives
4. Looking at applications like VSCode and Slack, they currently default to placing .node files in app.asar.unpack.
Therefore, I suggest that during the smart unpack process, we automatically detect files ending in .node and place them in the unpack directory.
=> feat: unpacked native node file

.changeset/clean-trainers-talk.md, packages/electron-updater/src/providers/GitHubProvider.ts
fix https://github.com/electron-userland/electron-builder/issues/8388
=> feat: add custom channel in github provider

.changeset/smooth-roses-laugh.md, docs/generated/PlatformSpecificBuildOptions.md, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/options/PlatformSpecificBuildOptions.ts, packages/app-builder-lib/src/util/NodeModuleCopyHelper.ts, test/src/BuildTest.ts
fix https://github.com/electron-userland/electron-builder/issues/8397
=> fix: add disableDefaultIgnoredFiles option

.changeset/sixty-plants-lie.md, packages/app-builder-lib/src/util/appFileCopier.ts
fix  https://github.com/electron-userland/electron-builder/issues/8401
=> fix: return parent dir for local dependency

.changeset/old-ducks-cry.md, packages/electron-updater/src/BaseUpdater.ts, packages/electron-updater/src/DebUpdater.ts
So @Ryan432 just discovered an amazing bug (and made a PR for the fix #8400) that produces problems with the auto updates when an application has spaces in the artifact name. However, it was only implemented for .deb specifically and the same issues exists with other package managers. 
So I moved the handling of spaces in installer paths to the point where the installerPath is generated, before the `doInstall` function is called so it's pre-formatted.
To address this, I updated the logic for managing installer paths to ensure compatibility across various Linux package managers:
- **Linux:** Spaces in paths are now escaped with `\ ` to ensure proper handling in shell commands.
This fix ensures that auto-updates work seamlessly regardless of whether the artifact name includes spaces.
=> fix: handle spaces in artifact name for all linux platforms instead of only .deb

packages/app-builder-lib/src/options/linuxOptions.ts
Noticed that while browsing the docs. Seemed easy to fix and contribute back a little 🙇‍♂️
---
By the way, the reason I was looking at the docs is because [some users of Simplenote Electron are reproting issues installing due to `gconf2`](https://github.com/Automattic/simplenote-electron/issues/3241). Any ideas how to work around it? Thanks!
=> docs: Fix a broken link formatting in the docs

.changeset/proud-cats-try.md, packages/electron-updater/src/windowsExecutableCodeSignatureVerifier.ts
by applying #8051 and noted in #8162 win signature verification of signatures created using
certificates including special chars like german
umlauts got broken in electron-updater >= 1.6.9
issue at hand is that the windows set command does not terminate when reading semicolon;
setting %PATH% is a good example for this
c.f. https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-xp/bb490998(v=technet.10) so instead commands should be concatenated using &
Closes #8162
=> fix: windows signature verification special chars

.changeset/strong-spiders-grab.md, packages/electron-updater/src/differentialDownloader/DifferentialDownloader.ts
There are many SimpleURLLoaderWrapper server error in sentrty, I think they might be caused by this event.
Here's a simple example:
```javascript
// test.js
'use strict';
// The same issue occurs with `http`, too.
const https = require('https');
const req = https.request('https://nodejs.org/dist/v13.7.0/node-v13.7.0.tar.gz');
req.on('response', (res) => {
res
.on('end', () => console.log('end'))
.on('close', () => console.log('close'))
.on('aborted', () => console.log('aborted'))
.on('error', (err) => console.log(err));
setTimeout(() => {
console.log('start');
req.abort();
}, 500);
});
req.end();
```
=> fix: change abort to aborted event

.changeset/chatty-mayflies-argue.md, packages/electron-updater/package.json, pnpm-lock.yaml
fix https://nvd.nist.gov/vuln/detail/CVE-2022-25883
=> chore(deps): upgrade semver to latest to resolve CVE

.changeset/stupid-avocados-appear.md, docs/api/electron-builder.md, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/linuxPackager.ts, packages/app-builder-lib/src/targets/snap.ts, packages/builder-util/src/arch.ts, packages/electron-builder/src/builder.ts, test/src/helpers/downloadElectron.ts
Reverts electron-userland/electron-builder#8143
=> fix: Revert "feat: allow `riscv64` support via custom electron dist"

.changeset/shy-cobras-smell.md, packages/app-builder-lib/src/electron/electronWin.ts, packages/app-builder-lib/src/electron/injectFFMPEG.ts, packages/app-builder-lib/src/publish/PublishManager.ts, packages/app-builder-lib/src/targets/FpmTarget.ts, test/snapshots/BuildTest.js.snap
chore: improving file path logging to be relative paths when within process.cwd()
Also updates BuildTest snapshot due to new SECURITY.md file in the `pump` npm package -> (asar file tree verification in `posix smart unpack` test detected this npm package change)
=> chore: update test snapshot and improve file path logging

.changeset/chatty-rice-hunt.md, packages/app-builder-lib/src/packager.ts, packages/app-builder-lib/src/util/appFileCopier.ts, packages/app-builder-lib/src/util/packageDependencies.ts, packages/electron-builder/src/cli/install-app-deps.ts
This PR fixes the mismatch in the dependency tree structure provided by the rebuild-node-modules command in the app-builder binary.
=> fix: correct native dependency tree mismatch in app-builder rebuild

.changeset/orange-radios-tie.md, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/configuration.ts, packages/app-builder-lib/src/index.ts, packages/app-builder-lib/src/targets/AppxTarget.ts, pages/configuration.md
Force using `applicationId` if provided before falling back to `identityName` or app `name`
Fixes: #8479
=> fix(appx): utilize `applicationId` verbatim when provided

.changeset/wise-turtles-heal.md, packages/app-builder-lib/src/util/yarn.ts
`debug` flag on electron-rebuild is for Release/Debug native rebuilds, not for logging
Fixes: https://github.com/electron-userland/electron-builder/issues/8529
=> fix: always produce Release .node builds

.changeset/real-otters-sparkle.md, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/codeSign/windowsSignAzureManager.ts, packages/app-builder-lib/src/options/winOptions.ts, test/src/windows/winCodeSignTest.ts
Ref: https://github.com/electron-userland/electron-builder/issues/8276#issuecomment-2371920176
=> fix: add `CodeSigningAccountName` as required prop in Azure Signing Options

.changeset/silly-cooks-allow.md, packages/builder-util/package.json, pnpm-lock.yaml
Try to fix  
https://github.com/electron-userland/electron-builder/issues/8493
https://github.com/electron-userland/electron-builder/issues/8519
https://github.com/electron-userland/electron-builder/issues/8503
In app-builder-bin(https://github.com/develar/app-builder/pull/138), if using pnpm, it will employ the simplest hoisting algorithm, which only elevates packages to higher levels (if possible) to reduce duplicate packages. This approach also ensures no other anomalies occur. For yarn/npm/pnpm with hoisting, it'll continue using the original algorithm, only reading the dependency tree from node modules without performing any hoisting.
=> chore(deps): update dependency app-builder-bin to 5.0.0-alpha.10

.changeset/dry-rockets-pretend.md, packages/electron-updater/src/MacUpdater.ts
fix https://github.com/electron-userland/electron-builder/issues/8507
https://github.com/electron-userland/electron-builder/blob/3b03f27245458a0b595b7a65c8634f184d32f2fa/packages/electron-updater/src/AppUpdater.ts#L698-L702
The problem lies here. If cachedUpdateFile already exists, the task function won't run; instead, the done function will be executed directly.
=> fix: Unable to copy file for caching: ENOENT

.changeset/three-fans-worry.md, packages/app-builder-lib/src/util/appFileCopier.ts, test/src/globTest.ts
fix https://github.com/electron-userland/electron-builder/issues/8460
Reproducible demo
```
{
"name": "TestApp",
"productName": "Test App ßW",
"description": "My Electron application description",
"keywords": [],
"main": "./main.js",
"version": "1.0.0",
"author": "beyondkmp",
"scripts": {
"start": "electron .",
"dist": "electron-builder"
},
"license": "MIT",
"build": {
"appId": "electron-blog-example",
"files": [
"!node_modules/@electron/remote/*"
],
"win": {
"target": "nsis"
}
},
"devDependencies": {
"electron": "32.1.0",
"electron-builder": "25.1.6"
},
"dependencies": {
"tar": "7.4.3",
"@electron/remote": "2.1.2"
}
}
```
=> fix: fix the main matcher patterns for !node_modules/@test/xxxx

.changeset/six-spoons-heal.md, packages/app-builder-lib/src/targets/nsis/nsisLicense.ts
fix https://github.com/electron-userland/electron-builder/issues/8512
If the file is already in UTF-8 BOM format, there's no need to convert it again. If it's converted again, it will result in garbled characters.
=> fix: check if the file already starts with a UTF-8 BOM

.changeset/swift-apricots-explode.md, packages/app-builder-lib/src/util/appFileCopier.ts, test/src/globTest.ts
fix https://github.com/electron-userland/electron-builder/issues/8558
The @isaacs/cliui package depends on string-width-cjs@4.2.3, but the package that's actually downloaded is string-width@4.2.3. The name in the path doesn't match the original name, which is causing an error.
Fix solution: Truncate based on scope depth, not by name.
```
"string-width-cjs": {
"from": "string-width",
"version": "4.2.3",
"resolved": "https://registry.npmjs.org/string-width/-/string-width-4.2.3.tgz",
"description": "Get the visual width of a string - the number of columns required to display it",
"license": "MIT",
"author": {
"name": "Sindre Sorhus",
"email": "sindresorhus@gmail.com",
"url": "sindresorhus.com"
},
"homepage": "https://github.com/sindresorhus/string-width#readme",
"repository": …
```
=> fix: Path does not end with the package name 

.changeset/tricky-files-speak.md, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/configuration.ts, packages/app-builder-lib/src/fileMatcher.ts, packages/app-builder-lib/src/util/AppFileWalker.ts, packages/app-builder-lib/src/util/filter.ts, packages/builder-util/src/fs.ts, test/snapshots/ignoreTest.js.snap, test/src/ignoreTest.ts
fix https://github.com/electron-userland/electron-builder/pull/6080  and support including node_modules in other subdirectories
**How to fix**
1. No file patterns
-  The final File patterns are `["**/*", "!**/node_modules/**", "!dist{,/**/*}", ...] `
2. File patterns with other sub node_modules `["/*", "**/sub/node_modules/**"]`
- File patterns are `["**/*", "!**/node_modules/**", "**/sub/node_modules/**", "!dist{,/**/*}", ...]`
3. File patterns without sub node_modules
-  The final File patterns are `["**/*", "!**/node_modules/**", "!dist{,/**/*}", ...]`
The final patterns above all filter out the node_modules in the app root directory. In filter.ts, we handle this by returning false by default if relative === 'node_modules', so it won't be filtered out. …
=> fix: support including node_modules in other subdirectories

.changeset/lucky-tigers-do.md, packages/app-builder-lib/src/fileMatcher.ts, packages/app-builder-lib/src/util/NodeModuleCopyHelper.ts, test/snapshots/HoistedNodeModuleTest.js.snap, test/snapshots/globTest.js.snap, test/snapshots/ignoreTest.js.snap, test/snapshots/mac/macPackagerTest.js.snap, test/src/globTest.ts
Adding `node_gyp_bins` to excluded directories and `pnpm-lock.yaml` & `.obj` to excluded files.
Adding additional symlinks "types" to globTest unit tests ("reverse" up one dir, same dir symlink, "downward" symlink)
The exclusions mirror the behavior that electron-forge's packager takes. For instance, `node_gyp_bins` directory commonly has extraneous symlinks for building (such as usually python3), but are not supposed to be in the final assets
=> fix: add additional default exclusions to copy logic

.changeset/two-rice-wash.md, mkdocs.yml, package.json, packages/app-builder-lib/package.json, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/configuration.ts, packages/app-builder-lib/src/index.ts, packages/app-builder-lib/src/platformPackager.ts, pages/tutorials/adding-electron-fuses.md, pages/tutorials/code-signing-windows-apps-on-unix.md, pnpm-lock.yaml, test/src/linux/debTest.ts, test/src/linux/flatpakTest.ts, test/src/linux/fpmTest.ts, test/src/linux/linuxArchiveTest.ts, test/src/linux/linuxPackagerTest.ts, test/src/linux/snapHeavyTest.ts, test/src/linux/snapTest.ts, test/src/mac/macPackagerTest.ts, test/src/windows/appxTest.ts, test/src/windows/assistedInstallerTest.ts, test/src/windows/msiTest.ts, test/src/windows/msiWrappedTest.ts, test/src/windows/oneClickInstallerTest.ts, test/src/windows/portableTest.ts, test/src/windows/squirrelWindowsTest.ts, test/src/windows/webInstallerTest.ts, test/src/windows/winPackagerTest.ts
feat: adding hardcoded interface for [FuseV1Config](https://github.com/electron/fuses/blob/0cf2a177e70dd81cc74c4449847287cd65ea140b/src/config.ts#L19-L34) so that electron-builder can integrate [@electron/fuses](https://github.com/electron/fuses) while also allowing scheme.json to still generated correctly
Resolves: #6365
There will be a new configuration object `electronFuses: FuseOptionsV1` and it executes `@electron/fuses` directly before signing as is recommended on the repo instructions: https://github.com/electron/fuses?tab=readme-ov-file#apple-silicon
I've also opened it up as a convenience method should you want to keep custom logic in your `afterPack` method called via
```
await context.packager.addElectronFuses(context, { ... })
``` …
=> feat: add integration for `@electron/fuses`

pnpm-lock.yaml, test/package.json
chore(deps): update fast-xml-parser to 4.4.1 to fix https://github.com/electron-userland/electron-builder/security/dependabot/31
=> chore(deps): update fast-xml-parser to 4.4.1

.changeset/stupid-buses-compete.md, packages/app-builder-lib/src/winPackager.ts
Reverts electron-userland/electron-builder#8125
The PR caused a regression where task manager shows the app description instead of the app name for the running process
Fixes: https://github.com/electron-userland/electron-builder/issues/8599
=> fix(win): Revert "fix(win): use appInfo description as primary entry for FileDescription"

.changeset/slimy-chairs-buy.md, packages/app-builder-lib/src/asar/asarUtil.ts
fix: checking relative path without separator as that doesn't work on Windows
=> fix: check relative path in `asarUtil` without path separator

.changeset/sixty-dogs-deliver.md, packages/app-builder-lib/src/codeSign/windowsSignAzureManager.ts
=> fix: add quotes to surround file path during azure signing to handle files with spaces

.changeset/wet-hats-drum.md, packages/electron-publish/src/httpPublisher.ts
During refactoring #8596, the `basename` import was changed from "path" to "path/posix", which doesn't properly reduce to the base name.
This caused some filenames to contain the absolute path after publishing.
=> fix: Remove path from published binaries

.changeset/gold-parents-complain.md, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/codeSign/windowsSignAzureManager.ts, packages/app-builder-lib/src/options/winOptions.ts
Fixes: https://github.com/electron-userland/electron-builder/issues/8626
=> fix(win): add rfc3161 timestamp entry as default for azure signing

.changeset/new-zoos-repair.md, packages/electron-updater/src/AppUpdater.ts, packages/electron-updater/src/MacUpdater.ts
Looks like only MacUpdater is the only updater that doesn't utilize the property. The code docs weren't updated when the auto-install-relaunch logic was added for Linux.
Fixes: https://github.com/electron-userland/electron-builder/issues/8630
Credit to @toddsouthenbentley for the code
=> feat(updater): allow usage of `autoRunAppAfterInstall` with mac updater

.changeset/sour-points-refuse.md, packages/app-builder-lib/src/codeSign/windowsCodeSign.ts, packages/app-builder-lib/src/winPackager.ts, test/src/windows/winCodeSignTest.ts
Removing Bluebird map w/ concurrency from signing flow as Azure Trusted Signing locks specific files each time it's being invoked.
Also adds retry functionality to the codesigning mechanism (already existed for signtool, added it for azure)
Fixes: https://github.com/electron-userland/electron-builder/issues/8615
=> fix: remove concurrency of windows codesign

.changeset/dull-eyes-check.md, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/codeSign/signManager.ts, packages/app-builder-lib/src/codeSign/windowsCodeSign.ts, packages/app-builder-lib/src/codeSign/windowsSignAzureManager.ts, packages/app-builder-lib/src/codeSign/windowsSignToolManager.ts, packages/app-builder-lib/src/options/winOptions.ts, packages/app-builder-lib/src/publish/PublishManager.ts, packages/app-builder-lib/src/targets/AppxTarget.ts, packages/app-builder-lib/src/winPackager.ts, test/src/windows/winCodeSignTest.ts
In order to support signature verification during auto-update flow with Azure Trusted Signing, a `publisherName` field must be added (mirrors that of signtool, except that one is optional).
Previously, the `publisherName` could be read from local signing certificate automatically, but we want to avoid having both signtool and Azure Trusted Signing accidentally being used at the same time as Azure Trusted Signing doesn't have a publisher name accessible at the time of app-update.yml being created. (app-update.yml creation is during `afterPack` stage, as opposed to `afterSign`)
=> fix(win): add mandatory `publisherName` field to Azure Trusted Signing

.changeset/fresh-camels-smash.md, packages/app-builder-lib/src/codeSign/macCodeSign.ts
Related to this issue: https://github.com/electron-userland/electron-builder/issues/8647.
Thank you!
=> fix: cscIKeyPassword must support empty string arguments

package.json, test/src/globTest.ts
**Error info**
```
> @electron-builder/monorepo@ prettier C:\Users\beyon\Code\electron-builder
> prettier 'packages/**/*.{ts, js}' 'test/src/**/*.ts' --write
[error] No files matching the pattern were found: "'packages/**/*.{ts,".
[error] No files matching the pattern were found: "js}'".
[error] No files matching the pattern were found: "'test/src/**/*.ts'".
 ELIFECYCLE  Command failed with exit code 2.
```
The modified command has been tested on Linux/Mac/Windows and is now working properly on all platforms.
=> fix: pnpm prettier cannot work in windows

.changeset/thirty-colts-march.md, packages/app-builder-lib/src/electron/electronWin.ts
Fix asar integrity info in `.exe` binary built from Linux by normalizing the file path using `path.win32`
Resolves https://github.com/electron-userland/electron-builder/issues/8690
I tested locally with the app in [issue reproduction gist](https://gist.github.com/Lemonexe/0f4b098febc1595914c1636e83b8c774) by compiling the local fix and linking it there.
I confirmed with `strings ./release/win-unpacked/asar-demo.exe | grep '"alg":"SHA256"'`
that it contains `resources\\app.asar` :heavy_check_mark: 
And running `wine ./release/win-unpacked/asar-demo.exe` no longer crashes :heavy_check_mark:
=> fix(win): corrupt asar integrity file path on crossplatform build

.changeset/small-windows-leave.md, packages/app-builder-lib/src/util/yarn.ts
fix https://github.com/electron-userland/electron-builder/issues/7103.
If node_modules doesn't exist at all, I think we can directly install all packages, not just the production ones. Even if we  reinstall all packages under the workspace again, it shouldn't cause any issues. 
At most, this approach would just take some extra time but won't lead to any problems.
=> fix: install all dependencies to fix building within NPM workspaces

.changeset/six-tips-play.md, packages/app-builder-lib/src/asar/asarUtil.ts, packages/app-builder-lib/templates/nsis/assistedMessages.yml
The assisted installer currently uses informal language that may not be appropriate for all users. This pull request updates the messages to use formal language to improve clarity and professionalism.
=> chore: Remove informal Russian messages in the NSIS installer

.changeset/shy-pumas-attack.md, packages/app-builder-lib/src/codeSign/windowsSignToolManager.ts
While working on learning how to set up code signing customization, the name `vmRequired` confused me a good bit, since it seemed to imply that a VM was required even when running on Windows.
=> chore: Rename `vmRequired` variable to `useVmIfNotOnWin`

mkdocs.yml, pages/code-signing-mac.md, pages/code-signing-root.md, pages/code-signing-win.md
Thank you @Chetan11-dev for putting this together!
Please review and see if there's any additional content/documentation you would like added.
Implements: #8621
=> chore(docs): adding video tutorial/introduction to macOS codesigning and notarization

.changeset/four-gorillas-nail.md, packages/builder-util-runtime/src/publishOptions.ts, packages/builder-util/package.json, packages/electron-publish/src/s3/s3Publisher.ts, pnpm-lock.yaml
=> feat(s3): add forcePathStyle option to S3Options

.changeset/odd-trees-battle.md, packages/electron-updater/src/AppImageUpdater.ts
Hi, this is my first contribution here so please LMK if I did something wrong. 
- I have a quite trouble running the tests. It produces a lot of errors that seem unrelated.
- I was able to run `pnpm compile && TEST_FILES=linuxUpdaterTest.ts pnpm ci:test` and it passed
- It also seems there is missing a test for AppImage (`test AppImage download`) is commented and not working
=> fix: use disableDifferentialDownload flag in the AppImageBuilder

.github/actions/pretest/action.yml
=> chore: update GHA actions/cache to v4.2.0

.github/workflows/deploy-docker.yml, .github/workflows/docker-build.yml, .github/workflows/test.yaml, docker/base/test.sh, docker/build.sh, docker/push.sh, package.json, pages/multi-platform-build.md
This is to resolve a few of my concerns:
- "No space left on device" when attempting to build node 14/16/18/20 images AND run tests.
- No space = unable to add node 22 to the pipeline
- Tests running in parallel with docker deployment instead of sequentially
Note: Temporarily disables the `docker push` command so as to test with docker deploy on-github-tag GHA event
New workflow:
Test flow:
1. Determine if docker directory has changes. If so, rebuild all docker images using a matrix of runners (reusable workflow docker-build.yml)
2. If docker images are rebuilt, they're uploaded as tar artifacts from each runner
3. Test runner(s) download the tar image for `TEST_IMAGE_NODE_MAJOR_VERSION` (currently 20) and execute tests
If docker deployment pipeline, complete all above steps from Test …
=> chore: refactor docker build/test/deploy workflows

.changeset/funny-pandas-worry.md, .github/workflows/docker-build.yml, .github/workflows/test.yaml, docker/base/Dockerfile, docker/node/Dockerfile, docker/wine-chrome/Dockerfile, docker/wine-mono/Dockerfile, docker/wine/Dockerfile, test/snapshots/HoistedNodeModuleTest.js.snap
- Required upgrading packages `python`->`python3`, wine-stable `6` -> `9`, and added `python2` for backward compatibility (note, `python` alias does not get created by `apt-get install`, must be accessed via `python2`)
- Adds `powershell` to `wine` image for Azure Signing
- Adds `--platform=linux/x86_64` in `FROM` line so as to allow building these images on arm64 macs
- Manually adds `libssl1.1` to `base` Docker image since Ubuntu 22.04 upgraded to `libssl3` and some upstream dependencies (e.g. `osslsigncode`) still require `libssl1.1`.
- Adds windows installer unit tests to linux matrix runners
=> chore(docker): upgrade image `buildpack-deps:focal-curl` to `jammy-curl` 22.04 (BREAKING)

.changeset/strong-timers-film.md, .github/actions/pnpm/action.yml, .github/actions/pretest/action.yml, .github/workflows/deploy-docker.yml, .github/workflows/docker-build.yml, .github/workflows/test.yaml, docker/node/Dockerfile, package.json, packages/electron-builder/package.json
This PR updates electron-builder to node 22 (note: this is separate from electron-updater) in order to adopt updates/fixes from @electron/* packages. Read more @ https://www.electronjs.org/blog/ecosystem-node-22
In order to continue supporting the ecosystem, this PR also adds a new docker image set for node 22. `electronuserland/builder:22`. This will now be `latest` tag
=> chore: deploy docker image w/ node 22

.github/workflows/deploy-docker.yml, docker/node/Dockerfile
Fixes: https://github.com/electron-userland/electron-builder/actions/runs/12857907910/job/35846664284
```
Run find /home/runner/work/_temp -type f -name "electron-builder-all-*.tar" -exec docker image load --input "{}" \;
write /blobs/sha256/b729d0d4583d5643ae5524776c32beeb[1](https://github.com/electron-userland/electron-builder/actions/runs/12857907910/job/35846664284#step:7:1)6104bef87a499098bb514093541db5a: no space left on device
write /blobs/sha256/bc995f40c4ff5af1b6fcc18f6d23c4e4146c150237a21454d8c4e[6](https://github.com/electron-userland/electron-builder/actions/runs/12857907910/job/35846664284#step:7:7)ec4e438abc: no space left on device
write /blobs/sha256/f315cb4a43eb539a64d546702b5cf46078ccfab6bab356a509d4eba44b325fcc: no space left on device
write …
```
=> fix: docker deploy script runs out of space

.changeset/cuddly-comics-cough.md, packages/dmg-builder/src/dmg.ts
Removes conditional logic that would build HFS+ dmg on non-arm64 macs as HFS+ was sunset in macos 15.2. The warning of this deprecation has been present for significant time and we can also drop support for macos <10.12 for electron-builder v26
Fixes: https://github.com/electron-userland/electron-builder/issues/8769
=> fix(mac): always build dmg's with APFS (BREAKING)

pages/auto-update.md
This moves the note to be closer to where it would be expected.
I discovered this note the hard way, as I didn't think to check the `Quick Setup Guide` for this, when there was a note under the `Auto-updatable Targets` heading stating similar limitations for windows
=> chore: update auto-update notes about macos requiring zip

.changeset/eighty-swans-hang.md, packages/app-builder-lib/src/macPackager.ts, packages/app-builder-lib/src/platformPackager.ts, test/src/helpers/CheckingPackager.ts
Without this `@electron/universal` would error complaining that the x64 and the arm64 builds varied in an unexpected place. Could have maybe overridden `addElectronFuses` in MacPackager, but we didn't have a reference to the fact we were building a universal package from the param in `doPack` and didn't want to explore adding more properties in the area.
Fixes https://github.com/electron-userland/electron-builder/issues/8798
=> fix(mac): only fuse macOS universal builds on the combined universal package

.changeset/beige-pillows-relate.md, packages/electron-updater/src/AppImageUpdater.ts, packages/electron-updater/src/BaseUpdater.ts, packages/electron-updater/src/DebUpdater.ts, packages/electron-updater/src/NsisUpdater.ts, packages/electron-updater/src/PacmanUpdater.ts, packages/electron-updater/src/RpmUpdater.ts
Revert move of space escape to BaseUpdater (from #8403) and instead do it separately in DebUpdater, PacmanUpdater and RpmUpdater as this escape breaks AppImageUpdater. Fixes #8698.
=> fix(linux): AppImage update when filename contains spaces

test/src/windows/winPackagerTest.ts
chore: adding retry to `winPackagerTest` since one test is pretty flaky when running on mac/linux? ¯\_(ツ)_/¯
Specifically the `beta` test:
```
Failed to open file: /tmp/et-db411cd21f3bbd882f3a5a30c58db6ff/t-pUzazs/test-project-0/dist/__uninstaller-nsis-TestApp.exe
```
Will investigate this later, and this should be considered a temporary resolution
=> chore: adding retry to `winPackagerTest`

.changeset/fresh-phones-return.md, packages/app-builder-lib/src/electron/ElectronFramework.ts, packages/app-builder-lib/src/util/yarn.ts
Prior to this `packages/app-builder-lib/src/util/yarn.ts` hard-coded the Electron headers `disturl` with no option to configure it for a local mirror.  This commit changes it to try the environment variable `npm_config_electron_headers_disturl` before using the hard-coded value. This lets users set the variable
`electron_headers_disturl=https://example.com/custom-headers-mirror` to use a local mirror.
=> feat: Allow users to pass a custom headers URL

.changeset/weak-owls-obey.md, packages/app-builder-lib/src/util/packageMetadata.ts
While trying to use #8829 through a `yarn patch electron-updater`, that causes this check to start failing as the version number in my package.json gets mangled to inject the patch.
This updates the check to pluck the version number out of the patch line, and check that instead
=> fix: handle yarn berry patch format in electron-updater version check

.changeset/fuzzy-trains-grab.md, packages/electron-updater/src/AppUpdater.ts, packages/electron-updater/src/main.ts
This clarifies a point of frustration I had while setting up the updater in an application.
I assumed that `null` would mean that there was no update, and got stuck when I discovered that the lib doesn't report whether the version was determined to be an update or not.
So this adds a property to inform the caller whether the version can be installed or not.
=> feat: add `isUpdateAvailable` property to `checkForUpdates` result

.changeset/tender-elephants-love.md, packages/app-builder-lib/src/codeSign/windowsSignAzureManager.ts
Also setting it as `-MinimumVersion` instead of Required to allow for future flexibility
Relates to https://github.com/electron-userland/electron-builder/issues/8700
=> fix: upgrading TrustedSigning module to 0.5.0

.changeset/kind-items-clean.md, packages/app-builder-lib/templates/linux/after-install.tpl, test/snapshots/linux/debTest.js.snap
This prevents `postinst` script failure when run in a `chroot` environment.
This closes #8841.
=> fix: Only update AppArmor profile if not chroot'ed

.changeset/many-lemons-press.md, packages/app-builder-lib/src/node-module-collector/nodeModulesCollector.ts, packages/app-builder-lib/src/node-module-collector/npmNodeModulesCollector.ts, packages/app-builder-lib/src/node-module-collector/pnpmNodeModulesCollector.ts, packages/app-builder-lib/src/node-module-collector/types.ts, packages/app-builder-lib/src/node-module-collector/yarnNodeModulesCollector.ts, test/snapshots/HoistedNodeModuleTest.js.snap, test/src/HoistedNodeModuleTest.ts
**Root Cause**
In the data returned by npm list, if there are duplicate packages with the same version in the dependencies, only one will be present.
**How to fix**
First, traverse all the packages and store them in a map. Then, when removing non-production dependencies, if you find that the dependencies are empty, retrieve them again from the complete list of packages.
**UT**
```javascript
//github.com/electron-userland/electron-builder/issues/8842
test.ifAll("yarn ms", () =>
assertPack(
"test-app-hoisted",
{
targets: linuxDirTarget,
},
{
isInstallDepsBefore: true,
projectDirCreated: projectDir => {
return Promise.all([
modifyPackageJson(projectDir, data => {
data.dependencies = {
"@sentry/electron": "5.11.0",
"electron-clear-data": "^1.0.5",
}
data.devDependencies = {
electron: …
```
=> fix: Fix the issue of the missing ms package

pages/code-signing-win.md
Hej! As announced in my recent issue, here are my suggestions to improve the Azure Trusted Signing documentation. I tried to find a balance between "not explaining everything" and ensuring that people understand the very confusing naming conventions Microsoft uses in its documentation (such as "Service Principal" versus "App Registration"). I believe that the way I tried to condense it hopefully makes it easier understandable for users to get started.
While writing the docs, I assumed as the "average" reader of this documentation someone with no experience with Azure who only wants to implement code signing. Because of this, I decided to add a "minimal viable setup" guide to help people get started, but keep the documentation in there to tell people "Hey, if you need another setup …
=> feat: Improve Azure Trusted Signing Docs

.changeset/fresh-rats-hide.md, packages/builder-util/src/DebugLogger.ts, packages/builder-util/src/deepAssign.ts, packages/builder-util/src/mapper.ts
https://github.com/electron-userland/electron-builder/security/code-scanning/9
https://github.com/electron-userland/electron-builder/security/code-scanning/10
https://github.com/electron-userland/electron-builder/security/code-scanning/11
https://github.com/electron-userland/electron-builder/security/code-scanning/12
=> fix: validate key before proceeding with deep assignment

test/src/globTest.ts
error by npm install
```
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: electronSquirrelDemo@1.0.0
npm error Found: react@18.2.0
npm error node_modules/react
npm error   react@"18.2.0" from the root project
npm error   peer react@"*" from @react-navigation/stack@6.3.7
npm error   node_modules/@react-navigation/stack
npm error     @react-navigation/stack@"6.3.7" from the root project
npm error   1 more (@react-navigation/native)
npm error
npm error Could not resolve dependency:
npm error peer react@"^19.0.0" from react-native@0.78.0
npm error node_modules/react-native
npm error   peer react-native@"*" from @react-navigation/stack@6.3.7
npm error   node_modules/@react-navigation/stack
npm error …
```
=> chore(tests): use `yarn` instead of `npm install` to resolve unit test instability

test/snapshots/HoistedNodeModuleTest.js.snap
The size of `index.js` in `require-in-the-middle` has changed, which means the entire test snapshot needs to be updated.
=> chore(tests): update test snap to resolve unit test instability

.changeset/lemon-moles-rhyme.md, packages/app-builder-lib/src/node-module-collector/index.ts, packages/app-builder-lib/src/node-module-collector/nodeModulesCollector.ts, packages/app-builder-lib/src/node-module-collector/npmNodeModulesCollector.ts, packages/app-builder-lib/src/node-module-collector/pnpmNodeModulesCollector.ts, test/snapshots/HoistedNodeModuleTest.js.snap, test/src/HoistedNodeModuleTest.ts
Fixes: https://github.com/electron-userland/electron-builder/issues/8881
=> fix: allow usage of `node-linker=hoisted` with pnpm

.changeset/few-zebras-swim.md, packages/app-builder-lib/src/packager.ts, packages/app-builder-lib/src/util/asyncEventEmitter.ts
Removes Promise ability from `.on` assignment of listeners in AsyncEventEmitter as it's impossible to filter listeners without `filterListeners` being async.
=> fix: `AsyncEventEmitter` `filterListeners` doesn't work with promises

test/snapshots/HoistedNodeModuleTest.js.snap, test/src/globTest.ts
fixtures that install deps had sub-deps change again. We need to figure out a way to utilize `--frozen-lockfile` or similar for our fixtures
=> chore: update snapshots and pin fixture dep versions

.changeset/sixty-crabs-approve.md, packages/app-builder-lib/src/macPackager.ts
Fixes: https://github.com/electron-userland/electron-builder/issues/8861 https://github.com/electron-userland/electron-builder/issues/7995
=> fix(mac): when using default `osx-sign`, specifically pass in identity name instead of hash

.changeset/spicy-cougars-type.md, packages/app-builder-lib/templates/nsis/uninstaller.nsh
fix https://github.com/electron-userland/electron-builder/issues/8874.
=> fix(win): execute `customUnInstall` before `atomicRMDir` function in NSIS uninstaller

.changeset/wise-apples-look.md, packages/app-builder-lib/templates/linux/after-install.tpl
Merely the presence of a config directory does not imply a functional apparmor installation. Instead, just ask apparmor itself if it is enabled.
This fixes #8931
=> fix: `after-install.tpl`: Detect if apparmor is enabled instead of just file-exists check

.changeset/light-pandas-reply.md, packages/electron-updater/src/types.ts
fix: re-export `CancellationToken`, `PackageFileInfo`, `ProgressInfo`, `UpdateFileInfo`, `UpdateInfo` from electron-updater
Fixes: https://github.com/electron-userland/electron-builder/pull/8913#discussion_r1978579715
CC @lyswhut
=> fix: re-export various types from electron-updater

.changeset/old-shrimps-invite.md, packages/app-builder-lib/src/node-module-collector/packageManager.ts, packages/app-builder-lib/src/util/yarn.ts
Fixes: https://github.com/electron-userland/electron-builder/issues/8938
=> fix: find cwd using `getProjectRootPath` for detecting package manager

.changeset/bright-students-add.md, packages/app-builder-lib/src/platformPackager.ts
Fixes: https://github.com/electron-userland/electron-builder/issues/8946
=> fix: support `mas` packages for flipping fuses

.github/workflows/test.yaml
Necessary transition due to https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised#
Note: The electron-builder was pinned specifically to a sha, not a version tag, and thus was not impacted by the compromise.
=> fix: re-enable CI build workflow by swapping in `dorny/paths-filter`

.changeset/friendly-drinks-allow.md, packages/app-builder-lib/src/codeSign/windowsSignAzureManager.ts
Azure trust signing fails when parameters contain spaces or special characters, breaking the build process for applications using this signing method.
By properly escaping PowerShell parameter values using single quotes and handling existing quotes in values.
- Added string value wrapping with single quotes
- Escape existing single quotes by doubling them (`''`)
- Converted parameters to string to ensure consistent handling
While this approach quotes all parameters, it remains compatible with the various parameter types used by `Invoke-TrustedSigning`:
- String parameters (like `-Files`, `-Endpoint`, `-CertificateProfileName`): Properly handled with quotes to preserve spaces
- Integer parameters (like `-FilesFolderDepth`): PowerShell automatically converts quoted values like `'0'` to …
=> fix: Azure trust signing fails with spaces in parameters

.changeset/perfect-pumpkins-repeat.md, packages/app-builder-lib/src/codeSign/windowsSignAzureManager.ts
Resolves https://github.com/electron-userland/electron-builder/issues/8985.
=> fix: malformed Files param when using Azure Trusted Signing

.changeset/tame-radios-pump.md, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/codeSign/macCodeSign.ts, packages/app-builder-lib/src/macPackager.ts, packages/app-builder-lib/src/options/macOptions.ts, pages/code-signing-mac.md
Fixes #5850
If no signing identity is present while an app is built and it is downloaded via a web browser, macOS on ARM shows "app is damaged" errors that are hard to bypass for the average user (see #5850 and some other duplicates). This seems to be because the default signature applied by the linker to the executables isn't valid due to something the build system is doing [1]. It is thus an error to not manually codesign the resulting app, even if no stable signing identity is available (in which case it must be an ad-hoc signature).
The damaged warning is **not** the same as the unverified warning. Not paying for a developer account does not mean your app must show "this app is damaged" warnings to users, but it will show an unverified warning. The damaged warning cannot be bypassed …
=> fix(mac): allow ad-hoc identities for codesigning

.changeset/wicked-zebras-begin.md, packages/electron-updater/src/AppUpdater.ts, packages/electron-updater/src/providers/Provider.ts
Each commit explains why the fix was required, but TLDR:
- Without a lowercase on the file extension, `https://myurl.com/myfile.AppImage` can never be equal to `AppImage`. I think it worked for most people because of the fallback 3 that takes whatever first file which is not in the `not`. In my case this file was a `tar.gz` so that didn't work.
- Since the extension didn't match it also took the `else` clause to generate the download file name which is based on the url. This generates invalid paths on the disk since it tries to create a file `pending/temp-https:/myurl.com/myfile.tar.gz`. I decided to use a sha1 instead of random so at least it will be stable between restarts since we check if the file is already downloaded.
We might want to change the logic of `getCacheUpdateFileName` to …
=> fix: missing lowercase comparison in electron-updater

.changeset/tall-geese-invite.md, packages/app-builder-lib/src/packager.ts, packages/app-builder-lib/src/util/appFileCopier.ts, packages/app-builder-lib/src/util/yarn.ts, packages/electron-builder/src/cli/install-app-deps.ts, test/snapshots/HoistedNodeModuleTest.js.snap, test/src/HoistedNodeModuleTest.ts
fix https://github.com/electron-userland/electron-builder/issues/9011
Under the two `package.json` framework, if there are no `node_modules` in the `app` directory and `npmRebuild` is set to `false`, dependencies will not be reinstalled. As a result, `npm list` will return empty. In this case, we should attempt to retrieve the `node_modules` using the `projectDir`, which can resolve this issue.
Using `getProjectRootPath` directly from `electron/rebuild` is not accurate because it recursively searches upward level by level and returns the first match it finds. If I set the `app` directory outside the `project dir`, such as in another directory, the result returned by `getProjectRootPath` in `electron/rebuild` will be incorrect. Therefore, the `projectDir` should be passed in directly …
=> fix: dependency path is undefined

.changeset/four-cheetahs-wash.md, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/targets/nsis/NsisTarget.ts, packages/app-builder-lib/src/targets/nsis/nsisOptions.ts, packages/app-builder-lib/src/targets/nsis/nsisUtil.ts
Prior to this change `customNsisBinary` could be used to override the url of `nsis-*.7z` from the `electron-builder-binaries` repo to a custom location. However, there was no option to change the url of the `nsis-resources-*.7z` file.
With this chcange the url of the NSIS resources could also be overriden.
=> feat: customNsisResources override in nsis options

.changeset/sweet-jeans-brake.md, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/targets/nsis/nsisOptions.ts
When using `electron-builder --win --x64 --arm64` to build NSIS, we can set buildUniversalInstaller to false to avoid generating a universal setup EXE. However, a universal portable EXE is still generated. Add a configuration to control whether to generate the universal portable EXE.
=> feat: add buildUniversalInstaller option to NSIS portable configuration

.changeset/late-drinks-drive.md, packages/app-builder-lib/src/targets/FpmTarget.ts, packages/app-builder-lib/src/targets/tools.ts
Fairly straight-forward translation of https://github.com/develar/app-builder/blob/master/pkg/package-format/fpm/fpm.go
This will make it much easier to update fpm and innately test within electron-builder's CI/CD without interspersed updates of app-builder project.
=> chore: migrate fpm packaging from app builder

.changeset/purple-tigers-guess.md, packages/electron-updater/src/differentialDownloader/multipleRangeDownloader.ts
The `Content-Type` response is as follows: `Content-Type: multipart/byteranges; boundary=799ddd5a-943e-4e22-981d-e32596ca39d2`. The `boundary` can have a space before it or no space at all. 
Here's the rfc:
https://datatracker.ietf.org/doc/html/rfc7231#section-3.1.1.1
**Issue**
Currently, the check only accounts for cases where there is a space. If some servers return a response without a space, it will cause incremental downloads to fail.
**Error Info**
```
17:13:29.256 > Full: 92,770.98 KB, To download: 19,742.1 KB (21%)
17:13:29.633 > Cannot download differentially, fallback to full download: Error: Content-Type "multipart/byteranges" is expected, but got "multipart/byteranges;boundary=e888c103-165d-4ec1-9b6f-eca722ac9b10"
at ClientRequest.<anonymous> …
```
=> fix: update regex for multipart content-type parsing in multipleRange

.changeset/blue-icons-push.md, packages/app-builder-lib/src/node-module-collector/index.ts, packages/app-builder-lib/src/node-module-collector/packageManager.ts, packages/app-builder-lib/src/util/yarn.ts, test/src/BuildTest.ts, test/src/HoistedNodeModuleTest.ts, test/src/globTest.ts, test/src/ignoreTest.ts
fix https://github.com/electron-userland/electron-builder/issues/8970#issuecomment-2830421527
- Replaced the `detect` and `getPackageManagerVersion` functions with a new `detectPackageManager` function for better clarity and type safety.
- Updated the `PM` type to an enum for improved maintainability.
- Adjusted the logic in `getCollectorByPackageManager` and `installDependencies` to utilize the new detection method.
- Cleaned up unused code and comments in `packageManager.ts` and `yarn.ts` files.
=> refactor: update package manager detection and improve type handling

pages/auto-update.md
A dedicated release server is not needed anymore (https://www.electronjs.org/docs/latest/tutorial/updates#using-cloud-object-storage-serverless) but a major existing difference is that only electron-updater supports Linux.
=> docs: replace difference to built-in autoUpdater

.changeset/soft-pets-warn.md, packages/dmg-builder/src/dmgUtil.ts
Use `--force` to unmount dmg when using hdiutil after 3sec delay if receiving error code 16 (resource is busy)
=> fix(dmg): `--force` unmount dmg using hdiutil after delay on Resource Lock (code 16)

.changeset/old-games-wait.md, .github/workflows/test.yaml, packages/dmg-builder/src/dmgUtil.ts, packages/dmg-builder/src/hdiuil.ts, test/snapshots/mac/dmgTest.js.snap, test/src/mac/dmgTest.ts
Using older windows runner to attempt to more consistently build in order, and added a unique `productName` for all dmg's to prevent collision
Added human-readable logging for hdiutil error codes and refactoring logic to retry only for transiet errors.
=> refactor(dmg): add human-readable hdiutil log messages and refactoring to only retry on transient error codes

.changeset/three-schools-beam.md, .github/workflows/test.yaml, packages/app-builder-lib/src/electron/ElectronFramework.ts, test/snapshots/ExtraBuildResourcesTest.js.snap, test/src/ExtraBuildResourcesTest.ts, test/src/mac/macPackagerTest.ts, test/src/windows/winCodeSignTest.ts
Turns out that `ExtraBuildResourcesTest` wasn't running in the CI. Now it will
Fixes: https://github.com/electron-userland/electron-builder/pull/9126#issuecomment-2948662417
=> fix: `electronDist` - detect if directory and copy electron from there, short circuit current logic path

.changeset/thin-geckos-dream.md, packages/app-builder-lib/templates/nsis/installer.nsi, packages/app-builder-lib/templates/nsis/uninstaller.nsh, pages/nsis.md
- Added support for uninstall components page.
- Uninstall section is RO (readonly)
- Uninstall section can be rename via `UNINSTALL_SECTION_NAME` definition
Example (installer.nsh):
```nsis
!define UNINSTALL_SECTION_NAME "Odinstalovat prohlížeč"
!macro customUnInstallSection
Section /o "un.Vymazat data aplikace"
RMDir /r "$APPDATA\${PRODUCT_NAME}"
SectionEnd
!macroend
; ...
```
=> feat(nsis): added supports for uninstall components page

.changeset/heavy-hats-wonder.md, packages/app-builder-lib/src/codeSign/macCodeSign.ts, packages/app-builder-lib/src/codeSign/windowsCodeSign.ts, packages/app-builder-lib/src/codeSign/windowsSignToolManager.ts, packages/app-builder-lib/src/node-module-collector/index.ts, packages/app-builder-lib/src/node-module-collector/nodeModulesCollector.ts, packages/app-builder-lib/src/node-module-collector/npmNodeModulesCollector.ts, packages/app-builder-lib/src/node-module-collector/packageManager.ts, packages/app-builder-lib/src/node-module-collector/pnpmNodeModulesCollector.ts, packages/app-builder-lib/src/node-module-collector/yarnNodeModulesCollector.ts, packages/app-builder-lib/src/util/appFileCopier.ts, packages/builder-util-runtime/src/retry.ts, packages/builder-util/src/log.ts, packages/builder-util/src/util.ts, packages/dmg-builder/src/hdiuil.ts, packages/electron-updater/src/AppUpdater.ts, test/src/helpers/packTester.ts, test/src/linux/fpmTest.ts
Fixes: https://github.com/electron-userland/electron-builder/issues/9020.
Research is here: https://github.com/electron-userland/electron-builder/issues/9020#issuecomment-3006486452
TLDR; having `shell: true` can result in malformed JSON because console could log something during profile loading. We need to remove the `shell: true`, but `.cmd` and spaces in the path are not supported when not an explicit executable on Windows. This is a particular caveat of Windows requiring a workaround
Solution:
- cross-platform
- JSON-safe without console Profile log noise (e.g. shell: false)
- supports .cmd/.bat/.exe and no-extension file paths
- works with paths containing spaces
- automatic temp .bat creation only when necessary
Might fix OOM: …
=> fix: Use `spawn` without `shell: true` for node module collection

.changeset/famous-berries-clap.md, packages/app-builder-lib/templates/nsis/multiUser.nsh
Added a new macro `GetDParameter` to improve handling of the /D command line parameter in NSIS scripts. This function extracts the installation path correctly even when it contains spaces, ensuring compatibility with the NSIS requirements for the /D parameter.
fix #7946 
test results:
=> fix(nsis): implement custom function to handle /D parameter with spaces

.changeset/funny-bottles-occur.md, packages/builder-util-runtime/src/httpExecutor.ts, packages/builder-util-runtime/src/index.ts, packages/builder-util-runtime/src/publishOptions.ts, packages/electron-updater/src/providerFactory.ts, packages/electron-updater/src/providers/GitLabProvider.ts, test/snapshots/updater/nsisUpdaterTest.js.snap, test/src/updater/nsisUpdaterTest.ts
```typescript
autoUpdater.setFeedURL({
provider: 'gitlab',
projectId: 12345,
token: process.env.GITLAB_TOKEN // for private repos
})
```
Let me know, if need to update.
=> feat(electron-updater): add GitLab provider

README.md, packages/electron-builder/src/builder.ts, pages/cli.md
* Fixes broken or outdated links in `cli.md` and `builder.ts`
* Makes sure all CLI and builder references point to the correct URLs
=> fix: correct broken links in builder.ts and cli.md

.changeset/rude-donuts-bathe.md, packages/app-builder-lib/src/util/yarn.ts
fix https://github.com/electron-userland/electron-builder/issues/6448
In a workspace setup, the `node_modules` inside the app directory often doesn't exist, while the one in the project directory does. Therefore, we can add an additional check to verify the existence of `node_modules` in the project directory.
=> fix(yarn): check for dependencies in both projectDir and appDir during installation

test/snapshots/updater/nsisUpdaterTest.js.snap
To test the getBlockMapFiles() feature in [electron-builder PR #9209](https://github.com/electron-userland/electron-builder/pull/9209), I published a new release (v1.1.0) in the GitLab repository ([gitlab-electron-updater-test](https://gitlab.com/daihere1993/gitlab-electron-updater-test)). This caused the GitLab-related tests to fail on the master CI.
Raise this PR to fix the failing tests, so they no longer block the CI on the master branch.
=> fix: gitlab related failed cases

.changeset/lovely-geckos-chew.md, packages/electron-builder-squirrel-windows/src/SquirrelWindowsTarget.ts
fix https://github.com/electron-userland/electron-builder/issues/9184
=> fix(squirrel-windows): update loadingGif handling to prioritize user-defined option

.changeset/sharp-elephants-shout.md, packages/electron-updater/src/LinuxUpdater.ts
When updating an application on a system without graphical authentication agents the `sudo` execution fails with `command not found` because the command is wrapped in quotes.
This pull request removes the wrapper quotes when using the `sudo` fallback command if no authentication agent is found.
=> fix(electron-updater): Do not wrap update command when updating with sudo

.changeset/rotten-bags-carry.md, packages/electron-builder/src/publish.ts
Fixes:
- https://github.com/electron-userland/electron-builder/issues/9005 
Caused by:
- https://github.com/electron-userland/electron-builder/pull/8596 
---
**Fixes mismatched argument names:**
`config` ↔ `configurationFilePath`
**Resolves conflicts caused by the reserved word 'version' in [yargs](https://github.com/yargs/yargs), and removes warning messages (Output before fix):**
```bash
$ npx electron-builder publish -f foobar.dmg
(node:7826) Warning: "version" is a reserved word.
Please do one of the following:
- Disable version with `yargs.version(false)` if using "version" as an option
- Use the built-in `yargs.version` method instead (if applicable)
- Use a different option key
https://yargs.js.org/docs/#api-reference-version
```
=> fix: fix argument names mismatch in publish command to make it work

.changeset/long-wasps-divide.md, packages/electron-builder/src/publish.ts
Related:
- https://github.com/electron-userland/electron-builder/issues/4535 
- https://github.com/electron-userland/electron-builder/pull/8150 
---
**Add support for overriding the policy option in the 'publish' command, like the 'build' command:**
```bash
electron-builder --publish always
electron-builder publish --policy always
```
**This change is necessary to override the [intended behavior in the CI environment](https://www.electron.build/publish.html#how-to-publish) (See the following code):**
https://github.com/electron-userland/electron-builder/blob/cf0ac45db79e3e3ff1cef3ad931f7272646d1cb1/packages/app-builder-lib/src/publish/PublishManager.ts#L87-L94
**Currently, the 'publish' command(CLI) has a problem where it cannot read the configuration file path. The following PR resolves …
=> fix: support option to override publish trigger (`--policy`) in publish command

.changeset/chatty-points-shop.md, packages/app-builder-lib/scheme.json, packages/app-builder-lib/src/publish/PublishManager.ts, packages/builder-util-runtime/src/index.ts, packages/builder-util-runtime/src/publishOptions.ts, packages/electron-publish/src/gitHubPublisher.ts
This adds support for an optional `tagNamePrefix` setting in `GithubOptions`. This is joined by the a new `githubTagPrefix()` function that handles the creation of any prefix that should be prepended to the version number. When present, `tagNamePrefix` will override any `vPrefixedTagName` value.
This allows users of github updates to use any tag prefix they like. This makes the updater more adaptable and more easily used in monorepo projects that may use multiple different tag prefixes to mark the versions of different packages within the repo.
=> feat(github): Add `tagNamePrefix` option

.changeset/hot-cars-attack.md, packages/electron-updater/src/windowsExecutableCodeSignatureVerifier.ts
After the `Get-AuthenticodeSignature` command fails, in the error handler there is an additional `ConvertTo-Json test` command that should be called in the same way as `Get-AuthenticodeSignature`. Without this, `Get-AuthenticodeSignature` could fail simply due to the workarounds used (using `shell:true` `chcp 65001 >NUL` https://github.com/electron-userland/electron-builder/pull/7230 and resetting `PSModulePath` https://github.com/electron-userland/electron-builder/pull/8051), which is unintended behavior. 
After this fix, when the workarounds fail, the `ConvertTo-Json test` command will also fail (with the message `Ignoring signature validation due to unsupported PowerShell version`) and the update will be installed.
=> fix: auto-update powershell script

.changeset/tough-walls-bathe.md, packages/app-builder-lib/src/node-module-collector/index.ts, packages/app-builder-lib/src/node-module-collector/packageManager.ts, packages/app-builder-lib/src/util/appFileCopier.ts, packages/app-builder-lib/src/util/yarn.ts, test/src/helpers/packTester.ts
When using yarn to manage a two package.json structure, if pnpm is installed globally (i.e., the PNPM_HOME environment variable exists), it may result in the package manager being detected incorrectly.
=> fix: detect wrong package manager for two package.json structure

.changeset/old-spies-lick.md, packages/app-builder-lib/templates/nsis/include/allowOnlyOneInstallerInstance.nsh
Currently, if your NSIS script defines `customCheckAppRunning`, building fails with `Variable "CmdPath" not referenced or never set, wasting memory!`. PR fixes this by not always declaring the unused variables.
=> fix(nsis): undefined vars when customCheckAppRunning is defined
